platform :ios, '7.0'
pod 'UIAlertView+Blocks', '~> 0.7'
pod 'UIActionSheet+Blocks', '~> 0.8.1'
pod 'ExtendNSLog', '~> 1.0.1'
pod 'AFNetworking', '~> 2.3.1'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.0.5'
pod 'ProtocolBuffers', '~> 1.9.2'
pod 'CocoaAsyncSocket', '~> 7.3.5'
pod 'ZBarSDK', '~> 1.3.1'
pod 'MBProgressHUD', '~> 0.9'
pod 'MJRefresh', '~> 0.0.1'
pod 'XXNibBridge', '~> 2.1'
pod 'Masonry', '~> 0.6.0'
pod 'SBJson', '~> 3.2'
pod 'JSONModel', '~> 1.0.1'
pod 'iOS-QR-Code-Encoder', '~> 0.0.1'
pod 'Objection', '1.6'
pod 'JSBadgeView'
pod 'UITableView+FDTemplateLayoutCell','1.3'
