// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "FscTeachNode.pb.h"
// @@protoc_insertion_point(imports)

@class PMenuPb;
@class PMenuPbBuilder;
@class PRecorderListPb;
@class PRecorderListPbBuilder;
@class PRecorderPb;
@class PRecorderPbBuilder;
@class PSessionPb;
@class PSessionPbBuilder;
@class PUserListPb;
@class PUserListPbBuilder;
@class PUserPb;
@class PUserPbBuilder;
@class TeachNodeContentPb;
@class TeachNodeContentPbBuilder;
@class TeachNodeDetailsPb;
@class TeachNodeDetailsPbBuilder;
@class TeachNodeListPb;
@class TeachNodeListPbBuilder;
@class TeachNodePb;
@class TeachNodePbBuilder;



@interface FscChatPublicRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PUserPb_id @"id"
#define PUserPb_code @"code"
#define PUserPb_isGroup @"isGroup"
#define PUserPb_groupCode @"groupCode"
#define PUserPb_name @"name"
#define PUserPb_introduce @"introduce"
#define PUserPb_inputMsg @"inputMsg"
#define PUserPb_inputMenu @"inputMenu"
#define PUserPb_dataStatus @"dataStatus"
#define PUserPb_modifiedDate @"modifiedDate"
#define PUserPb_menuPb @"menuPb"
@interface PUserPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasIsGroup_:1;
  BOOL hasInputMsg_:1;
  BOOL hasInputMenu_:1;
  BOOL hasId_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasDataStatus_:1;
  BOOL hasCode_:1;
  BOOL hasGroupCode_:1;
  BOOL hasName_:1;
  BOOL hasIntroduce_:1;
  BOOL isGroup_:1;
  BOOL inputMsg_:1;
  BOOL inputMenu_:1;
  SInt64 id;
  SInt64 modifiedDate;
  SInt32 dataStatus;
  NSString* code;
  NSString* groupCode;
  NSString* name;
  NSString* introduce;
  NSMutableArray * menuPbArray;
}
- (BOOL) hasId;
- (BOOL) hasCode;
- (BOOL) hasIsGroup;
- (BOOL) hasGroupCode;
- (BOOL) hasName;
- (BOOL) hasIntroduce;
- (BOOL) hasInputMsg;
- (BOOL) hasInputMenu;
- (BOOL) hasDataStatus;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* code;
- (BOOL) isGroup;
@property (readonly, strong) NSString* groupCode;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* introduce;
- (BOOL) inputMsg;
- (BOOL) inputMenu;
@property (readonly) SInt32 dataStatus;
@property (readonly) SInt64 modifiedDate;
@property (readonly, strong) NSArray * menuPb;
- (PMenuPb*)menuPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PUserPbBuilder*) builder;
+ (PUserPbBuilder*) builder;
+ (PUserPbBuilder*) builderWithPrototype:(PUserPb*) prototype;
- (PUserPbBuilder*) toBuilder;

+ (PUserPb*) parseFromData:(NSData*) data;
+ (PUserPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PUserPb*) parseFromInputStream:(NSInputStream*) input;
+ (PUserPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PUserPbBuilder : PBGeneratedMessageBuilder {
@private
  PUserPb* resultPuserPb;
}

- (PUserPb*) defaultInstance;

- (PUserPbBuilder*) clear;
- (PUserPbBuilder*) clone;

- (PUserPb*) build;
- (PUserPb*) buildPartial;

- (PUserPbBuilder*) mergeFrom:(PUserPb*) other;
- (PUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PUserPbBuilder*) setId:(SInt64) value;
- (PUserPbBuilder*) clearId;

- (BOOL) hasCode;
- (NSString*) code;
- (PUserPbBuilder*) setCode:(NSString*) value;
- (PUserPbBuilder*) clearCode;

- (BOOL) hasIsGroup;
- (BOOL) isGroup;
- (PUserPbBuilder*) setIsGroup:(BOOL) value;
- (PUserPbBuilder*) clearIsGroup;

- (BOOL) hasGroupCode;
- (NSString*) groupCode;
- (PUserPbBuilder*) setGroupCode:(NSString*) value;
- (PUserPbBuilder*) clearGroupCode;

- (BOOL) hasName;
- (NSString*) name;
- (PUserPbBuilder*) setName:(NSString*) value;
- (PUserPbBuilder*) clearName;

- (BOOL) hasIntroduce;
- (NSString*) introduce;
- (PUserPbBuilder*) setIntroduce:(NSString*) value;
- (PUserPbBuilder*) clearIntroduce;

- (BOOL) hasInputMsg;
- (BOOL) inputMsg;
- (PUserPbBuilder*) setInputMsg:(BOOL) value;
- (PUserPbBuilder*) clearInputMsg;

- (BOOL) hasInputMenu;
- (BOOL) inputMenu;
- (PUserPbBuilder*) setInputMenu:(BOOL) value;
- (PUserPbBuilder*) clearInputMenu;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (PUserPbBuilder*) setDataStatus:(SInt32) value;
- (PUserPbBuilder*) clearDataStatus;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (PUserPbBuilder*) setModifiedDate:(SInt64) value;
- (PUserPbBuilder*) clearModifiedDate;

- (NSMutableArray *)menuPb;
- (PMenuPb*)menuPbAtIndex:(NSUInteger)index;
- (PUserPbBuilder *)addMenuPb:(PMenuPb*)value;
- (PUserPbBuilder *)setMenuPbArray:(NSArray *)array;
- (PUserPbBuilder *)clearMenuPb;
@end

#define PUserListPb_userPb @"userPb"
@interface PUserListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * userPbArray;
}
@property (readonly, strong) NSArray * userPb;
- (PUserPb*)userPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PUserListPbBuilder*) builder;
+ (PUserListPbBuilder*) builder;
+ (PUserListPbBuilder*) builderWithPrototype:(PUserListPb*) prototype;
- (PUserListPbBuilder*) toBuilder;

+ (PUserListPb*) parseFromData:(NSData*) data;
+ (PUserListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PUserListPb*) parseFromInputStream:(NSInputStream*) input;
+ (PUserListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PUserListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PUserListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PUserListPbBuilder : PBGeneratedMessageBuilder {
@private
  PUserListPb* resultPuserListPb;
}

- (PUserListPb*) defaultInstance;

- (PUserListPbBuilder*) clear;
- (PUserListPbBuilder*) clone;

- (PUserListPb*) build;
- (PUserListPb*) buildPartial;

- (PUserListPbBuilder*) mergeFrom:(PUserListPb*) other;
- (PUserListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PUserListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)userPb;
- (PUserPb*)userPbAtIndex:(NSUInteger)index;
- (PUserListPbBuilder *)addUserPb:(PUserPb*)value;
- (PUserListPbBuilder *)setUserPbArray:(NSArray *)array;
- (PUserListPbBuilder *)clearUserPb;
@end

#define PMenuPb_id @"id"
#define PMenuPb_publicId @"publicId"
#define PMenuPb_itemName @"itemName"
#define PMenuPb_itemType @"itemType"
#define PMenuPb_itemMsg @"itemMsg"
#define PMenuPb_parentId @"parentId"
#define PMenuPb_isParent @"isParent"
#define PMenuPb_index @"index"
#define PMenuPb_dataStatus @"dataStatus"
#define PMenuPb_modifiedDate @"modifiedDate"
@interface PMenuPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasPublicId_:1;
  BOOL hasParentId_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasItemType_:1;
  BOOL hasIsParent_:1;
  BOOL hasIndex_:1;
  BOOL hasDataStatus_:1;
  BOOL hasItemName_:1;
  BOOL hasItemMsg_:1;
  SInt64 id;
  SInt64 publicId;
  SInt64 parentId;
  SInt64 modifiedDate;
  SInt32 itemType;
  SInt32 isParent;
  SInt32 index;
  SInt32 dataStatus;
  NSString* itemName;
  NSString* itemMsg;
}
- (BOOL) hasId;
- (BOOL) hasPublicId;
- (BOOL) hasItemName;
- (BOOL) hasItemType;
- (BOOL) hasItemMsg;
- (BOOL) hasParentId;
- (BOOL) hasIsParent;
- (BOOL) hasIndex;
- (BOOL) hasDataStatus;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 id;
@property (readonly) SInt64 publicId;
@property (readonly, strong) NSString* itemName;
@property (readonly) SInt32 itemType;
@property (readonly, strong) NSString* itemMsg;
@property (readonly) SInt64 parentId;
@property (readonly) SInt32 isParent;
@property (readonly) SInt32 index;
@property (readonly) SInt32 dataStatus;
@property (readonly) SInt64 modifiedDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PMenuPbBuilder*) builder;
+ (PMenuPbBuilder*) builder;
+ (PMenuPbBuilder*) builderWithPrototype:(PMenuPb*) prototype;
- (PMenuPbBuilder*) toBuilder;

+ (PMenuPb*) parseFromData:(NSData*) data;
+ (PMenuPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PMenuPb*) parseFromInputStream:(NSInputStream*) input;
+ (PMenuPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PMenuPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PMenuPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PMenuPbBuilder : PBGeneratedMessageBuilder {
@private
  PMenuPb* resultPmenuPb;
}

- (PMenuPb*) defaultInstance;

- (PMenuPbBuilder*) clear;
- (PMenuPbBuilder*) clone;

- (PMenuPb*) build;
- (PMenuPb*) buildPartial;

- (PMenuPbBuilder*) mergeFrom:(PMenuPb*) other;
- (PMenuPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PMenuPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PMenuPbBuilder*) setId:(SInt64) value;
- (PMenuPbBuilder*) clearId;

- (BOOL) hasPublicId;
- (SInt64) publicId;
- (PMenuPbBuilder*) setPublicId:(SInt64) value;
- (PMenuPbBuilder*) clearPublicId;

- (BOOL) hasItemName;
- (NSString*) itemName;
- (PMenuPbBuilder*) setItemName:(NSString*) value;
- (PMenuPbBuilder*) clearItemName;

- (BOOL) hasItemType;
- (SInt32) itemType;
- (PMenuPbBuilder*) setItemType:(SInt32) value;
- (PMenuPbBuilder*) clearItemType;

- (BOOL) hasItemMsg;
- (NSString*) itemMsg;
- (PMenuPbBuilder*) setItemMsg:(NSString*) value;
- (PMenuPbBuilder*) clearItemMsg;

- (BOOL) hasParentId;
- (SInt64) parentId;
- (PMenuPbBuilder*) setParentId:(SInt64) value;
- (PMenuPbBuilder*) clearParentId;

- (BOOL) hasIsParent;
- (SInt32) isParent;
- (PMenuPbBuilder*) setIsParent:(SInt32) value;
- (PMenuPbBuilder*) clearIsParent;

- (BOOL) hasIndex;
- (SInt32) index;
- (PMenuPbBuilder*) setIndex:(SInt32) value;
- (PMenuPbBuilder*) clearIndex;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (PMenuPbBuilder*) setDataStatus:(SInt32) value;
- (PMenuPbBuilder*) clearDataStatus;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (PMenuPbBuilder*) setModifiedDate:(SInt64) value;
- (PMenuPbBuilder*) clearModifiedDate;
@end

#define PSessionPb_id @"id"
#define PSessionPb_publicId @"publicId"
#define PSessionPb_publicCode @"publicCode"
#define PSessionPb_userId @"userId"
#define PSessionPb_createdDate @"createdDate"
#define PSessionPb_timestamp @"timestamp"
@interface PSessionPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasPublicId_:1;
  BOOL hasUserId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasPublicCode_:1;
  SInt64 id;
  SInt64 publicId;
  SInt64 userId;
  SInt64 createdDate;
  SInt64 timestamp;
  NSString* publicCode;
}
- (BOOL) hasId;
- (BOOL) hasPublicId;
- (BOOL) hasPublicCode;
- (BOOL) hasUserId;
- (BOOL) hasCreatedDate;
- (BOOL) hasTimestamp;
@property (readonly) SInt64 id;
@property (readonly) SInt64 publicId;
@property (readonly, strong) NSString* publicCode;
@property (readonly) SInt64 userId;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 timestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PSessionPbBuilder*) builder;
+ (PSessionPbBuilder*) builder;
+ (PSessionPbBuilder*) builderWithPrototype:(PSessionPb*) prototype;
- (PSessionPbBuilder*) toBuilder;

+ (PSessionPb*) parseFromData:(NSData*) data;
+ (PSessionPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PSessionPb*) parseFromInputStream:(NSInputStream*) input;
+ (PSessionPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PSessionPbBuilder : PBGeneratedMessageBuilder {
@private
  PSessionPb* resultPsessionPb;
}

- (PSessionPb*) defaultInstance;

- (PSessionPbBuilder*) clear;
- (PSessionPbBuilder*) clone;

- (PSessionPb*) build;
- (PSessionPb*) buildPartial;

- (PSessionPbBuilder*) mergeFrom:(PSessionPb*) other;
- (PSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PSessionPbBuilder*) setId:(SInt64) value;
- (PSessionPbBuilder*) clearId;

- (BOOL) hasPublicId;
- (SInt64) publicId;
- (PSessionPbBuilder*) setPublicId:(SInt64) value;
- (PSessionPbBuilder*) clearPublicId;

- (BOOL) hasPublicCode;
- (NSString*) publicCode;
- (PSessionPbBuilder*) setPublicCode:(NSString*) value;
- (PSessionPbBuilder*) clearPublicCode;

- (BOOL) hasUserId;
- (SInt64) userId;
- (PSessionPbBuilder*) setUserId:(SInt64) value;
- (PSessionPbBuilder*) clearUserId;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (PSessionPbBuilder*) setCreatedDate:(SInt64) value;
- (PSessionPbBuilder*) clearCreatedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (PSessionPbBuilder*) setTimestamp:(SInt64) value;
- (PSessionPbBuilder*) clearTimestamp;
@end

#define PRecorderListPb_recorderPb @"recorderPb"
@interface PRecorderListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * recorderPbArray;
}
@property (readonly, strong) NSArray * recorderPb;
- (PRecorderPb*)recorderPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PRecorderListPbBuilder*) builder;
+ (PRecorderListPbBuilder*) builder;
+ (PRecorderListPbBuilder*) builderWithPrototype:(PRecorderListPb*) prototype;
- (PRecorderListPbBuilder*) toBuilder;

+ (PRecorderListPb*) parseFromData:(NSData*) data;
+ (PRecorderListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PRecorderListPb*) parseFromInputStream:(NSInputStream*) input;
+ (PRecorderListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PRecorderListPbBuilder : PBGeneratedMessageBuilder {
@private
  PRecorderListPb* resultPrecorderListPb;
}

- (PRecorderListPb*) defaultInstance;

- (PRecorderListPbBuilder*) clear;
- (PRecorderListPbBuilder*) clone;

- (PRecorderListPb*) build;
- (PRecorderListPb*) buildPartial;

- (PRecorderListPbBuilder*) mergeFrom:(PRecorderListPb*) other;
- (PRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)recorderPb;
- (PRecorderPb*)recorderPbAtIndex:(NSUInteger)index;
- (PRecorderListPbBuilder *)addRecorderPb:(PRecorderPb*)value;
- (PRecorderListPbBuilder *)setRecorderPbArray:(NSArray *)array;
- (PRecorderListPbBuilder *)clearRecorderPb;
@end

#define PRecorderPb_id @"id"
#define PRecorderPb_sessionId @"sessionId"
#define PRecorderPb_fromType @"fromType"
#define PRecorderPb_fromUserId @"fromUserId"
#define PRecorderPb_toUserId @"toUserId"
#define PRecorderPb_type @"type"
#define PRecorderPb_message @"message"
#define PRecorderPb_timestamp @"timestamp"
#define PRecorderPb_createdDate @"createdDate"
#define PRecorderPb_uuid @"uuid"
#define PRecorderPb_file @"file"
@interface PRecorderPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSessionId_:1;
  BOOL hasFromUserId_:1;
  BOOL hasToUserId_:1;
  BOOL hasTimestamp_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasFromType_:1;
  BOOL hasType_:1;
  BOOL hasMessage_:1;
  BOOL hasUuid_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 sessionId;
  SInt64 fromUserId;
  SInt64 toUserId;
  SInt64 timestamp;
  SInt64 createdDate;
  SInt32 fromType;
  SInt32 type;
  NSString* message;
  NSString* uuid;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasSessionId;
- (BOOL) hasFromType;
- (BOOL) hasFromUserId;
- (BOOL) hasToUserId;
- (BOOL) hasType;
- (BOOL) hasMessage;
- (BOOL) hasTimestamp;
- (BOOL) hasCreatedDate;
- (BOOL) hasUuid;
- (BOOL) hasFile;
@property (readonly) SInt64 id;
@property (readonly) SInt64 sessionId;
@property (readonly) SInt32 fromType;
@property (readonly) SInt64 fromUserId;
@property (readonly) SInt64 toUserId;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* message;
@property (readonly) SInt64 timestamp;
@property (readonly) SInt64 createdDate;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSData* file;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PRecorderPbBuilder*) builder;
+ (PRecorderPbBuilder*) builder;
+ (PRecorderPbBuilder*) builderWithPrototype:(PRecorderPb*) prototype;
- (PRecorderPbBuilder*) toBuilder;

+ (PRecorderPb*) parseFromData:(NSData*) data;
+ (PRecorderPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PRecorderPb*) parseFromInputStream:(NSInputStream*) input;
+ (PRecorderPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PRecorderPbBuilder : PBGeneratedMessageBuilder {
@private
  PRecorderPb* resultPrecorderPb;
}

- (PRecorderPb*) defaultInstance;

- (PRecorderPbBuilder*) clear;
- (PRecorderPbBuilder*) clone;

- (PRecorderPb*) build;
- (PRecorderPb*) buildPartial;

- (PRecorderPbBuilder*) mergeFrom:(PRecorderPb*) other;
- (PRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (PRecorderPbBuilder*) setId:(SInt64) value;
- (PRecorderPbBuilder*) clearId;

- (BOOL) hasSessionId;
- (SInt64) sessionId;
- (PRecorderPbBuilder*) setSessionId:(SInt64) value;
- (PRecorderPbBuilder*) clearSessionId;

- (BOOL) hasFromType;
- (SInt32) fromType;
- (PRecorderPbBuilder*) setFromType:(SInt32) value;
- (PRecorderPbBuilder*) clearFromType;

- (BOOL) hasFromUserId;
- (SInt64) fromUserId;
- (PRecorderPbBuilder*) setFromUserId:(SInt64) value;
- (PRecorderPbBuilder*) clearFromUserId;

- (BOOL) hasToUserId;
- (SInt64) toUserId;
- (PRecorderPbBuilder*) setToUserId:(SInt64) value;
- (PRecorderPbBuilder*) clearToUserId;

- (BOOL) hasType;
- (SInt32) type;
- (PRecorderPbBuilder*) setType:(SInt32) value;
- (PRecorderPbBuilder*) clearType;

- (BOOL) hasMessage;
- (NSString*) message;
- (PRecorderPbBuilder*) setMessage:(NSString*) value;
- (PRecorderPbBuilder*) clearMessage;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (PRecorderPbBuilder*) setTimestamp:(SInt64) value;
- (PRecorderPbBuilder*) clearTimestamp;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (PRecorderPbBuilder*) setCreatedDate:(SInt64) value;
- (PRecorderPbBuilder*) clearCreatedDate;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (PRecorderPbBuilder*) setUuid:(NSString*) value;
- (PRecorderPbBuilder*) clearUuid;

- (BOOL) hasFile;
- (NSData*) file;
- (PRecorderPbBuilder*) setFile:(NSData*) value;
- (PRecorderPbBuilder*) clearFile;
@end


// @@protoc_insertion_point(global_scope)
