// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class DiskFileListPb;
@class DiskFileListPbBuilder;
@class DiskFilePb;
@class DiskFilePbBuilder;



@interface FscDiskFileRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define DiskFileListPb_diskFile @"diskFile"
@interface DiskFileListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * diskFileArray;
}
@property (readonly, strong) NSArray * diskFile;
- (DiskFilePb*)diskFileAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DiskFileListPbBuilder*) builder;
+ (DiskFileListPbBuilder*) builder;
+ (DiskFileListPbBuilder*) builderWithPrototype:(DiskFileListPb*) prototype;
- (DiskFileListPbBuilder*) toBuilder;

+ (DiskFileListPb*) parseFromData:(NSData*) data;
+ (DiskFileListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DiskFileListPb*) parseFromInputStream:(NSInputStream*) input;
+ (DiskFileListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DiskFileListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DiskFileListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DiskFileListPbBuilder : PBGeneratedMessageBuilder {
@private
  DiskFileListPb* resultDiskFileListPb;
}

- (DiskFileListPb*) defaultInstance;

- (DiskFileListPbBuilder*) clear;
- (DiskFileListPbBuilder*) clone;

- (DiskFileListPb*) build;
- (DiskFileListPb*) buildPartial;

- (DiskFileListPbBuilder*) mergeFrom:(DiskFileListPb*) other;
- (DiskFileListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DiskFileListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)diskFile;
- (DiskFilePb*)diskFileAtIndex:(NSUInteger)index;
- (DiskFileListPbBuilder *)addDiskFile:(DiskFilePb*)value;
- (DiskFileListPbBuilder *)setDiskFileArray:(NSArray *)array;
- (DiskFileListPbBuilder *)clearDiskFile;
@end

#define DiskFilePb_id @"id"
#define DiskFilePb_userId @"userId"
#define DiskFilePb_isParent @"isParent"
#define DiskFilePb_parentId @"parentId"
#define DiskFilePb_fileId @"fileId"
#define DiskFilePb_fileName @"fileName"
#define DiskFilePb_fileType @"fileType"
#define DiskFilePb_fileSize @"fileSize"
#define DiskFilePb_filePath @"filePath"
#define DiskFilePb_dataStatus @"dataStatus"
#define DiskFilePb_modifiedDate @"modifiedDate"
#define DiskFilePb_file @"file"
#define DiskFilePb_md5 @"md5"
@interface DiskFilePb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasUserId_:1;
  BOOL hasParentId_:1;
  BOOL hasFileId_:1;
  BOOL hasFileSize_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasIsParent_:1;
  BOOL hasDataStatus_:1;
  BOOL hasFileName_:1;
  BOOL hasFileType_:1;
  BOOL hasFilePath_:1;
  BOOL hasMd5_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 userId;
  SInt64 parentId;
  SInt64 fileId;
  SInt64 fileSize;
  SInt64 modifiedDate;
  SInt32 isParent;
  SInt32 dataStatus;
  NSString* fileName;
  NSString* fileType;
  NSString* filePath;
  NSString* md5;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasUserId;
- (BOOL) hasIsParent;
- (BOOL) hasParentId;
- (BOOL) hasFileId;
- (BOOL) hasFileName;
- (BOOL) hasFileType;
- (BOOL) hasFileSize;
- (BOOL) hasFilePath;
- (BOOL) hasDataStatus;
- (BOOL) hasModifiedDate;
- (BOOL) hasFile;
- (BOOL) hasMd5;
@property (readonly) SInt64 id;
@property (readonly) SInt64 userId;
@property (readonly) SInt32 isParent;
@property (readonly) SInt64 parentId;
@property (readonly) SInt64 fileId;
@property (readonly, strong) NSString* fileName;
@property (readonly, strong) NSString* fileType;
@property (readonly) SInt64 fileSize;
@property (readonly, strong) NSString* filePath;
@property (readonly) SInt32 dataStatus;
@property (readonly) SInt64 modifiedDate;
@property (readonly, strong) NSData* file;
@property (readonly, strong) NSString* md5;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (DiskFilePbBuilder*) builder;
+ (DiskFilePbBuilder*) builder;
+ (DiskFilePbBuilder*) builderWithPrototype:(DiskFilePb*) prototype;
- (DiskFilePbBuilder*) toBuilder;

+ (DiskFilePb*) parseFromData:(NSData*) data;
+ (DiskFilePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DiskFilePb*) parseFromInputStream:(NSInputStream*) input;
+ (DiskFilePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (DiskFilePb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (DiskFilePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface DiskFilePbBuilder : PBGeneratedMessageBuilder {
@private
  DiskFilePb* resultDiskFilePb;
}

- (DiskFilePb*) defaultInstance;

- (DiskFilePbBuilder*) clear;
- (DiskFilePbBuilder*) clone;

- (DiskFilePb*) build;
- (DiskFilePb*) buildPartial;

- (DiskFilePbBuilder*) mergeFrom:(DiskFilePb*) other;
- (DiskFilePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (DiskFilePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (DiskFilePbBuilder*) setId:(SInt64) value;
- (DiskFilePbBuilder*) clearId;

- (BOOL) hasUserId;
- (SInt64) userId;
- (DiskFilePbBuilder*) setUserId:(SInt64) value;
- (DiskFilePbBuilder*) clearUserId;

- (BOOL) hasIsParent;
- (SInt32) isParent;
- (DiskFilePbBuilder*) setIsParent:(SInt32) value;
- (DiskFilePbBuilder*) clearIsParent;

- (BOOL) hasParentId;
- (SInt64) parentId;
- (DiskFilePbBuilder*) setParentId:(SInt64) value;
- (DiskFilePbBuilder*) clearParentId;

- (BOOL) hasFileId;
- (SInt64) fileId;
- (DiskFilePbBuilder*) setFileId:(SInt64) value;
- (DiskFilePbBuilder*) clearFileId;

- (BOOL) hasFileName;
- (NSString*) fileName;
- (DiskFilePbBuilder*) setFileName:(NSString*) value;
- (DiskFilePbBuilder*) clearFileName;

- (BOOL) hasFileType;
- (NSString*) fileType;
- (DiskFilePbBuilder*) setFileType:(NSString*) value;
- (DiskFilePbBuilder*) clearFileType;

- (BOOL) hasFileSize;
- (SInt64) fileSize;
- (DiskFilePbBuilder*) setFileSize:(SInt64) value;
- (DiskFilePbBuilder*) clearFileSize;

- (BOOL) hasFilePath;
- (NSString*) filePath;
- (DiskFilePbBuilder*) setFilePath:(NSString*) value;
- (DiskFilePbBuilder*) clearFilePath;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (DiskFilePbBuilder*) setDataStatus:(SInt32) value;
- (DiskFilePbBuilder*) clearDataStatus;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (DiskFilePbBuilder*) setModifiedDate:(SInt64) value;
- (DiskFilePbBuilder*) clearModifiedDate;

- (BOOL) hasFile;
- (NSData*) file;
- (DiskFilePbBuilder*) setFile:(NSData*) value;
- (DiskFilePbBuilder*) clearFile;

- (BOOL) hasMd5;
- (NSString*) md5;
- (DiskFilePbBuilder*) setMd5:(NSString*) value;
- (DiskFilePbBuilder*) clearMd5;
@end


// @@protoc_insertion_point(global_scope)
