// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FscErrorPbList;
@class FscErrorPbListBuilder;
@class FscErrorRecorderPb;
@class FscErrorRecorderPbBuilder;



@interface FscErrorRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FscErrorPbList_fscErrorPb @"fscErrorPb"
@interface FscErrorPbList : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * fscErrorPbArray;
}
@property (readonly, strong) NSArray * fscErrorPb;
- (FscErrorRecorderPb*)fscErrorPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscErrorPbListBuilder*) builder;
+ (FscErrorPbListBuilder*) builder;
+ (FscErrorPbListBuilder*) builderWithPrototype:(FscErrorPbList*) prototype;
- (FscErrorPbListBuilder*) toBuilder;

+ (FscErrorPbList*) parseFromData:(NSData*) data;
+ (FscErrorPbList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscErrorPbList*) parseFromInputStream:(NSInputStream*) input;
+ (FscErrorPbList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscErrorPbList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscErrorPbList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscErrorPbListBuilder : PBGeneratedMessageBuilder {
@private
  FscErrorPbList* resultFscErrorPbList;
}

- (FscErrorPbList*) defaultInstance;

- (FscErrorPbListBuilder*) clear;
- (FscErrorPbListBuilder*) clone;

- (FscErrorPbList*) build;
- (FscErrorPbList*) buildPartial;

- (FscErrorPbListBuilder*) mergeFrom:(FscErrorPbList*) other;
- (FscErrorPbListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscErrorPbListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)fscErrorPb;
- (FscErrorRecorderPb*)fscErrorPbAtIndex:(NSUInteger)index;
- (FscErrorPbListBuilder *)addFscErrorPb:(FscErrorRecorderPb*)value;
- (FscErrorPbListBuilder *)setFscErrorPbArray:(NSArray *)array;
- (FscErrorPbListBuilder *)clearFscErrorPb;
@end

#define FscErrorRecorderPb_id @"id"
#define FscErrorRecorderPb_userId @"userId"
#define FscErrorRecorderPb_deviceId @"deviceId"
#define FscErrorRecorderPb_subscriberId @"subscriberId"
#define FscErrorRecorderPb_model @"model"
#define FscErrorRecorderPb_brand @"brand"
#define FscErrorRecorderPb_number @"number"
#define FscErrorRecorderPb_appVersion @"appVersion"
#define FscErrorRecorderPb_osVersion @"osVersion"
#define FscErrorRecorderPb_errorMsg @"errorMsg"
#define FscErrorRecorderPb_createdDate @"createdDate"
@interface FscErrorRecorderPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasUserId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasDeviceId_:1;
  BOOL hasSubscriberId_:1;
  BOOL hasModel_:1;
  BOOL hasBrand_:1;
  BOOL hasNumber_:1;
  BOOL hasAppVersion_:1;
  BOOL hasOsVersion_:1;
  BOOL hasErrorMsg_:1;
  SInt64 id;
  SInt64 userId;
  SInt64 createdDate;
  NSString* deviceId;
  NSString* subscriberId;
  NSString* model;
  NSString* brand;
  NSString* number;
  NSString* appVersion;
  NSString* osVersion;
  NSString* errorMsg;
}
- (BOOL) hasId;
- (BOOL) hasUserId;
- (BOOL) hasDeviceId;
- (BOOL) hasSubscriberId;
- (BOOL) hasModel;
- (BOOL) hasBrand;
- (BOOL) hasNumber;
- (BOOL) hasAppVersion;
- (BOOL) hasOsVersion;
- (BOOL) hasErrorMsg;
- (BOOL) hasCreatedDate;
@property (readonly) SInt64 id;
@property (readonly) SInt64 userId;
@property (readonly, strong) NSString* deviceId;
@property (readonly, strong) NSString* subscriberId;
@property (readonly, strong) NSString* model;
@property (readonly, strong) NSString* brand;
@property (readonly, strong) NSString* number;
@property (readonly, strong) NSString* appVersion;
@property (readonly, strong) NSString* osVersion;
@property (readonly, strong) NSString* errorMsg;
@property (readonly) SInt64 createdDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscErrorRecorderPbBuilder*) builder;
+ (FscErrorRecorderPbBuilder*) builder;
+ (FscErrorRecorderPbBuilder*) builderWithPrototype:(FscErrorRecorderPb*) prototype;
- (FscErrorRecorderPbBuilder*) toBuilder;

+ (FscErrorRecorderPb*) parseFromData:(NSData*) data;
+ (FscErrorRecorderPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscErrorRecorderPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscErrorRecorderPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscErrorRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscErrorRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscErrorRecorderPbBuilder : PBGeneratedMessageBuilder {
@private
  FscErrorRecorderPb* resultFscErrorRecorderPb;
}

- (FscErrorRecorderPb*) defaultInstance;

- (FscErrorRecorderPbBuilder*) clear;
- (FscErrorRecorderPbBuilder*) clone;

- (FscErrorRecorderPb*) build;
- (FscErrorRecorderPb*) buildPartial;

- (FscErrorRecorderPbBuilder*) mergeFrom:(FscErrorRecorderPb*) other;
- (FscErrorRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscErrorRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscErrorRecorderPbBuilder*) setId:(SInt64) value;
- (FscErrorRecorderPbBuilder*) clearId;

- (BOOL) hasUserId;
- (SInt64) userId;
- (FscErrorRecorderPbBuilder*) setUserId:(SInt64) value;
- (FscErrorRecorderPbBuilder*) clearUserId;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (FscErrorRecorderPbBuilder*) setDeviceId:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearDeviceId;

- (BOOL) hasSubscriberId;
- (NSString*) subscriberId;
- (FscErrorRecorderPbBuilder*) setSubscriberId:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearSubscriberId;

- (BOOL) hasModel;
- (NSString*) model;
- (FscErrorRecorderPbBuilder*) setModel:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearModel;

- (BOOL) hasBrand;
- (NSString*) brand;
- (FscErrorRecorderPbBuilder*) setBrand:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearBrand;

- (BOOL) hasNumber;
- (NSString*) number;
- (FscErrorRecorderPbBuilder*) setNumber:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearNumber;

- (BOOL) hasAppVersion;
- (NSString*) appVersion;
- (FscErrorRecorderPbBuilder*) setAppVersion:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearAppVersion;

- (BOOL) hasOsVersion;
- (NSString*) osVersion;
- (FscErrorRecorderPbBuilder*) setOsVersion:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearOsVersion;

- (BOOL) hasErrorMsg;
- (NSString*) errorMsg;
- (FscErrorRecorderPbBuilder*) setErrorMsg:(NSString*) value;
- (FscErrorRecorderPbBuilder*) clearErrorMsg;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (FscErrorRecorderPbBuilder*) setCreatedDate:(SInt64) value;
- (FscErrorRecorderPbBuilder*) clearCreatedDate;
@end


// @@protoc_insertion_point(global_scope)
