// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import "FscSns.pb.h"
// @@protoc_insertion_point(imports)

@implementation FscSnsRoot
static PBExtensionRegistry* extensionRegistry = nil;
+ (PBExtensionRegistry*) extensionRegistry {
  return extensionRegistry;
}

+ (void) initialize {
  if (self == [FscSnsRoot class]) {
    PBMutableExtensionRegistry* registry = [PBMutableExtensionRegistry registry];
    [self registerAllExtensions:registry];
    extensionRegistry = registry;
  }
}
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry {
}
@end

@interface FscSnsMsgReqPb ()
@property SInt64 timestamp;
@end

@implementation FscSnsMsgReqPb

- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) _value_ {
  hasTimestamp_ = !!_value_;
}
@synthesize timestamp;
- (instancetype) init {
  if ((self = [super init])) {
    self.timestamp = 0L;
  }
  return self;
}
static FscSnsMsgReqPb* defaultFscSnsMsgReqPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsMsgReqPb class]) {
    defaultFscSnsMsgReqPbInstance = [[FscSnsMsgReqPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsMsgReqPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsMsgReqPbInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasTimestamp) {
    [output writeInt64:1 value:self.timestamp];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasTimestamp) {
    size_ += computeInt64Size(1, self.timestamp);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsMsgReqPb*) parseFromData:(NSData*) data {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromData:data] build];
}
+ (FscSnsMsgReqPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgReqPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsMsgReqPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgReqPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsMsgReqPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgReqPb*)[[[FscSnsMsgReqPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgReqPbBuilder*) builder {
  return [[FscSnsMsgReqPbBuilder alloc] init];
}
+ (FscSnsMsgReqPbBuilder*) builderWithPrototype:(FscSnsMsgReqPb*) prototype {
  return [[FscSnsMsgReqPb builder] mergeFrom:prototype];
}
- (FscSnsMsgReqPbBuilder*) builder {
  return [FscSnsMsgReqPb builder];
}
- (FscSnsMsgReqPbBuilder*) toBuilder {
  return [FscSnsMsgReqPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasTimestamp) {
    [output appendFormat:@"%@%@: %@\n", indent, @"timestamp", [NSNumber numberWithLongLong:self.timestamp]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasTimestamp) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.timestamp] forKey: @"timestamp"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsMsgReqPb class]]) {
    return NO;
  }
  FscSnsMsgReqPb *otherMessage = other;
  return
      self.hasTimestamp == otherMessage.hasTimestamp &&
      (!self.hasTimestamp || self.timestamp == otherMessage.timestamp) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasTimestamp) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.timestamp] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsMsgReqPbBuilder()
@property (strong) FscSnsMsgReqPb* resultFscSnsMsgReqPb;
@end

@implementation FscSnsMsgReqPbBuilder
@synthesize resultFscSnsMsgReqPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsMsgReqPb = [[FscSnsMsgReqPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsMsgReqPb;
}
- (FscSnsMsgReqPbBuilder*) clear {
  self.resultFscSnsMsgReqPb = [[FscSnsMsgReqPb alloc] init];
  return self;
}
- (FscSnsMsgReqPbBuilder*) clone {
  return [FscSnsMsgReqPb builderWithPrototype:resultFscSnsMsgReqPb];
}
- (FscSnsMsgReqPb*) defaultInstance {
  return [FscSnsMsgReqPb defaultInstance];
}
- (FscSnsMsgReqPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsMsgReqPb*) buildPartial {
  FscSnsMsgReqPb* returnMe = resultFscSnsMsgReqPb;
  self.resultFscSnsMsgReqPb = nil;
  return returnMe;
}
- (FscSnsMsgReqPbBuilder*) mergeFrom:(FscSnsMsgReqPb*) other {
  if (other == [FscSnsMsgReqPb defaultInstance]) {
    return self;
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsMsgReqPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsMsgReqPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setTimestamp:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasTimestamp {
  return resultFscSnsMsgReqPb.hasTimestamp;
}
- (SInt64) timestamp {
  return resultFscSnsMsgReqPb.timestamp;
}
- (FscSnsMsgReqPbBuilder*) setTimestamp:(SInt64) value {
  resultFscSnsMsgReqPb.hasTimestamp = YES;
  resultFscSnsMsgReqPb.timestamp = value;
  return self;
}
- (FscSnsMsgReqPbBuilder*) clearTimestamp {
  resultFscSnsMsgReqPb.hasTimestamp = NO;
  resultFscSnsMsgReqPb.timestamp = 0L;
  return self;
}
@end

@interface FscSnsMsgRespPb ()
@property (strong) NSMutableArray * fscSnsMsgPbArray;
@end

@implementation FscSnsMsgRespPb

@synthesize fscSnsMsgPbArray;
@dynamic fscSnsMsgPb;
- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static FscSnsMsgRespPb* defaultFscSnsMsgRespPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsMsgRespPb class]) {
    defaultFscSnsMsgRespPbInstance = [[FscSnsMsgRespPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsMsgRespPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsMsgRespPbInstance;
}
- (NSArray *)fscSnsMsgPb {
  return fscSnsMsgPbArray;
}
- (FscSnsMsgPb*)fscSnsMsgPbAtIndex:(NSUInteger)index {
  return [fscSnsMsgPbArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:1 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(1, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsMsgRespPb*) parseFromData:(NSData*) data {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromData:data] build];
}
+ (FscSnsMsgRespPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgRespPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsMsgRespPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgRespPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsMsgRespPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgRespPb*)[[[FscSnsMsgRespPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgRespPbBuilder*) builder {
  return [[FscSnsMsgRespPbBuilder alloc] init];
}
+ (FscSnsMsgRespPbBuilder*) builderWithPrototype:(FscSnsMsgRespPb*) prototype {
  return [[FscSnsMsgRespPb builder] mergeFrom:prototype];
}
- (FscSnsMsgRespPbBuilder*) builder {
  return [FscSnsMsgRespPb builder];
}
- (FscSnsMsgRespPbBuilder*) toBuilder {
  return [FscSnsMsgRespPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"fscSnsMsgPb"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  for (FscSnsMsgPb* element in self.fscSnsMsgPbArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"fscSnsMsgPb"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsMsgRespPb class]]) {
    return NO;
  }
  FscSnsMsgRespPb *otherMessage = other;
  return
      [self.fscSnsMsgPbArray isEqualToArray:otherMessage.fscSnsMsgPbArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsMsgRespPbBuilder()
@property (strong) FscSnsMsgRespPb* resultFscSnsMsgRespPb;
@end

@implementation FscSnsMsgRespPbBuilder
@synthesize resultFscSnsMsgRespPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsMsgRespPb = [[FscSnsMsgRespPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsMsgRespPb;
}
- (FscSnsMsgRespPbBuilder*) clear {
  self.resultFscSnsMsgRespPb = [[FscSnsMsgRespPb alloc] init];
  return self;
}
- (FscSnsMsgRespPbBuilder*) clone {
  return [FscSnsMsgRespPb builderWithPrototype:resultFscSnsMsgRespPb];
}
- (FscSnsMsgRespPb*) defaultInstance {
  return [FscSnsMsgRespPb defaultInstance];
}
- (FscSnsMsgRespPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsMsgRespPb*) buildPartial {
  FscSnsMsgRespPb* returnMe = resultFscSnsMsgRespPb;
  self.resultFscSnsMsgRespPb = nil;
  return returnMe;
}
- (FscSnsMsgRespPbBuilder*) mergeFrom:(FscSnsMsgRespPb*) other {
  if (other == [FscSnsMsgRespPb defaultInstance]) {
    return self;
  }
  if (other.fscSnsMsgPbArray.count > 0) {
    if (resultFscSnsMsgRespPb.fscSnsMsgPbArray == nil) {
      resultFscSnsMsgRespPb.fscSnsMsgPbArray = [[NSMutableArray alloc] initWithArray:other.fscSnsMsgPbArray];
    } else {
      [resultFscSnsMsgRespPb.fscSnsMsgPbArray addObjectsFromArray:other.fscSnsMsgPbArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsMsgRespPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsMsgRespPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        FscSnsMsgPbBuilder* subBuilder = [FscSnsMsgPb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFscSnsMsgPb:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray *)fscSnsMsgPb {
  return resultFscSnsMsgRespPb.fscSnsMsgPbArray;
}
- (FscSnsMsgPb*)fscSnsMsgPbAtIndex:(NSUInteger)index {
  return [resultFscSnsMsgRespPb fscSnsMsgPbAtIndex:index];
}
- (FscSnsMsgRespPbBuilder *)addFscSnsMsgPb:(FscSnsMsgPb*)value {
  if (resultFscSnsMsgRespPb.fscSnsMsgPbArray == nil) {
    resultFscSnsMsgRespPb.fscSnsMsgPbArray = [[NSMutableArray alloc]init];
  }
  [resultFscSnsMsgRespPb.fscSnsMsgPbArray addObject:value];
  return self;
}
- (FscSnsMsgRespPbBuilder *)setFscSnsMsgPbArray:(NSArray *)array {
  resultFscSnsMsgRespPb.fscSnsMsgPbArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FscSnsMsgRespPbBuilder *)clearFscSnsMsgPb {
  resultFscSnsMsgRespPb.fscSnsMsgPbArray = nil;
  return self;
}
@end

@interface FscSnsMsgImgPb ()
@property (strong) NSData* imgByte;
@end

@implementation FscSnsMsgImgPb

- (BOOL) hasImgByte {
  return !!hasImgByte_;
}
- (void) setHasImgByte:(BOOL) _value_ {
  hasImgByte_ = !!_value_;
}
@synthesize imgByte;
- (instancetype) init {
  if ((self = [super init])) {
    self.imgByte = [NSData data];
  }
  return self;
}
static FscSnsMsgImgPb* defaultFscSnsMsgImgPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsMsgImgPb class]) {
    defaultFscSnsMsgImgPbInstance = [[FscSnsMsgImgPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsMsgImgPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsMsgImgPbInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasImgByte) {
    [output writeData:1 value:self.imgByte];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasImgByte) {
    size_ += computeDataSize(1, self.imgByte);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsMsgImgPb*) parseFromData:(NSData*) data {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromData:data] build];
}
+ (FscSnsMsgImgPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgImgPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsMsgImgPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgImgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsMsgImgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgImgPb*)[[[FscSnsMsgImgPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgImgPbBuilder*) builder {
  return [[FscSnsMsgImgPbBuilder alloc] init];
}
+ (FscSnsMsgImgPbBuilder*) builderWithPrototype:(FscSnsMsgImgPb*) prototype {
  return [[FscSnsMsgImgPb builder] mergeFrom:prototype];
}
- (FscSnsMsgImgPbBuilder*) builder {
  return [FscSnsMsgImgPb builder];
}
- (FscSnsMsgImgPbBuilder*) toBuilder {
  return [FscSnsMsgImgPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasImgByte) {
    [output appendFormat:@"%@%@: %@\n", indent, @"imgByte", self.imgByte];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasImgByte) {
    [dictionary setObject: self.imgByte forKey: @"imgByte"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsMsgImgPb class]]) {
    return NO;
  }
  FscSnsMsgImgPb *otherMessage = other;
  return
      self.hasImgByte == otherMessage.hasImgByte &&
      (!self.hasImgByte || [self.imgByte isEqual:otherMessage.imgByte]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasImgByte) {
    hashCode = hashCode * 31 + [self.imgByte hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsMsgImgPbBuilder()
@property (strong) FscSnsMsgImgPb* resultFscSnsMsgImgPb;
@end

@implementation FscSnsMsgImgPbBuilder
@synthesize resultFscSnsMsgImgPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsMsgImgPb = [[FscSnsMsgImgPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsMsgImgPb;
}
- (FscSnsMsgImgPbBuilder*) clear {
  self.resultFscSnsMsgImgPb = [[FscSnsMsgImgPb alloc] init];
  return self;
}
- (FscSnsMsgImgPbBuilder*) clone {
  return [FscSnsMsgImgPb builderWithPrototype:resultFscSnsMsgImgPb];
}
- (FscSnsMsgImgPb*) defaultInstance {
  return [FscSnsMsgImgPb defaultInstance];
}
- (FscSnsMsgImgPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsMsgImgPb*) buildPartial {
  FscSnsMsgImgPb* returnMe = resultFscSnsMsgImgPb;
  self.resultFscSnsMsgImgPb = nil;
  return returnMe;
}
- (FscSnsMsgImgPbBuilder*) mergeFrom:(FscSnsMsgImgPb*) other {
  if (other == [FscSnsMsgImgPb defaultInstance]) {
    return self;
  }
  if (other.hasImgByte) {
    [self setImgByte:other.imgByte];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsMsgImgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsMsgImgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        [self setImgByte:[input readData]];
        break;
      }
    }
  }
}
- (BOOL) hasImgByte {
  return resultFscSnsMsgImgPb.hasImgByte;
}
- (NSData*) imgByte {
  return resultFscSnsMsgImgPb.imgByte;
}
- (FscSnsMsgImgPbBuilder*) setImgByte:(NSData*) value {
  resultFscSnsMsgImgPb.hasImgByte = YES;
  resultFscSnsMsgImgPb.imgByte = value;
  return self;
}
- (FscSnsMsgImgPbBuilder*) clearImgByte {
  resultFscSnsMsgImgPb.hasImgByte = NO;
  resultFscSnsMsgImgPb.imgByte = [NSData data];
  return self;
}
@end

@interface FscSnsSinaMsgListPb ()
@property (strong) NSMutableArray * fscSnsMsgPbArray;
@end

@implementation FscSnsSinaMsgListPb

@synthesize fscSnsMsgPbArray;
@dynamic fscSnsMsgPb;
- (instancetype) init {
  if ((self = [super init])) {
  }
  return self;
}
static FscSnsSinaMsgListPb* defaultFscSnsSinaMsgListPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsSinaMsgListPb class]) {
    defaultFscSnsSinaMsgListPbInstance = [[FscSnsSinaMsgListPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsSinaMsgListPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsSinaMsgListPbInstance;
}
- (NSArray *)fscSnsMsgPb {
  return fscSnsMsgPbArray;
}
- (FscSnsMsgPb*)fscSnsMsgPbAtIndex:(NSUInteger)index {
  return [fscSnsMsgPbArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:1 value:element];
  }];
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(1, element);
  }];
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsSinaMsgListPb*) parseFromData:(NSData*) data {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromData:data] build];
}
+ (FscSnsSinaMsgListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsSinaMsgListPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsSinaMsgListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsSinaMsgListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsSinaMsgListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsSinaMsgListPb*)[[[FscSnsSinaMsgListPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsSinaMsgListPbBuilder*) builder {
  return [[FscSnsSinaMsgListPbBuilder alloc] init];
}
+ (FscSnsSinaMsgListPbBuilder*) builderWithPrototype:(FscSnsSinaMsgListPb*) prototype {
  return [[FscSnsSinaMsgListPb builder] mergeFrom:prototype];
}
- (FscSnsSinaMsgListPbBuilder*) builder {
  return [FscSnsSinaMsgListPb builder];
}
- (FscSnsSinaMsgListPbBuilder*) toBuilder {
  return [FscSnsSinaMsgListPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"fscSnsMsgPb"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  for (FscSnsMsgPb* element in self.fscSnsMsgPbArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"fscSnsMsgPb"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsSinaMsgListPb class]]) {
    return NO;
  }
  FscSnsSinaMsgListPb *otherMessage = other;
  return
      [self.fscSnsMsgPbArray isEqualToArray:otherMessage.fscSnsMsgPbArray] &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  [self.fscSnsMsgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgPb *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsSinaMsgListPbBuilder()
@property (strong) FscSnsSinaMsgListPb* resultFscSnsSinaMsgListPb;
@end

@implementation FscSnsSinaMsgListPbBuilder
@synthesize resultFscSnsSinaMsgListPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsSinaMsgListPb = [[FscSnsSinaMsgListPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsSinaMsgListPb;
}
- (FscSnsSinaMsgListPbBuilder*) clear {
  self.resultFscSnsSinaMsgListPb = [[FscSnsSinaMsgListPb alloc] init];
  return self;
}
- (FscSnsSinaMsgListPbBuilder*) clone {
  return [FscSnsSinaMsgListPb builderWithPrototype:resultFscSnsSinaMsgListPb];
}
- (FscSnsSinaMsgListPb*) defaultInstance {
  return [FscSnsSinaMsgListPb defaultInstance];
}
- (FscSnsSinaMsgListPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsSinaMsgListPb*) buildPartial {
  FscSnsSinaMsgListPb* returnMe = resultFscSnsSinaMsgListPb;
  self.resultFscSnsSinaMsgListPb = nil;
  return returnMe;
}
- (FscSnsSinaMsgListPbBuilder*) mergeFrom:(FscSnsSinaMsgListPb*) other {
  if (other == [FscSnsSinaMsgListPb defaultInstance]) {
    return self;
  }
  if (other.fscSnsMsgPbArray.count > 0) {
    if (resultFscSnsSinaMsgListPb.fscSnsMsgPbArray == nil) {
      resultFscSnsSinaMsgListPb.fscSnsMsgPbArray = [[NSMutableArray alloc] initWithArray:other.fscSnsMsgPbArray];
    } else {
      [resultFscSnsSinaMsgListPb.fscSnsMsgPbArray addObjectsFromArray:other.fscSnsMsgPbArray];
    }
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsSinaMsgListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsSinaMsgListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 10: {
        FscSnsMsgPbBuilder* subBuilder = [FscSnsMsgPb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFscSnsMsgPb:[subBuilder buildPartial]];
        break;
      }
    }
  }
}
- (NSMutableArray *)fscSnsMsgPb {
  return resultFscSnsSinaMsgListPb.fscSnsMsgPbArray;
}
- (FscSnsMsgPb*)fscSnsMsgPbAtIndex:(NSUInteger)index {
  return [resultFscSnsSinaMsgListPb fscSnsMsgPbAtIndex:index];
}
- (FscSnsSinaMsgListPbBuilder *)addFscSnsMsgPb:(FscSnsMsgPb*)value {
  if (resultFscSnsSinaMsgListPb.fscSnsMsgPbArray == nil) {
    resultFscSnsSinaMsgListPb.fscSnsMsgPbArray = [[NSMutableArray alloc]init];
  }
  [resultFscSnsSinaMsgListPb.fscSnsMsgPbArray addObject:value];
  return self;
}
- (FscSnsSinaMsgListPbBuilder *)setFscSnsMsgPbArray:(NSArray *)array {
  resultFscSnsSinaMsgListPb.fscSnsMsgPbArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FscSnsSinaMsgListPbBuilder *)clearFscSnsMsgPb {
  resultFscSnsSinaMsgListPb.fscSnsMsgPbArray = nil;
  return self;
}
@end

@interface FscSnsMsgPb ()
@property SInt64 id;
@property SInt32 msgType;
@property (strong) NSString* msg;
@property (strong) NSString* resPath;
@property SInt64 praiseCount;
@property SInt64 commentCount;
@property SInt32 dataStatus;
@property SInt64 createdDate;
@property SInt64 createdBy;
@property SInt64 timestamp;
@property (strong) NSMutableArray * fscSnsPraisePbArray;
@property (strong) NSMutableArray * fscSnsCommentPbArray;
@property (strong) NSMutableArray * fscSnsMsgImgPbArray;
@property SInt64 sinaId;
@property (strong) NSString* source;
@end

@implementation FscSnsMsgPb

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value_ {
  hasId_ = !!_value_;
}
@synthesize id;
- (BOOL) hasMsgType {
  return !!hasMsgType_;
}
- (void) setHasMsgType:(BOOL) _value_ {
  hasMsgType_ = !!_value_;
}
@synthesize msgType;
- (BOOL) hasMsg {
  return !!hasMsg_;
}
- (void) setHasMsg:(BOOL) _value_ {
  hasMsg_ = !!_value_;
}
@synthesize msg;
- (BOOL) hasResPath {
  return !!hasResPath_;
}
- (void) setHasResPath:(BOOL) _value_ {
  hasResPath_ = !!_value_;
}
@synthesize resPath;
- (BOOL) hasPraiseCount {
  return !!hasPraiseCount_;
}
- (void) setHasPraiseCount:(BOOL) _value_ {
  hasPraiseCount_ = !!_value_;
}
@synthesize praiseCount;
- (BOOL) hasCommentCount {
  return !!hasCommentCount_;
}
- (void) setHasCommentCount:(BOOL) _value_ {
  hasCommentCount_ = !!_value_;
}
@synthesize commentCount;
- (BOOL) hasDataStatus {
  return !!hasDataStatus_;
}
- (void) setHasDataStatus:(BOOL) _value_ {
  hasDataStatus_ = !!_value_;
}
@synthesize dataStatus;
- (BOOL) hasCreatedDate {
  return !!hasCreatedDate_;
}
- (void) setHasCreatedDate:(BOOL) _value_ {
  hasCreatedDate_ = !!_value_;
}
@synthesize createdDate;
- (BOOL) hasCreatedBy {
  return !!hasCreatedBy_;
}
- (void) setHasCreatedBy:(BOOL) _value_ {
  hasCreatedBy_ = !!_value_;
}
@synthesize createdBy;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) _value_ {
  hasTimestamp_ = !!_value_;
}
@synthesize timestamp;
@synthesize fscSnsPraisePbArray;
@dynamic fscSnsPraisePb;
@synthesize fscSnsCommentPbArray;
@dynamic fscSnsCommentPb;
@synthesize fscSnsMsgImgPbArray;
@dynamic fscSnsMsgImgPb;
- (BOOL) hasSinaId {
  return !!hasSinaId_;
}
- (void) setHasSinaId:(BOOL) _value_ {
  hasSinaId_ = !!_value_;
}
@synthesize sinaId;
- (BOOL) hasSource {
  return !!hasSource_;
}
- (void) setHasSource:(BOOL) _value_ {
  hasSource_ = !!_value_;
}
@synthesize source;
- (instancetype) init {
  if ((self = [super init])) {
    self.id = 0L;
    self.msgType = 0;
    self.msg = @"";
    self.resPath = @"";
    self.praiseCount = 0L;
    self.commentCount = 0L;
    self.dataStatus = 0;
    self.createdDate = 0L;
    self.createdBy = 0L;
    self.timestamp = 0L;
    self.sinaId = 0L;
    self.source = @"";
  }
  return self;
}
static FscSnsMsgPb* defaultFscSnsMsgPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsMsgPb class]) {
    defaultFscSnsMsgPbInstance = [[FscSnsMsgPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsMsgPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsMsgPbInstance;
}
- (NSArray *)fscSnsPraisePb {
  return fscSnsPraisePbArray;
}
- (FscSnsPraisePb*)fscSnsPraisePbAtIndex:(NSUInteger)index {
  return [fscSnsPraisePbArray objectAtIndex:index];
}
- (NSArray *)fscSnsCommentPb {
  return fscSnsCommentPbArray;
}
- (FscSnsCommentPb*)fscSnsCommentPbAtIndex:(NSUInteger)index {
  return [fscSnsCommentPbArray objectAtIndex:index];
}
- (NSArray *)fscSnsMsgImgPb {
  return fscSnsMsgImgPbArray;
}
- (FscSnsMsgImgPb*)fscSnsMsgImgPbAtIndex:(NSUInteger)index {
  return [fscSnsMsgImgPbArray objectAtIndex:index];
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt64:1 value:self.id];
  }
  if (self.hasMsgType) {
    [output writeInt32:2 value:self.msgType];
  }
  if (self.hasMsg) {
    [output writeString:3 value:self.msg];
  }
  if (self.hasResPath) {
    [output writeString:4 value:self.resPath];
  }
  if (self.hasPraiseCount) {
    [output writeInt64:5 value:self.praiseCount];
  }
  if (self.hasCommentCount) {
    [output writeInt64:6 value:self.commentCount];
  }
  if (self.hasDataStatus) {
    [output writeInt32:7 value:self.dataStatus];
  }
  if (self.hasCreatedDate) {
    [output writeInt64:8 value:self.createdDate];
  }
  if (self.hasCreatedBy) {
    [output writeInt64:9 value:self.createdBy];
  }
  if (self.hasTimestamp) {
    [output writeInt64:10 value:self.timestamp];
  }
  [self.fscSnsPraisePbArray enumerateObjectsUsingBlock:^(FscSnsPraisePb *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:11 value:element];
  }];
  [self.fscSnsCommentPbArray enumerateObjectsUsingBlock:^(FscSnsCommentPb *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:12 value:element];
  }];
  [self.fscSnsMsgImgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgImgPb *element, NSUInteger idx, BOOL *stop) {
    [output writeMessage:13 value:element];
  }];
  if (self.hasSinaId) {
    [output writeInt64:14 value:self.sinaId];
  }
  if (self.hasSource) {
    [output writeString:15 value:self.source];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt64Size(1, self.id);
  }
  if (self.hasMsgType) {
    size_ += computeInt32Size(2, self.msgType);
  }
  if (self.hasMsg) {
    size_ += computeStringSize(3, self.msg);
  }
  if (self.hasResPath) {
    size_ += computeStringSize(4, self.resPath);
  }
  if (self.hasPraiseCount) {
    size_ += computeInt64Size(5, self.praiseCount);
  }
  if (self.hasCommentCount) {
    size_ += computeInt64Size(6, self.commentCount);
  }
  if (self.hasDataStatus) {
    size_ += computeInt32Size(7, self.dataStatus);
  }
  if (self.hasCreatedDate) {
    size_ += computeInt64Size(8, self.createdDate);
  }
  if (self.hasCreatedBy) {
    size_ += computeInt64Size(9, self.createdBy);
  }
  if (self.hasTimestamp) {
    size_ += computeInt64Size(10, self.timestamp);
  }
  [self.fscSnsPraisePbArray enumerateObjectsUsingBlock:^(FscSnsPraisePb *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(11, element);
  }];
  [self.fscSnsCommentPbArray enumerateObjectsUsingBlock:^(FscSnsCommentPb *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(12, element);
  }];
  [self.fscSnsMsgImgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgImgPb *element, NSUInteger idx, BOOL *stop) {
    size_ += computeMessageSize(13, element);
  }];
  if (self.hasSinaId) {
    size_ += computeInt64Size(14, self.sinaId);
  }
  if (self.hasSource) {
    size_ += computeStringSize(15, self.source);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsMsgPb*) parseFromData:(NSData*) data {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromData:data] build];
}
+ (FscSnsMsgPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsMsgPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsMsgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsMsgPb*)[[[FscSnsMsgPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsMsgPbBuilder*) builder {
  return [[FscSnsMsgPbBuilder alloc] init];
}
+ (FscSnsMsgPbBuilder*) builderWithPrototype:(FscSnsMsgPb*) prototype {
  return [[FscSnsMsgPb builder] mergeFrom:prototype];
}
- (FscSnsMsgPbBuilder*) builder {
  return [FscSnsMsgPb builder];
}
- (FscSnsMsgPbBuilder*) toBuilder {
  return [FscSnsMsgPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithLongLong:self.id]];
  }
  if (self.hasMsgType) {
    [output appendFormat:@"%@%@: %@\n", indent, @"msgType", [NSNumber numberWithInteger:self.msgType]];
  }
  if (self.hasMsg) {
    [output appendFormat:@"%@%@: %@\n", indent, @"msg", self.msg];
  }
  if (self.hasResPath) {
    [output appendFormat:@"%@%@: %@\n", indent, @"resPath", self.resPath];
  }
  if (self.hasPraiseCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"praiseCount", [NSNumber numberWithLongLong:self.praiseCount]];
  }
  if (self.hasCommentCount) {
    [output appendFormat:@"%@%@: %@\n", indent, @"commentCount", [NSNumber numberWithLongLong:self.commentCount]];
  }
  if (self.hasDataStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"dataStatus", [NSNumber numberWithInteger:self.dataStatus]];
  }
  if (self.hasCreatedDate) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createdDate", [NSNumber numberWithLongLong:self.createdDate]];
  }
  if (self.hasCreatedBy) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createdBy", [NSNumber numberWithLongLong:self.createdBy]];
  }
  if (self.hasTimestamp) {
    [output appendFormat:@"%@%@: %@\n", indent, @"timestamp", [NSNumber numberWithLongLong:self.timestamp]];
  }
  [self.fscSnsPraisePbArray enumerateObjectsUsingBlock:^(FscSnsPraisePb *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"fscSnsPraisePb"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.fscSnsCommentPbArray enumerateObjectsUsingBlock:^(FscSnsCommentPb *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"fscSnsCommentPb"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  [self.fscSnsMsgImgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgImgPb *element, NSUInteger idx, BOOL *stop) {
    [output appendFormat:@"%@%@ {\n", indent, @"fscSnsMsgImgPb"];
    [element writeDescriptionTo:output
                     withIndent:[NSString stringWithFormat:@"%@  ", indent]];
    [output appendFormat:@"%@}\n", indent];
  }];
  if (self.hasSinaId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"sinaId", [NSNumber numberWithLongLong:self.sinaId]];
  }
  if (self.hasSource) {
    [output appendFormat:@"%@%@: %@\n", indent, @"source", self.source];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.id] forKey: @"id"];
  }
  if (self.hasMsgType) {
    [dictionary setObject: [NSNumber numberWithInteger:self.msgType] forKey: @"msgType"];
  }
  if (self.hasMsg) {
    [dictionary setObject: self.msg forKey: @"msg"];
  }
  if (self.hasResPath) {
    [dictionary setObject: self.resPath forKey: @"resPath"];
  }
  if (self.hasPraiseCount) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.praiseCount] forKey: @"praiseCount"];
  }
  if (self.hasCommentCount) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.commentCount] forKey: @"commentCount"];
  }
  if (self.hasDataStatus) {
    [dictionary setObject: [NSNumber numberWithInteger:self.dataStatus] forKey: @"dataStatus"];
  }
  if (self.hasCreatedDate) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.createdDate] forKey: @"createdDate"];
  }
  if (self.hasCreatedBy) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.createdBy] forKey: @"createdBy"];
  }
  if (self.hasTimestamp) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.timestamp] forKey: @"timestamp"];
  }
  for (FscSnsPraisePb* element in self.fscSnsPraisePbArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"fscSnsPraisePb"];
  }
  for (FscSnsCommentPb* element in self.fscSnsCommentPbArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"fscSnsCommentPb"];
  }
  for (FscSnsMsgImgPb* element in self.fscSnsMsgImgPbArray) {
    NSMutableDictionary *elementDictionary = [NSMutableDictionary dictionary];
    [element storeInDictionary:elementDictionary];
    [dictionary setObject:[NSDictionary dictionaryWithDictionary:elementDictionary] forKey:@"fscSnsMsgImgPb"];
  }
  if (self.hasSinaId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.sinaId] forKey: @"sinaId"];
  }
  if (self.hasSource) {
    [dictionary setObject: self.source forKey: @"source"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsMsgPb class]]) {
    return NO;
  }
  FscSnsMsgPb *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasMsgType == otherMessage.hasMsgType &&
      (!self.hasMsgType || self.msgType == otherMessage.msgType) &&
      self.hasMsg == otherMessage.hasMsg &&
      (!self.hasMsg || [self.msg isEqual:otherMessage.msg]) &&
      self.hasResPath == otherMessage.hasResPath &&
      (!self.hasResPath || [self.resPath isEqual:otherMessage.resPath]) &&
      self.hasPraiseCount == otherMessage.hasPraiseCount &&
      (!self.hasPraiseCount || self.praiseCount == otherMessage.praiseCount) &&
      self.hasCommentCount == otherMessage.hasCommentCount &&
      (!self.hasCommentCount || self.commentCount == otherMessage.commentCount) &&
      self.hasDataStatus == otherMessage.hasDataStatus &&
      (!self.hasDataStatus || self.dataStatus == otherMessage.dataStatus) &&
      self.hasCreatedDate == otherMessage.hasCreatedDate &&
      (!self.hasCreatedDate || self.createdDate == otherMessage.createdDate) &&
      self.hasCreatedBy == otherMessage.hasCreatedBy &&
      (!self.hasCreatedBy || self.createdBy == otherMessage.createdBy) &&
      self.hasTimestamp == otherMessage.hasTimestamp &&
      (!self.hasTimestamp || self.timestamp == otherMessage.timestamp) &&
      [self.fscSnsPraisePbArray isEqualToArray:otherMessage.fscSnsPraisePbArray] &&
      [self.fscSnsCommentPbArray isEqualToArray:otherMessage.fscSnsCommentPbArray] &&
      [self.fscSnsMsgImgPbArray isEqualToArray:otherMessage.fscSnsMsgImgPbArray] &&
      self.hasSinaId == otherMessage.hasSinaId &&
      (!self.hasSinaId || self.sinaId == otherMessage.sinaId) &&
      self.hasSource == otherMessage.hasSource &&
      (!self.hasSource || [self.source isEqual:otherMessage.source]) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.id] hash];
  }
  if (self.hasMsgType) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.msgType] hash];
  }
  if (self.hasMsg) {
    hashCode = hashCode * 31 + [self.msg hash];
  }
  if (self.hasResPath) {
    hashCode = hashCode * 31 + [self.resPath hash];
  }
  if (self.hasPraiseCount) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.praiseCount] hash];
  }
  if (self.hasCommentCount) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.commentCount] hash];
  }
  if (self.hasDataStatus) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.dataStatus] hash];
  }
  if (self.hasCreatedDate) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.createdDate] hash];
  }
  if (self.hasCreatedBy) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.createdBy] hash];
  }
  if (self.hasTimestamp) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.timestamp] hash];
  }
  [self.fscSnsPraisePbArray enumerateObjectsUsingBlock:^(FscSnsPraisePb *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.fscSnsCommentPbArray enumerateObjectsUsingBlock:^(FscSnsCommentPb *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  [self.fscSnsMsgImgPbArray enumerateObjectsUsingBlock:^(FscSnsMsgImgPb *element, NSUInteger idx, BOOL *stop) {
    hashCode = hashCode * 31 + [element hash];
  }];
  if (self.hasSinaId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.sinaId] hash];
  }
  if (self.hasSource) {
    hashCode = hashCode * 31 + [self.source hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsMsgPbBuilder()
@property (strong) FscSnsMsgPb* resultFscSnsMsgPb;
@end

@implementation FscSnsMsgPbBuilder
@synthesize resultFscSnsMsgPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsMsgPb = [[FscSnsMsgPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsMsgPb;
}
- (FscSnsMsgPbBuilder*) clear {
  self.resultFscSnsMsgPb = [[FscSnsMsgPb alloc] init];
  return self;
}
- (FscSnsMsgPbBuilder*) clone {
  return [FscSnsMsgPb builderWithPrototype:resultFscSnsMsgPb];
}
- (FscSnsMsgPb*) defaultInstance {
  return [FscSnsMsgPb defaultInstance];
}
- (FscSnsMsgPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsMsgPb*) buildPartial {
  FscSnsMsgPb* returnMe = resultFscSnsMsgPb;
  self.resultFscSnsMsgPb = nil;
  return returnMe;
}
- (FscSnsMsgPbBuilder*) mergeFrom:(FscSnsMsgPb*) other {
  if (other == [FscSnsMsgPb defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasMsgType) {
    [self setMsgType:other.msgType];
  }
  if (other.hasMsg) {
    [self setMsg:other.msg];
  }
  if (other.hasResPath) {
    [self setResPath:other.resPath];
  }
  if (other.hasPraiseCount) {
    [self setPraiseCount:other.praiseCount];
  }
  if (other.hasCommentCount) {
    [self setCommentCount:other.commentCount];
  }
  if (other.hasDataStatus) {
    [self setDataStatus:other.dataStatus];
  }
  if (other.hasCreatedDate) {
    [self setCreatedDate:other.createdDate];
  }
  if (other.hasCreatedBy) {
    [self setCreatedBy:other.createdBy];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  if (other.fscSnsPraisePbArray.count > 0) {
    if (resultFscSnsMsgPb.fscSnsPraisePbArray == nil) {
      resultFscSnsMsgPb.fscSnsPraisePbArray = [[NSMutableArray alloc] initWithArray:other.fscSnsPraisePbArray];
    } else {
      [resultFscSnsMsgPb.fscSnsPraisePbArray addObjectsFromArray:other.fscSnsPraisePbArray];
    }
  }
  if (other.fscSnsCommentPbArray.count > 0) {
    if (resultFscSnsMsgPb.fscSnsCommentPbArray == nil) {
      resultFscSnsMsgPb.fscSnsCommentPbArray = [[NSMutableArray alloc] initWithArray:other.fscSnsCommentPbArray];
    } else {
      [resultFscSnsMsgPb.fscSnsCommentPbArray addObjectsFromArray:other.fscSnsCommentPbArray];
    }
  }
  if (other.fscSnsMsgImgPbArray.count > 0) {
    if (resultFscSnsMsgPb.fscSnsMsgImgPbArray == nil) {
      resultFscSnsMsgPb.fscSnsMsgImgPbArray = [[NSMutableArray alloc] initWithArray:other.fscSnsMsgImgPbArray];
    } else {
      [resultFscSnsMsgPb.fscSnsMsgImgPbArray addObjectsFromArray:other.fscSnsMsgImgPbArray];
    }
  }
  if (other.hasSinaId) {
    [self setSinaId:other.sinaId];
  }
  if (other.hasSource) {
    [self setSource:other.source];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsMsgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsMsgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt64]];
        break;
      }
      case 16: {
        [self setMsgType:[input readInt32]];
        break;
      }
      case 26: {
        [self setMsg:[input readString]];
        break;
      }
      case 34: {
        [self setResPath:[input readString]];
        break;
      }
      case 40: {
        [self setPraiseCount:[input readInt64]];
        break;
      }
      case 48: {
        [self setCommentCount:[input readInt64]];
        break;
      }
      case 56: {
        [self setDataStatus:[input readInt32]];
        break;
      }
      case 64: {
        [self setCreatedDate:[input readInt64]];
        break;
      }
      case 72: {
        [self setCreatedBy:[input readInt64]];
        break;
      }
      case 80: {
        [self setTimestamp:[input readInt64]];
        break;
      }
      case 90: {
        FscSnsPraisePbBuilder* subBuilder = [FscSnsPraisePb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFscSnsPraisePb:[subBuilder buildPartial]];
        break;
      }
      case 98: {
        FscSnsCommentPbBuilder* subBuilder = [FscSnsCommentPb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFscSnsCommentPb:[subBuilder buildPartial]];
        break;
      }
      case 106: {
        FscSnsMsgImgPbBuilder* subBuilder = [FscSnsMsgImgPb builder];
        [input readMessage:subBuilder extensionRegistry:extensionRegistry];
        [self addFscSnsMsgImgPb:[subBuilder buildPartial]];
        break;
      }
      case 112: {
        [self setSinaId:[input readInt64]];
        break;
      }
      case 122: {
        [self setSource:[input readString]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return resultFscSnsMsgPb.hasId;
}
- (SInt64) id {
  return resultFscSnsMsgPb.id;
}
- (FscSnsMsgPbBuilder*) setId:(SInt64) value {
  resultFscSnsMsgPb.hasId = YES;
  resultFscSnsMsgPb.id = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearId {
  resultFscSnsMsgPb.hasId = NO;
  resultFscSnsMsgPb.id = 0L;
  return self;
}
- (BOOL) hasMsgType {
  return resultFscSnsMsgPb.hasMsgType;
}
- (SInt32) msgType {
  return resultFscSnsMsgPb.msgType;
}
- (FscSnsMsgPbBuilder*) setMsgType:(SInt32) value {
  resultFscSnsMsgPb.hasMsgType = YES;
  resultFscSnsMsgPb.msgType = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearMsgType {
  resultFscSnsMsgPb.hasMsgType = NO;
  resultFscSnsMsgPb.msgType = 0;
  return self;
}
- (BOOL) hasMsg {
  return resultFscSnsMsgPb.hasMsg;
}
- (NSString*) msg {
  return resultFscSnsMsgPb.msg;
}
- (FscSnsMsgPbBuilder*) setMsg:(NSString*) value {
  resultFscSnsMsgPb.hasMsg = YES;
  resultFscSnsMsgPb.msg = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearMsg {
  resultFscSnsMsgPb.hasMsg = NO;
  resultFscSnsMsgPb.msg = @"";
  return self;
}
- (BOOL) hasResPath {
  return resultFscSnsMsgPb.hasResPath;
}
- (NSString*) resPath {
  return resultFscSnsMsgPb.resPath;
}
- (FscSnsMsgPbBuilder*) setResPath:(NSString*) value {
  resultFscSnsMsgPb.hasResPath = YES;
  resultFscSnsMsgPb.resPath = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearResPath {
  resultFscSnsMsgPb.hasResPath = NO;
  resultFscSnsMsgPb.resPath = @"";
  return self;
}
- (BOOL) hasPraiseCount {
  return resultFscSnsMsgPb.hasPraiseCount;
}
- (SInt64) praiseCount {
  return resultFscSnsMsgPb.praiseCount;
}
- (FscSnsMsgPbBuilder*) setPraiseCount:(SInt64) value {
  resultFscSnsMsgPb.hasPraiseCount = YES;
  resultFscSnsMsgPb.praiseCount = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearPraiseCount {
  resultFscSnsMsgPb.hasPraiseCount = NO;
  resultFscSnsMsgPb.praiseCount = 0L;
  return self;
}
- (BOOL) hasCommentCount {
  return resultFscSnsMsgPb.hasCommentCount;
}
- (SInt64) commentCount {
  return resultFscSnsMsgPb.commentCount;
}
- (FscSnsMsgPbBuilder*) setCommentCount:(SInt64) value {
  resultFscSnsMsgPb.hasCommentCount = YES;
  resultFscSnsMsgPb.commentCount = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearCommentCount {
  resultFscSnsMsgPb.hasCommentCount = NO;
  resultFscSnsMsgPb.commentCount = 0L;
  return self;
}
- (BOOL) hasDataStatus {
  return resultFscSnsMsgPb.hasDataStatus;
}
- (SInt32) dataStatus {
  return resultFscSnsMsgPb.dataStatus;
}
- (FscSnsMsgPbBuilder*) setDataStatus:(SInt32) value {
  resultFscSnsMsgPb.hasDataStatus = YES;
  resultFscSnsMsgPb.dataStatus = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearDataStatus {
  resultFscSnsMsgPb.hasDataStatus = NO;
  resultFscSnsMsgPb.dataStatus = 0;
  return self;
}
- (BOOL) hasCreatedDate {
  return resultFscSnsMsgPb.hasCreatedDate;
}
- (SInt64) createdDate {
  return resultFscSnsMsgPb.createdDate;
}
- (FscSnsMsgPbBuilder*) setCreatedDate:(SInt64) value {
  resultFscSnsMsgPb.hasCreatedDate = YES;
  resultFscSnsMsgPb.createdDate = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearCreatedDate {
  resultFscSnsMsgPb.hasCreatedDate = NO;
  resultFscSnsMsgPb.createdDate = 0L;
  return self;
}
- (BOOL) hasCreatedBy {
  return resultFscSnsMsgPb.hasCreatedBy;
}
- (SInt64) createdBy {
  return resultFscSnsMsgPb.createdBy;
}
- (FscSnsMsgPbBuilder*) setCreatedBy:(SInt64) value {
  resultFscSnsMsgPb.hasCreatedBy = YES;
  resultFscSnsMsgPb.createdBy = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearCreatedBy {
  resultFscSnsMsgPb.hasCreatedBy = NO;
  resultFscSnsMsgPb.createdBy = 0L;
  return self;
}
- (BOOL) hasTimestamp {
  return resultFscSnsMsgPb.hasTimestamp;
}
- (SInt64) timestamp {
  return resultFscSnsMsgPb.timestamp;
}
- (FscSnsMsgPbBuilder*) setTimestamp:(SInt64) value {
  resultFscSnsMsgPb.hasTimestamp = YES;
  resultFscSnsMsgPb.timestamp = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearTimestamp {
  resultFscSnsMsgPb.hasTimestamp = NO;
  resultFscSnsMsgPb.timestamp = 0L;
  return self;
}
- (NSMutableArray *)fscSnsPraisePb {
  return resultFscSnsMsgPb.fscSnsPraisePbArray;
}
- (FscSnsPraisePb*)fscSnsPraisePbAtIndex:(NSUInteger)index {
  return [resultFscSnsMsgPb fscSnsPraisePbAtIndex:index];
}
- (FscSnsMsgPbBuilder *)addFscSnsPraisePb:(FscSnsPraisePb*)value {
  if (resultFscSnsMsgPb.fscSnsPraisePbArray == nil) {
    resultFscSnsMsgPb.fscSnsPraisePbArray = [[NSMutableArray alloc]init];
  }
  [resultFscSnsMsgPb.fscSnsPraisePbArray addObject:value];
  return self;
}
- (FscSnsMsgPbBuilder *)setFscSnsPraisePbArray:(NSArray *)array {
  resultFscSnsMsgPb.fscSnsPraisePbArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FscSnsMsgPbBuilder *)clearFscSnsPraisePb {
  resultFscSnsMsgPb.fscSnsPraisePbArray = nil;
  return self;
}
- (NSMutableArray *)fscSnsCommentPb {
  return resultFscSnsMsgPb.fscSnsCommentPbArray;
}
- (FscSnsCommentPb*)fscSnsCommentPbAtIndex:(NSUInteger)index {
  return [resultFscSnsMsgPb fscSnsCommentPbAtIndex:index];
}
- (FscSnsMsgPbBuilder *)addFscSnsCommentPb:(FscSnsCommentPb*)value {
  if (resultFscSnsMsgPb.fscSnsCommentPbArray == nil) {
    resultFscSnsMsgPb.fscSnsCommentPbArray = [[NSMutableArray alloc]init];
  }
  [resultFscSnsMsgPb.fscSnsCommentPbArray addObject:value];
  return self;
}
- (FscSnsMsgPbBuilder *)setFscSnsCommentPbArray:(NSArray *)array {
  resultFscSnsMsgPb.fscSnsCommentPbArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FscSnsMsgPbBuilder *)clearFscSnsCommentPb {
  resultFscSnsMsgPb.fscSnsCommentPbArray = nil;
  return self;
}
- (NSMutableArray *)fscSnsMsgImgPb {
  return resultFscSnsMsgPb.fscSnsMsgImgPbArray;
}
- (FscSnsMsgImgPb*)fscSnsMsgImgPbAtIndex:(NSUInteger)index {
  return [resultFscSnsMsgPb fscSnsMsgImgPbAtIndex:index];
}
- (FscSnsMsgPbBuilder *)addFscSnsMsgImgPb:(FscSnsMsgImgPb*)value {
  if (resultFscSnsMsgPb.fscSnsMsgImgPbArray == nil) {
    resultFscSnsMsgPb.fscSnsMsgImgPbArray = [[NSMutableArray alloc]init];
  }
  [resultFscSnsMsgPb.fscSnsMsgImgPbArray addObject:value];
  return self;
}
- (FscSnsMsgPbBuilder *)setFscSnsMsgImgPbArray:(NSArray *)array {
  resultFscSnsMsgPb.fscSnsMsgImgPbArray = [[NSMutableArray alloc]initWithArray:array];
  return self;
}
- (FscSnsMsgPbBuilder *)clearFscSnsMsgImgPb {
  resultFscSnsMsgPb.fscSnsMsgImgPbArray = nil;
  return self;
}
- (BOOL) hasSinaId {
  return resultFscSnsMsgPb.hasSinaId;
}
- (SInt64) sinaId {
  return resultFscSnsMsgPb.sinaId;
}
- (FscSnsMsgPbBuilder*) setSinaId:(SInt64) value {
  resultFscSnsMsgPb.hasSinaId = YES;
  resultFscSnsMsgPb.sinaId = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearSinaId {
  resultFscSnsMsgPb.hasSinaId = NO;
  resultFscSnsMsgPb.sinaId = 0L;
  return self;
}
- (BOOL) hasSource {
  return resultFscSnsMsgPb.hasSource;
}
- (NSString*) source {
  return resultFscSnsMsgPb.source;
}
- (FscSnsMsgPbBuilder*) setSource:(NSString*) value {
  resultFscSnsMsgPb.hasSource = YES;
  resultFscSnsMsgPb.source = value;
  return self;
}
- (FscSnsMsgPbBuilder*) clearSource {
  resultFscSnsMsgPb.hasSource = NO;
  resultFscSnsMsgPb.source = @"";
  return self;
}
@end

@interface FscSnsPraisePb ()
@property SInt64 id;
@property SInt64 msgId;
@property SInt64 userId;
@property SInt32 dataStatus;
@property SInt64 timestamp;
@property SInt64 createdDate;
@end

@implementation FscSnsPraisePb

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value_ {
  hasId_ = !!_value_;
}
@synthesize id;
- (BOOL) hasMsgId {
  return !!hasMsgId_;
}
- (void) setHasMsgId:(BOOL) _value_ {
  hasMsgId_ = !!_value_;
}
@synthesize msgId;
- (BOOL) hasUserId {
  return !!hasUserId_;
}
- (void) setHasUserId:(BOOL) _value_ {
  hasUserId_ = !!_value_;
}
@synthesize userId;
- (BOOL) hasDataStatus {
  return !!hasDataStatus_;
}
- (void) setHasDataStatus:(BOOL) _value_ {
  hasDataStatus_ = !!_value_;
}
@synthesize dataStatus;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) _value_ {
  hasTimestamp_ = !!_value_;
}
@synthesize timestamp;
- (BOOL) hasCreatedDate {
  return !!hasCreatedDate_;
}
- (void) setHasCreatedDate:(BOOL) _value_ {
  hasCreatedDate_ = !!_value_;
}
@synthesize createdDate;
- (instancetype) init {
  if ((self = [super init])) {
    self.id = 0L;
    self.msgId = 0L;
    self.userId = 0L;
    self.dataStatus = 0;
    self.timestamp = 0L;
    self.createdDate = 0L;
  }
  return self;
}
static FscSnsPraisePb* defaultFscSnsPraisePbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsPraisePb class]) {
    defaultFscSnsPraisePbInstance = [[FscSnsPraisePb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsPraisePbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsPraisePbInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt64:1 value:self.id];
  }
  if (self.hasMsgId) {
    [output writeInt64:2 value:self.msgId];
  }
  if (self.hasUserId) {
    [output writeInt64:3 value:self.userId];
  }
  if (self.hasDataStatus) {
    [output writeInt32:4 value:self.dataStatus];
  }
  if (self.hasTimestamp) {
    [output writeInt64:5 value:self.timestamp];
  }
  if (self.hasCreatedDate) {
    [output writeInt64:6 value:self.createdDate];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt64Size(1, self.id);
  }
  if (self.hasMsgId) {
    size_ += computeInt64Size(2, self.msgId);
  }
  if (self.hasUserId) {
    size_ += computeInt64Size(3, self.userId);
  }
  if (self.hasDataStatus) {
    size_ += computeInt32Size(4, self.dataStatus);
  }
  if (self.hasTimestamp) {
    size_ += computeInt64Size(5, self.timestamp);
  }
  if (self.hasCreatedDate) {
    size_ += computeInt64Size(6, self.createdDate);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsPraisePb*) parseFromData:(NSData*) data {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromData:data] build];
}
+ (FscSnsPraisePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsPraisePb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromInputStream:input] build];
}
+ (FscSnsPraisePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsPraisePb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsPraisePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsPraisePb*)[[[FscSnsPraisePb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsPraisePbBuilder*) builder {
  return [[FscSnsPraisePbBuilder alloc] init];
}
+ (FscSnsPraisePbBuilder*) builderWithPrototype:(FscSnsPraisePb*) prototype {
  return [[FscSnsPraisePb builder] mergeFrom:prototype];
}
- (FscSnsPraisePbBuilder*) builder {
  return [FscSnsPraisePb builder];
}
- (FscSnsPraisePbBuilder*) toBuilder {
  return [FscSnsPraisePb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithLongLong:self.id]];
  }
  if (self.hasMsgId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"msgId", [NSNumber numberWithLongLong:self.msgId]];
  }
  if (self.hasUserId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"userId", [NSNumber numberWithLongLong:self.userId]];
  }
  if (self.hasDataStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"dataStatus", [NSNumber numberWithInteger:self.dataStatus]];
  }
  if (self.hasTimestamp) {
    [output appendFormat:@"%@%@: %@\n", indent, @"timestamp", [NSNumber numberWithLongLong:self.timestamp]];
  }
  if (self.hasCreatedDate) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createdDate", [NSNumber numberWithLongLong:self.createdDate]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.id] forKey: @"id"];
  }
  if (self.hasMsgId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.msgId] forKey: @"msgId"];
  }
  if (self.hasUserId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.userId] forKey: @"userId"];
  }
  if (self.hasDataStatus) {
    [dictionary setObject: [NSNumber numberWithInteger:self.dataStatus] forKey: @"dataStatus"];
  }
  if (self.hasTimestamp) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.timestamp] forKey: @"timestamp"];
  }
  if (self.hasCreatedDate) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.createdDate] forKey: @"createdDate"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsPraisePb class]]) {
    return NO;
  }
  FscSnsPraisePb *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasMsgId == otherMessage.hasMsgId &&
      (!self.hasMsgId || self.msgId == otherMessage.msgId) &&
      self.hasUserId == otherMessage.hasUserId &&
      (!self.hasUserId || self.userId == otherMessage.userId) &&
      self.hasDataStatus == otherMessage.hasDataStatus &&
      (!self.hasDataStatus || self.dataStatus == otherMessage.dataStatus) &&
      self.hasTimestamp == otherMessage.hasTimestamp &&
      (!self.hasTimestamp || self.timestamp == otherMessage.timestamp) &&
      self.hasCreatedDate == otherMessage.hasCreatedDate &&
      (!self.hasCreatedDate || self.createdDate == otherMessage.createdDate) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.id] hash];
  }
  if (self.hasMsgId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.msgId] hash];
  }
  if (self.hasUserId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.userId] hash];
  }
  if (self.hasDataStatus) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.dataStatus] hash];
  }
  if (self.hasTimestamp) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.timestamp] hash];
  }
  if (self.hasCreatedDate) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.createdDate] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsPraisePbBuilder()
@property (strong) FscSnsPraisePb* resultFscSnsPraisePb;
@end

@implementation FscSnsPraisePbBuilder
@synthesize resultFscSnsPraisePb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsPraisePb = [[FscSnsPraisePb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsPraisePb;
}
- (FscSnsPraisePbBuilder*) clear {
  self.resultFscSnsPraisePb = [[FscSnsPraisePb alloc] init];
  return self;
}
- (FscSnsPraisePbBuilder*) clone {
  return [FscSnsPraisePb builderWithPrototype:resultFscSnsPraisePb];
}
- (FscSnsPraisePb*) defaultInstance {
  return [FscSnsPraisePb defaultInstance];
}
- (FscSnsPraisePb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsPraisePb*) buildPartial {
  FscSnsPraisePb* returnMe = resultFscSnsPraisePb;
  self.resultFscSnsPraisePb = nil;
  return returnMe;
}
- (FscSnsPraisePbBuilder*) mergeFrom:(FscSnsPraisePb*) other {
  if (other == [FscSnsPraisePb defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasMsgId) {
    [self setMsgId:other.msgId];
  }
  if (other.hasUserId) {
    [self setUserId:other.userId];
  }
  if (other.hasDataStatus) {
    [self setDataStatus:other.dataStatus];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  if (other.hasCreatedDate) {
    [self setCreatedDate:other.createdDate];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsPraisePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsPraisePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt64]];
        break;
      }
      case 16: {
        [self setMsgId:[input readInt64]];
        break;
      }
      case 24: {
        [self setUserId:[input readInt64]];
        break;
      }
      case 32: {
        [self setDataStatus:[input readInt32]];
        break;
      }
      case 40: {
        [self setTimestamp:[input readInt64]];
        break;
      }
      case 48: {
        [self setCreatedDate:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return resultFscSnsPraisePb.hasId;
}
- (SInt64) id {
  return resultFscSnsPraisePb.id;
}
- (FscSnsPraisePbBuilder*) setId:(SInt64) value {
  resultFscSnsPraisePb.hasId = YES;
  resultFscSnsPraisePb.id = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearId {
  resultFscSnsPraisePb.hasId = NO;
  resultFscSnsPraisePb.id = 0L;
  return self;
}
- (BOOL) hasMsgId {
  return resultFscSnsPraisePb.hasMsgId;
}
- (SInt64) msgId {
  return resultFscSnsPraisePb.msgId;
}
- (FscSnsPraisePbBuilder*) setMsgId:(SInt64) value {
  resultFscSnsPraisePb.hasMsgId = YES;
  resultFscSnsPraisePb.msgId = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearMsgId {
  resultFscSnsPraisePb.hasMsgId = NO;
  resultFscSnsPraisePb.msgId = 0L;
  return self;
}
- (BOOL) hasUserId {
  return resultFscSnsPraisePb.hasUserId;
}
- (SInt64) userId {
  return resultFscSnsPraisePb.userId;
}
- (FscSnsPraisePbBuilder*) setUserId:(SInt64) value {
  resultFscSnsPraisePb.hasUserId = YES;
  resultFscSnsPraisePb.userId = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearUserId {
  resultFscSnsPraisePb.hasUserId = NO;
  resultFscSnsPraisePb.userId = 0L;
  return self;
}
- (BOOL) hasDataStatus {
  return resultFscSnsPraisePb.hasDataStatus;
}
- (SInt32) dataStatus {
  return resultFscSnsPraisePb.dataStatus;
}
- (FscSnsPraisePbBuilder*) setDataStatus:(SInt32) value {
  resultFscSnsPraisePb.hasDataStatus = YES;
  resultFscSnsPraisePb.dataStatus = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearDataStatus {
  resultFscSnsPraisePb.hasDataStatus = NO;
  resultFscSnsPraisePb.dataStatus = 0;
  return self;
}
- (BOOL) hasTimestamp {
  return resultFscSnsPraisePb.hasTimestamp;
}
- (SInt64) timestamp {
  return resultFscSnsPraisePb.timestamp;
}
- (FscSnsPraisePbBuilder*) setTimestamp:(SInt64) value {
  resultFscSnsPraisePb.hasTimestamp = YES;
  resultFscSnsPraisePb.timestamp = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearTimestamp {
  resultFscSnsPraisePb.hasTimestamp = NO;
  resultFscSnsPraisePb.timestamp = 0L;
  return self;
}
- (BOOL) hasCreatedDate {
  return resultFscSnsPraisePb.hasCreatedDate;
}
- (SInt64) createdDate {
  return resultFscSnsPraisePb.createdDate;
}
- (FscSnsPraisePbBuilder*) setCreatedDate:(SInt64) value {
  resultFscSnsPraisePb.hasCreatedDate = YES;
  resultFscSnsPraisePb.createdDate = value;
  return self;
}
- (FscSnsPraisePbBuilder*) clearCreatedDate {
  resultFscSnsPraisePb.hasCreatedDate = NO;
  resultFscSnsPraisePb.createdDate = 0L;
  return self;
}
@end

@interface FscSnsCommentPb ()
@property SInt64 id;
@property SInt64 msgId;
@property SInt64 fromUser;
@property SInt64 toUser;
@property (strong) NSString* comment;
@property SInt32 dataStatus;
@property SInt64 timestamp;
@property SInt64 createdDate;
@end

@implementation FscSnsCommentPb

- (BOOL) hasId {
  return !!hasId_;
}
- (void) setHasId:(BOOL) _value_ {
  hasId_ = !!_value_;
}
@synthesize id;
- (BOOL) hasMsgId {
  return !!hasMsgId_;
}
- (void) setHasMsgId:(BOOL) _value_ {
  hasMsgId_ = !!_value_;
}
@synthesize msgId;
- (BOOL) hasFromUser {
  return !!hasFromUser_;
}
- (void) setHasFromUser:(BOOL) _value_ {
  hasFromUser_ = !!_value_;
}
@synthesize fromUser;
- (BOOL) hasToUser {
  return !!hasToUser_;
}
- (void) setHasToUser:(BOOL) _value_ {
  hasToUser_ = !!_value_;
}
@synthesize toUser;
- (BOOL) hasComment {
  return !!hasComment_;
}
- (void) setHasComment:(BOOL) _value_ {
  hasComment_ = !!_value_;
}
@synthesize comment;
- (BOOL) hasDataStatus {
  return !!hasDataStatus_;
}
- (void) setHasDataStatus:(BOOL) _value_ {
  hasDataStatus_ = !!_value_;
}
@synthesize dataStatus;
- (BOOL) hasTimestamp {
  return !!hasTimestamp_;
}
- (void) setHasTimestamp:(BOOL) _value_ {
  hasTimestamp_ = !!_value_;
}
@synthesize timestamp;
- (BOOL) hasCreatedDate {
  return !!hasCreatedDate_;
}
- (void) setHasCreatedDate:(BOOL) _value_ {
  hasCreatedDate_ = !!_value_;
}
@synthesize createdDate;
- (instancetype) init {
  if ((self = [super init])) {
    self.id = 0L;
    self.msgId = 0L;
    self.fromUser = 0L;
    self.toUser = 0L;
    self.comment = @"";
    self.dataStatus = 0;
    self.timestamp = 0L;
    self.createdDate = 0L;
  }
  return self;
}
static FscSnsCommentPb* defaultFscSnsCommentPbInstance = nil;
+ (void) initialize {
  if (self == [FscSnsCommentPb class]) {
    defaultFscSnsCommentPbInstance = [[FscSnsCommentPb alloc] init];
  }
}
+ (instancetype) defaultInstance {
  return defaultFscSnsCommentPbInstance;
}
- (instancetype) defaultInstance {
  return defaultFscSnsCommentPbInstance;
}
- (BOOL) isInitialized {
  return YES;
}
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output {
  if (self.hasId) {
    [output writeInt64:1 value:self.id];
  }
  if (self.hasMsgId) {
    [output writeInt64:2 value:self.msgId];
  }
  if (self.hasFromUser) {
    [output writeInt64:3 value:self.fromUser];
  }
  if (self.hasToUser) {
    [output writeInt64:4 value:self.toUser];
  }
  if (self.hasComment) {
    [output writeString:5 value:self.comment];
  }
  if (self.hasDataStatus) {
    [output writeInt32:6 value:self.dataStatus];
  }
  if (self.hasTimestamp) {
    [output writeInt64:7 value:self.timestamp];
  }
  if (self.hasCreatedDate) {
    [output writeInt64:8 value:self.createdDate];
  }
  [self.unknownFields writeToCodedOutputStream:output];
}
- (SInt32) serializedSize {
  __block SInt32 size_ = memoizedSerializedSize;
  if (size_ != -1) {
    return size_;
  }

  size_ = 0;
  if (self.hasId) {
    size_ += computeInt64Size(1, self.id);
  }
  if (self.hasMsgId) {
    size_ += computeInt64Size(2, self.msgId);
  }
  if (self.hasFromUser) {
    size_ += computeInt64Size(3, self.fromUser);
  }
  if (self.hasToUser) {
    size_ += computeInt64Size(4, self.toUser);
  }
  if (self.hasComment) {
    size_ += computeStringSize(5, self.comment);
  }
  if (self.hasDataStatus) {
    size_ += computeInt32Size(6, self.dataStatus);
  }
  if (self.hasTimestamp) {
    size_ += computeInt64Size(7, self.timestamp);
  }
  if (self.hasCreatedDate) {
    size_ += computeInt64Size(8, self.createdDate);
  }
  size_ += self.unknownFields.serializedSize;
  memoizedSerializedSize = size_;
  return size_;
}
+ (FscSnsCommentPb*) parseFromData:(NSData*) data {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromData:data] build];
}
+ (FscSnsCommentPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromData:data extensionRegistry:extensionRegistry] build];
}
+ (FscSnsCommentPb*) parseFromInputStream:(NSInputStream*) input {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromInputStream:input] build];
}
+ (FscSnsCommentPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsCommentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromCodedInputStream:input] build];
}
+ (FscSnsCommentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  return (FscSnsCommentPb*)[[[FscSnsCommentPb builder] mergeFromCodedInputStream:input extensionRegistry:extensionRegistry] build];
}
+ (FscSnsCommentPbBuilder*) builder {
  return [[FscSnsCommentPbBuilder alloc] init];
}
+ (FscSnsCommentPbBuilder*) builderWithPrototype:(FscSnsCommentPb*) prototype {
  return [[FscSnsCommentPb builder] mergeFrom:prototype];
}
- (FscSnsCommentPbBuilder*) builder {
  return [FscSnsCommentPb builder];
}
- (FscSnsCommentPbBuilder*) toBuilder {
  return [FscSnsCommentPb builderWithPrototype:self];
}
- (void) writeDescriptionTo:(NSMutableString*) output withIndent:(NSString*) indent {
  if (self.hasId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"id", [NSNumber numberWithLongLong:self.id]];
  }
  if (self.hasMsgId) {
    [output appendFormat:@"%@%@: %@\n", indent, @"msgId", [NSNumber numberWithLongLong:self.msgId]];
  }
  if (self.hasFromUser) {
    [output appendFormat:@"%@%@: %@\n", indent, @"fromUser", [NSNumber numberWithLongLong:self.fromUser]];
  }
  if (self.hasToUser) {
    [output appendFormat:@"%@%@: %@\n", indent, @"toUser", [NSNumber numberWithLongLong:self.toUser]];
  }
  if (self.hasComment) {
    [output appendFormat:@"%@%@: %@\n", indent, @"comment", self.comment];
  }
  if (self.hasDataStatus) {
    [output appendFormat:@"%@%@: %@\n", indent, @"dataStatus", [NSNumber numberWithInteger:self.dataStatus]];
  }
  if (self.hasTimestamp) {
    [output appendFormat:@"%@%@: %@\n", indent, @"timestamp", [NSNumber numberWithLongLong:self.timestamp]];
  }
  if (self.hasCreatedDate) {
    [output appendFormat:@"%@%@: %@\n", indent, @"createdDate", [NSNumber numberWithLongLong:self.createdDate]];
  }
  [self.unknownFields writeDescriptionTo:output withIndent:indent];
}
- (void) storeInDictionary:(NSMutableDictionary *)dictionary {
  if (self.hasId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.id] forKey: @"id"];
  }
  if (self.hasMsgId) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.msgId] forKey: @"msgId"];
  }
  if (self.hasFromUser) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.fromUser] forKey: @"fromUser"];
  }
  if (self.hasToUser) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.toUser] forKey: @"toUser"];
  }
  if (self.hasComment) {
    [dictionary setObject: self.comment forKey: @"comment"];
  }
  if (self.hasDataStatus) {
    [dictionary setObject: [NSNumber numberWithInteger:self.dataStatus] forKey: @"dataStatus"];
  }
  if (self.hasTimestamp) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.timestamp] forKey: @"timestamp"];
  }
  if (self.hasCreatedDate) {
    [dictionary setObject: [NSNumber numberWithLongLong:self.createdDate] forKey: @"createdDate"];
  }
  [self.unknownFields storeInDictionary:dictionary];
}
- (BOOL) isEqual:(id)other {
  if (other == self) {
    return YES;
  }
  if (![other isKindOfClass:[FscSnsCommentPb class]]) {
    return NO;
  }
  FscSnsCommentPb *otherMessage = other;
  return
      self.hasId == otherMessage.hasId &&
      (!self.hasId || self.id == otherMessage.id) &&
      self.hasMsgId == otherMessage.hasMsgId &&
      (!self.hasMsgId || self.msgId == otherMessage.msgId) &&
      self.hasFromUser == otherMessage.hasFromUser &&
      (!self.hasFromUser || self.fromUser == otherMessage.fromUser) &&
      self.hasToUser == otherMessage.hasToUser &&
      (!self.hasToUser || self.toUser == otherMessage.toUser) &&
      self.hasComment == otherMessage.hasComment &&
      (!self.hasComment || [self.comment isEqual:otherMessage.comment]) &&
      self.hasDataStatus == otherMessage.hasDataStatus &&
      (!self.hasDataStatus || self.dataStatus == otherMessage.dataStatus) &&
      self.hasTimestamp == otherMessage.hasTimestamp &&
      (!self.hasTimestamp || self.timestamp == otherMessage.timestamp) &&
      self.hasCreatedDate == otherMessage.hasCreatedDate &&
      (!self.hasCreatedDate || self.createdDate == otherMessage.createdDate) &&
      (self.unknownFields == otherMessage.unknownFields || (self.unknownFields != nil && [self.unknownFields isEqual:otherMessage.unknownFields]));
}
- (NSUInteger) hash {
  __block NSUInteger hashCode = 7;
  if (self.hasId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.id] hash];
  }
  if (self.hasMsgId) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.msgId] hash];
  }
  if (self.hasFromUser) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.fromUser] hash];
  }
  if (self.hasToUser) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.toUser] hash];
  }
  if (self.hasComment) {
    hashCode = hashCode * 31 + [self.comment hash];
  }
  if (self.hasDataStatus) {
    hashCode = hashCode * 31 + [[NSNumber numberWithInteger:self.dataStatus] hash];
  }
  if (self.hasTimestamp) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.timestamp] hash];
  }
  if (self.hasCreatedDate) {
    hashCode = hashCode * 31 + [[NSNumber numberWithLongLong:self.createdDate] hash];
  }
  hashCode = hashCode * 31 + [self.unknownFields hash];
  return hashCode;
}
@end

@interface FscSnsCommentPbBuilder()
@property (strong) FscSnsCommentPb* resultFscSnsCommentPb;
@end

@implementation FscSnsCommentPbBuilder
@synthesize resultFscSnsCommentPb;
- (instancetype) init {
  if ((self = [super init])) {
    self.resultFscSnsCommentPb = [[FscSnsCommentPb alloc] init];
  }
  return self;
}
- (PBGeneratedMessage*) internalGetResult {
  return resultFscSnsCommentPb;
}
- (FscSnsCommentPbBuilder*) clear {
  self.resultFscSnsCommentPb = [[FscSnsCommentPb alloc] init];
  return self;
}
- (FscSnsCommentPbBuilder*) clone {
  return [FscSnsCommentPb builderWithPrototype:resultFscSnsCommentPb];
}
- (FscSnsCommentPb*) defaultInstance {
  return [FscSnsCommentPb defaultInstance];
}
- (FscSnsCommentPb*) build {
  [self checkInitialized];
  return [self buildPartial];
}
- (FscSnsCommentPb*) buildPartial {
  FscSnsCommentPb* returnMe = resultFscSnsCommentPb;
  self.resultFscSnsCommentPb = nil;
  return returnMe;
}
- (FscSnsCommentPbBuilder*) mergeFrom:(FscSnsCommentPb*) other {
  if (other == [FscSnsCommentPb defaultInstance]) {
    return self;
  }
  if (other.hasId) {
    [self setId:other.id];
  }
  if (other.hasMsgId) {
    [self setMsgId:other.msgId];
  }
  if (other.hasFromUser) {
    [self setFromUser:other.fromUser];
  }
  if (other.hasToUser) {
    [self setToUser:other.toUser];
  }
  if (other.hasComment) {
    [self setComment:other.comment];
  }
  if (other.hasDataStatus) {
    [self setDataStatus:other.dataStatus];
  }
  if (other.hasTimestamp) {
    [self setTimestamp:other.timestamp];
  }
  if (other.hasCreatedDate) {
    [self setCreatedDate:other.createdDate];
  }
  [self mergeUnknownFields:other.unknownFields];
  return self;
}
- (FscSnsCommentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input {
  return [self mergeFromCodedInputStream:input extensionRegistry:[PBExtensionRegistry emptyRegistry]];
}
- (FscSnsCommentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry {
  PBUnknownFieldSetBuilder* unknownFields = [PBUnknownFieldSet builderWithUnknownFields:self.unknownFields];
  while (YES) {
    SInt32 tag = [input readTag];
    switch (tag) {
      case 0:
        [self setUnknownFields:[unknownFields build]];
        return self;
      default: {
        if (![self parseUnknownField:input unknownFields:unknownFields extensionRegistry:extensionRegistry tag:tag]) {
          [self setUnknownFields:[unknownFields build]];
          return self;
        }
        break;
      }
      case 8: {
        [self setId:[input readInt64]];
        break;
      }
      case 16: {
        [self setMsgId:[input readInt64]];
        break;
      }
      case 24: {
        [self setFromUser:[input readInt64]];
        break;
      }
      case 32: {
        [self setToUser:[input readInt64]];
        break;
      }
      case 42: {
        [self setComment:[input readString]];
        break;
      }
      case 48: {
        [self setDataStatus:[input readInt32]];
        break;
      }
      case 56: {
        [self setTimestamp:[input readInt64]];
        break;
      }
      case 64: {
        [self setCreatedDate:[input readInt64]];
        break;
      }
    }
  }
}
- (BOOL) hasId {
  return resultFscSnsCommentPb.hasId;
}
- (SInt64) id {
  return resultFscSnsCommentPb.id;
}
- (FscSnsCommentPbBuilder*) setId:(SInt64) value {
  resultFscSnsCommentPb.hasId = YES;
  resultFscSnsCommentPb.id = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearId {
  resultFscSnsCommentPb.hasId = NO;
  resultFscSnsCommentPb.id = 0L;
  return self;
}
- (BOOL) hasMsgId {
  return resultFscSnsCommentPb.hasMsgId;
}
- (SInt64) msgId {
  return resultFscSnsCommentPb.msgId;
}
- (FscSnsCommentPbBuilder*) setMsgId:(SInt64) value {
  resultFscSnsCommentPb.hasMsgId = YES;
  resultFscSnsCommentPb.msgId = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearMsgId {
  resultFscSnsCommentPb.hasMsgId = NO;
  resultFscSnsCommentPb.msgId = 0L;
  return self;
}
- (BOOL) hasFromUser {
  return resultFscSnsCommentPb.hasFromUser;
}
- (SInt64) fromUser {
  return resultFscSnsCommentPb.fromUser;
}
- (FscSnsCommentPbBuilder*) setFromUser:(SInt64) value {
  resultFscSnsCommentPb.hasFromUser = YES;
  resultFscSnsCommentPb.fromUser = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearFromUser {
  resultFscSnsCommentPb.hasFromUser = NO;
  resultFscSnsCommentPb.fromUser = 0L;
  return self;
}
- (BOOL) hasToUser {
  return resultFscSnsCommentPb.hasToUser;
}
- (SInt64) toUser {
  return resultFscSnsCommentPb.toUser;
}
- (FscSnsCommentPbBuilder*) setToUser:(SInt64) value {
  resultFscSnsCommentPb.hasToUser = YES;
  resultFscSnsCommentPb.toUser = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearToUser {
  resultFscSnsCommentPb.hasToUser = NO;
  resultFscSnsCommentPb.toUser = 0L;
  return self;
}
- (BOOL) hasComment {
  return resultFscSnsCommentPb.hasComment;
}
- (NSString*) comment {
  return resultFscSnsCommentPb.comment;
}
- (FscSnsCommentPbBuilder*) setComment:(NSString*) value {
  resultFscSnsCommentPb.hasComment = YES;
  resultFscSnsCommentPb.comment = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearComment {
  resultFscSnsCommentPb.hasComment = NO;
  resultFscSnsCommentPb.comment = @"";
  return self;
}
- (BOOL) hasDataStatus {
  return resultFscSnsCommentPb.hasDataStatus;
}
- (SInt32) dataStatus {
  return resultFscSnsCommentPb.dataStatus;
}
- (FscSnsCommentPbBuilder*) setDataStatus:(SInt32) value {
  resultFscSnsCommentPb.hasDataStatus = YES;
  resultFscSnsCommentPb.dataStatus = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearDataStatus {
  resultFscSnsCommentPb.hasDataStatus = NO;
  resultFscSnsCommentPb.dataStatus = 0;
  return self;
}
- (BOOL) hasTimestamp {
  return resultFscSnsCommentPb.hasTimestamp;
}
- (SInt64) timestamp {
  return resultFscSnsCommentPb.timestamp;
}
- (FscSnsCommentPbBuilder*) setTimestamp:(SInt64) value {
  resultFscSnsCommentPb.hasTimestamp = YES;
  resultFscSnsCommentPb.timestamp = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearTimestamp {
  resultFscSnsCommentPb.hasTimestamp = NO;
  resultFscSnsCommentPb.timestamp = 0L;
  return self;
}
- (BOOL) hasCreatedDate {
  return resultFscSnsCommentPb.hasCreatedDate;
}
- (SInt64) createdDate {
  return resultFscSnsCommentPb.createdDate;
}
- (FscSnsCommentPbBuilder*) setCreatedDate:(SInt64) value {
  resultFscSnsCommentPb.hasCreatedDate = YES;
  resultFscSnsCommentPb.createdDate = value;
  return self;
}
- (FscSnsCommentPbBuilder*) clearCreatedDate {
  resultFscSnsCommentPb.hasCreatedDate = NO;
  resultFscSnsCommentPb.createdDate = 0L;
  return self;
}
@end


// @@protoc_insertion_point(global_scope)
