// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "FscTeachNode.pb.h"
// @@protoc_insertion_point(imports)

@class TeachNodeContentPb;
@class TeachNodeContentPbBuilder;
@class TeachNodeDetailsPb;
@class TeachNodeDetailsPbBuilder;
@class TeachNodeListPb;
@class TeachNodeListPbBuilder;
@class TeachNodePb;
@class TeachNodePbBuilder;
@class TeachPlanImgPb;
@class TeachPlanImgPbBuilder;
@class TeachPlanNodePb;
@class TeachPlanNodePbBuilder;
@class TeachPlanPb;
@class TeachPlanPbBuilder;



@interface FscTeachPlanRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define TeachPlanPb_id @"id"
#define TeachPlanPb_planName @"planName"
@interface TeachPlanPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasPlanName_:1;
  SInt64 id;
  NSString* planName;
}
- (BOOL) hasId;
- (BOOL) hasPlanName;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* planName;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachPlanPbBuilder*) builder;
+ (TeachPlanPbBuilder*) builder;
+ (TeachPlanPbBuilder*) builderWithPrototype:(TeachPlanPb*) prototype;
- (TeachPlanPbBuilder*) toBuilder;

+ (TeachPlanPb*) parseFromData:(NSData*) data;
+ (TeachPlanPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachPlanPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachPlanPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachPlanPbBuilder : PBGeneratedMessageBuilder {
@private
  TeachPlanPb* resultTeachPlanPb;
}

- (TeachPlanPb*) defaultInstance;

- (TeachPlanPbBuilder*) clear;
- (TeachPlanPbBuilder*) clone;

- (TeachPlanPb*) build;
- (TeachPlanPb*) buildPartial;

- (TeachPlanPbBuilder*) mergeFrom:(TeachPlanPb*) other;
- (TeachPlanPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachPlanPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (TeachPlanPbBuilder*) setId:(SInt64) value;
- (TeachPlanPbBuilder*) clearId;

- (BOOL) hasPlanName;
- (NSString*) planName;
- (TeachPlanPbBuilder*) setPlanName:(NSString*) value;
- (TeachPlanPbBuilder*) clearPlanName;
@end

#define TeachPlanNodePb_id @"id"
#define TeachPlanNodePb_classIds @"classIds"
#define TeachPlanNodePb_nodeDate @"nodeDate"
#define TeachPlanNodePb_title @"title"
#define TeachPlanNodePb_nodeContentPb @"nodeContentPb"
#define TeachPlanNodePb_teachPlanImgPb @"teachPlanImgPb"
#define TeachPlanNodePb_teachPlanVoice @"teachPlanVoice"
#define TeachPlanNodePb_imgPath @"imgPath"
@interface TeachPlanNodePb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasNodeDate_:1;
  BOOL hasClassIds_:1;
  BOOL hasTitle_:1;
  BOOL hasImgPath_:1;
  BOOL hasTeachPlanVoice_:1;
  SInt64 id;
  SInt64 nodeDate;
  NSString* classIds;
  NSString* title;
  NSString* imgPath;
  NSData* teachPlanVoice;
  NSMutableArray * nodeContentPbArray;
  NSMutableArray * teachPlanImgPbArray;
}
- (BOOL) hasId;
- (BOOL) hasClassIds;
- (BOOL) hasNodeDate;
- (BOOL) hasTitle;
- (BOOL) hasTeachPlanVoice;
- (BOOL) hasImgPath;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* classIds;
@property (readonly) SInt64 nodeDate;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSArray * nodeContentPb;
@property (readonly, strong) NSArray * teachPlanImgPb;
@property (readonly, strong) NSData* teachPlanVoice;
@property (readonly, strong) NSString* imgPath;
- (TeachNodeContentPb*)nodeContentPbAtIndex:(NSUInteger)index;
- (TeachPlanImgPb*)teachPlanImgPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachPlanNodePbBuilder*) builder;
+ (TeachPlanNodePbBuilder*) builder;
+ (TeachPlanNodePbBuilder*) builderWithPrototype:(TeachPlanNodePb*) prototype;
- (TeachPlanNodePbBuilder*) toBuilder;

+ (TeachPlanNodePb*) parseFromData:(NSData*) data;
+ (TeachPlanNodePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanNodePb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachPlanNodePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanNodePb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachPlanNodePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachPlanNodePbBuilder : PBGeneratedMessageBuilder {
@private
  TeachPlanNodePb* resultTeachPlanNodePb;
}

- (TeachPlanNodePb*) defaultInstance;

- (TeachPlanNodePbBuilder*) clear;
- (TeachPlanNodePbBuilder*) clone;

- (TeachPlanNodePb*) build;
- (TeachPlanNodePb*) buildPartial;

- (TeachPlanNodePbBuilder*) mergeFrom:(TeachPlanNodePb*) other;
- (TeachPlanNodePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachPlanNodePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (TeachPlanNodePbBuilder*) setId:(SInt64) value;
- (TeachPlanNodePbBuilder*) clearId;

- (BOOL) hasClassIds;
- (NSString*) classIds;
- (TeachPlanNodePbBuilder*) setClassIds:(NSString*) value;
- (TeachPlanNodePbBuilder*) clearClassIds;

- (BOOL) hasNodeDate;
- (SInt64) nodeDate;
- (TeachPlanNodePbBuilder*) setNodeDate:(SInt64) value;
- (TeachPlanNodePbBuilder*) clearNodeDate;

- (BOOL) hasTitle;
- (NSString*) title;
- (TeachPlanNodePbBuilder*) setTitle:(NSString*) value;
- (TeachPlanNodePbBuilder*) clearTitle;

- (NSMutableArray *)nodeContentPb;
- (TeachNodeContentPb*)nodeContentPbAtIndex:(NSUInteger)index;
- (TeachPlanNodePbBuilder *)addNodeContentPb:(TeachNodeContentPb*)value;
- (TeachPlanNodePbBuilder *)setNodeContentPbArray:(NSArray *)array;
- (TeachPlanNodePbBuilder *)clearNodeContentPb;

- (NSMutableArray *)teachPlanImgPb;
- (TeachPlanImgPb*)teachPlanImgPbAtIndex:(NSUInteger)index;
- (TeachPlanNodePbBuilder *)addTeachPlanImgPb:(TeachPlanImgPb*)value;
- (TeachPlanNodePbBuilder *)setTeachPlanImgPbArray:(NSArray *)array;
- (TeachPlanNodePbBuilder *)clearTeachPlanImgPb;

- (BOOL) hasTeachPlanVoice;
- (NSData*) teachPlanVoice;
- (TeachPlanNodePbBuilder*) setTeachPlanVoice:(NSData*) value;
- (TeachPlanNodePbBuilder*) clearTeachPlanVoice;

- (BOOL) hasImgPath;
- (NSString*) imgPath;
- (TeachPlanNodePbBuilder*) setImgPath:(NSString*) value;
- (TeachPlanNodePbBuilder*) clearImgPath;
@end

#define TeachPlanImgPb_imgByte @"imgByte"
@interface TeachPlanImgPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasImgByte_:1;
  NSData* imgByte;
}
- (BOOL) hasImgByte;
@property (readonly, strong) NSData* imgByte;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachPlanImgPbBuilder*) builder;
+ (TeachPlanImgPbBuilder*) builder;
+ (TeachPlanImgPbBuilder*) builderWithPrototype:(TeachPlanImgPb*) prototype;
- (TeachPlanImgPbBuilder*) toBuilder;

+ (TeachPlanImgPb*) parseFromData:(NSData*) data;
+ (TeachPlanImgPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanImgPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachPlanImgPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachPlanImgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachPlanImgPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachPlanImgPbBuilder : PBGeneratedMessageBuilder {
@private
  TeachPlanImgPb* resultTeachPlanImgPb;
}

- (TeachPlanImgPb*) defaultInstance;

- (TeachPlanImgPbBuilder*) clear;
- (TeachPlanImgPbBuilder*) clone;

- (TeachPlanImgPb*) build;
- (TeachPlanImgPb*) buildPartial;

- (TeachPlanImgPbBuilder*) mergeFrom:(TeachPlanImgPb*) other;
- (TeachPlanImgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachPlanImgPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasImgByte;
- (NSData*) imgByte;
- (TeachPlanImgPbBuilder*) setImgByte:(NSData*) value;
- (TeachPlanImgPbBuilder*) clearImgByte;
@end


// @@protoc_insertion_point(global_scope)
