// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FscTeacherListPb;
@class FscTeacherListPbBuilder;
@class FscTeacherPb;
@class FscTeacherPbBuilder;



@interface FscTeacherRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FscTeacherListPb_teacherPb @"teacherPb"
@interface FscTeacherListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * teacherPbArray;
}
@property (readonly, strong) NSArray * teacherPb;
- (FscTeacherPb*)teacherPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscTeacherListPbBuilder*) builder;
+ (FscTeacherListPbBuilder*) builder;
+ (FscTeacherListPbBuilder*) builderWithPrototype:(FscTeacherListPb*) prototype;
- (FscTeacherListPbBuilder*) toBuilder;

+ (FscTeacherListPb*) parseFromData:(NSData*) data;
+ (FscTeacherListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscTeacherListPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscTeacherListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscTeacherListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscTeacherListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscTeacherListPbBuilder : PBGeneratedMessageBuilder {
@private
  FscTeacherListPb* resultFscTeacherListPb;
}

- (FscTeacherListPb*) defaultInstance;

- (FscTeacherListPbBuilder*) clear;
- (FscTeacherListPbBuilder*) clone;

- (FscTeacherListPb*) build;
- (FscTeacherListPb*) buildPartial;

- (FscTeacherListPbBuilder*) mergeFrom:(FscTeacherListPb*) other;
- (FscTeacherListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscTeacherListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)teacherPb;
- (FscTeacherPb*)teacherPbAtIndex:(NSUInteger)index;
- (FscTeacherListPbBuilder *)addTeacherPb:(FscTeacherPb*)value;
- (FscTeacherListPbBuilder *)setTeacherPbArray:(NSArray *)array;
- (FscTeacherListPbBuilder *)clearTeacherPb;
@end

#define FscTeacherPb_id @"id"
#define FscTeacherPb_name @"name"
#define FscTeacherPb_portrait @"portrait"
#define FscTeacherPb_gender @"gender"
#define FscTeacherPb_subjectId @"subjectId"
#define FscTeacherPb_mobile @"mobile"
#define FscTeacherPb_dataStatus @"dataStatus"
#define FscTeacherPb_modifiedDate @"modifiedDate"
@interface FscTeacherPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSubjectId_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasGender_:1;
  BOOL hasDataStatus_:1;
  BOOL hasName_:1;
  BOOL hasPortrait_:1;
  BOOL hasMobile_:1;
  SInt64 id;
  SInt64 subjectId;
  SInt64 modifiedDate;
  SInt32 gender;
  SInt32 dataStatus;
  NSString* name;
  NSString* portrait;
  NSString* mobile;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasPortrait;
- (BOOL) hasGender;
- (BOOL) hasSubjectId;
- (BOOL) hasMobile;
- (BOOL) hasDataStatus;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly, strong) NSString* portrait;
@property (readonly) SInt32 gender;
@property (readonly) SInt64 subjectId;
@property (readonly, strong) NSString* mobile;
@property (readonly) SInt32 dataStatus;
@property (readonly) SInt64 modifiedDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscTeacherPbBuilder*) builder;
+ (FscTeacherPbBuilder*) builder;
+ (FscTeacherPbBuilder*) builderWithPrototype:(FscTeacherPb*) prototype;
- (FscTeacherPbBuilder*) toBuilder;

+ (FscTeacherPb*) parseFromData:(NSData*) data;
+ (FscTeacherPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscTeacherPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscTeacherPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscTeacherPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscTeacherPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscTeacherPbBuilder : PBGeneratedMessageBuilder {
@private
  FscTeacherPb* resultFscTeacherPb;
}

- (FscTeacherPb*) defaultInstance;

- (FscTeacherPbBuilder*) clear;
- (FscTeacherPbBuilder*) clone;

- (FscTeacherPb*) build;
- (FscTeacherPb*) buildPartial;

- (FscTeacherPbBuilder*) mergeFrom:(FscTeacherPb*) other;
- (FscTeacherPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscTeacherPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscTeacherPbBuilder*) setId:(SInt64) value;
- (FscTeacherPbBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (FscTeacherPbBuilder*) setName:(NSString*) value;
- (FscTeacherPbBuilder*) clearName;

- (BOOL) hasPortrait;
- (NSString*) portrait;
- (FscTeacherPbBuilder*) setPortrait:(NSString*) value;
- (FscTeacherPbBuilder*) clearPortrait;

- (BOOL) hasGender;
- (SInt32) gender;
- (FscTeacherPbBuilder*) setGender:(SInt32) value;
- (FscTeacherPbBuilder*) clearGender;

- (BOOL) hasSubjectId;
- (SInt64) subjectId;
- (FscTeacherPbBuilder*) setSubjectId:(SInt64) value;
- (FscTeacherPbBuilder*) clearSubjectId;

- (BOOL) hasMobile;
- (NSString*) mobile;
- (FscTeacherPbBuilder*) setMobile:(NSString*) value;
- (FscTeacherPbBuilder*) clearMobile;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (FscTeacherPbBuilder*) setDataStatus:(SInt32) value;
- (FscTeacherPbBuilder*) clearDataStatus;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (FscTeacherPbBuilder*) setModifiedDate:(SInt64) value;
- (FscTeacherPbBuilder*) clearModifiedDate;
@end


// @@protoc_insertion_point(global_scope)
