// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class TeachNodeContentPb;
@class TeachNodeContentPbBuilder;
@class TeachNodeDetailsPb;
@class TeachNodeDetailsPbBuilder;
@class TeachNodeListPb;
@class TeachNodeListPbBuilder;
@class TeachNodePb;
@class TeachNodePbBuilder;



@interface FscTeachNodeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define TeachNodeListPb_teachNode @"teachNode"
#define TeachNodeListPb_teachNodeDetails @"teachNodeDetails"
#define TeachNodeListPb_teachNodeContent @"teachNodeContent"
@interface TeachNodeListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * teachNodeArray;
  NSMutableArray * teachNodeDetailsArray;
  NSMutableArray * teachNodeContentArray;
}
@property (readonly, strong) NSArray * teachNode;
@property (readonly, strong) NSArray * teachNodeDetails;
@property (readonly, strong) NSArray * teachNodeContent;
- (TeachNodePb*)teachNodeAtIndex:(NSUInteger)index;
- (TeachNodeDetailsPb*)teachNodeDetailsAtIndex:(NSUInteger)index;
- (TeachNodeContentPb*)teachNodeContentAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachNodeListPbBuilder*) builder;
+ (TeachNodeListPbBuilder*) builder;
+ (TeachNodeListPbBuilder*) builderWithPrototype:(TeachNodeListPb*) prototype;
- (TeachNodeListPbBuilder*) toBuilder;

+ (TeachNodeListPb*) parseFromData:(NSData*) data;
+ (TeachNodeListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeListPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachNodeListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachNodeListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachNodeListPbBuilder : PBGeneratedMessageBuilder {
@private
  TeachNodeListPb* resultTeachNodeListPb;
}

- (TeachNodeListPb*) defaultInstance;

- (TeachNodeListPbBuilder*) clear;
- (TeachNodeListPbBuilder*) clone;

- (TeachNodeListPb*) build;
- (TeachNodeListPb*) buildPartial;

- (TeachNodeListPbBuilder*) mergeFrom:(TeachNodeListPb*) other;
- (TeachNodeListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachNodeListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)teachNode;
- (TeachNodePb*)teachNodeAtIndex:(NSUInteger)index;
- (TeachNodeListPbBuilder *)addTeachNode:(TeachNodePb*)value;
- (TeachNodeListPbBuilder *)setTeachNodeArray:(NSArray *)array;
- (TeachNodeListPbBuilder *)clearTeachNode;

- (NSMutableArray *)teachNodeDetails;
- (TeachNodeDetailsPb*)teachNodeDetailsAtIndex:(NSUInteger)index;
- (TeachNodeListPbBuilder *)addTeachNodeDetails:(TeachNodeDetailsPb*)value;
- (TeachNodeListPbBuilder *)setTeachNodeDetailsArray:(NSArray *)array;
- (TeachNodeListPbBuilder *)clearTeachNodeDetails;

- (NSMutableArray *)teachNodeContent;
- (TeachNodeContentPb*)teachNodeContentAtIndex:(NSUInteger)index;
- (TeachNodeListPbBuilder *)addTeachNodeContent:(TeachNodeContentPb*)value;
- (TeachNodeListPbBuilder *)setTeachNodeContentArray:(NSArray *)array;
- (TeachNodeListPbBuilder *)clearTeachNodeContent;
@end

#define TeachNodePb_id @"id"
#define TeachNodePb_schoolId @"schoolId"
#define TeachNodePb_subjectId @"subjectId"
#define TeachNodePb_name @"name"
#define TeachNodePb_step @"step"
#define TeachNodePb_type @"type"
#define TeachNodePb_resId @"resId"
#define TeachNodePb_nodeTime @"nodeTime"
#define TeachNodePb_modifiedDate @"modifiedDate"
#define TeachNodePb_studentId @"studentId"
#define TeachNodePb_teacherName @"teacherName"
#define TeachNodePb_nodeStatus @"nodeStatus"
#define TeachNodePb_score @"score"
#define TeachNodePb_dataStatus @"dataStatus"
#define TeachNodePb_imgText @"imgText"
#define TeachNodePb_classIds @"classIds"
#define TeachNodePb_correctCount @"correctCount"
#define TeachNodePb_submitCount @"submitCount"
#define TeachNodePb_total @"total"
#define TeachNodePb_isRead @"isRead"
#define TeachNodePb_isFinish @"isFinish"
#define TeachNodePb_picture @"picture"
#define TeachNodePb_voice @"voice"
#define TeachNodePb_file @"file"
@interface TeachNodePb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSchoolId_:1;
  BOOL hasSubjectId_:1;
  BOOL hasResId_:1;
  BOOL hasNodeTime_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasStudentId_:1;
  BOOL hasCorrectCount_:1;
  BOOL hasSubmitCount_:1;
  BOOL hasTotal_:1;
  BOOL hasStep_:1;
  BOOL hasType_:1;
  BOOL hasScore_:1;
  BOOL hasDataStatus_:1;
  BOOL hasIsRead_:1;
  BOOL hasIsFinish_:1;
  BOOL hasName_:1;
  BOOL hasTeacherName_:1;
  BOOL hasNodeStatus_:1;
  BOOL hasImgText_:1;
  BOOL hasClassIds_:1;
  BOOL hasPicture_:1;
  BOOL hasVoice_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 schoolId;
  SInt64 subjectId;
  SInt64 resId;
  SInt64 nodeTime;
  SInt64 modifiedDate;
  SInt64 studentId;
  SInt64 correctCount;
  SInt64 submitCount;
  SInt64 total;
  SInt32 step;
  SInt32 type;
  SInt32 score;
  SInt32 dataStatus;
  SInt32 isRead;
  SInt32 isFinish;
  NSString* name;
  NSString* teacherName;
  NSString* nodeStatus;
  NSString* imgText;
  NSString* classIds;
  NSString* picture;
  NSString* voice;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasSchoolId;
- (BOOL) hasSubjectId;
- (BOOL) hasName;
- (BOOL) hasStep;
- (BOOL) hasType;
- (BOOL) hasResId;
- (BOOL) hasNodeTime;
- (BOOL) hasModifiedDate;
- (BOOL) hasStudentId;
- (BOOL) hasTeacherName;
- (BOOL) hasNodeStatus;
- (BOOL) hasScore;
- (BOOL) hasDataStatus;
- (BOOL) hasImgText;
- (BOOL) hasClassIds;
- (BOOL) hasCorrectCount;
- (BOOL) hasSubmitCount;
- (BOOL) hasTotal;
- (BOOL) hasIsRead;
- (BOOL) hasIsFinish;
- (BOOL) hasPicture;
- (BOOL) hasVoice;
- (BOOL) hasFile;
@property (readonly) SInt64 id;
@property (readonly) SInt64 schoolId;
@property (readonly) SInt64 subjectId;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 step;
@property (readonly) SInt32 type;
@property (readonly) SInt64 resId;
@property (readonly) SInt64 nodeTime;
@property (readonly) SInt64 modifiedDate;
@property (readonly) SInt64 studentId;
@property (readonly, strong) NSString* teacherName;
@property (readonly, strong) NSString* nodeStatus;
@property (readonly) SInt32 score;
@property (readonly) SInt32 dataStatus;
@property (readonly, strong) NSString* imgText;
@property (readonly, strong) NSString* classIds;
@property (readonly) SInt64 correctCount;
@property (readonly) SInt64 submitCount;
@property (readonly) SInt64 total;
@property (readonly) SInt32 isRead;
@property (readonly) SInt32 isFinish;
@property (readonly, strong) NSString* picture;
@property (readonly, strong) NSString* voice;
@property (readonly, strong) NSData* file;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachNodePbBuilder*) builder;
+ (TeachNodePbBuilder*) builder;
+ (TeachNodePbBuilder*) builderWithPrototype:(TeachNodePb*) prototype;
- (TeachNodePbBuilder*) toBuilder;

+ (TeachNodePb*) parseFromData:(NSData*) data;
+ (TeachNodePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodePb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachNodePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodePb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachNodePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachNodePbBuilder : PBGeneratedMessageBuilder {
@private
  TeachNodePb* resultTeachNodePb;
}

- (TeachNodePb*) defaultInstance;

- (TeachNodePbBuilder*) clear;
- (TeachNodePbBuilder*) clone;

- (TeachNodePb*) build;
- (TeachNodePb*) buildPartial;

- (TeachNodePbBuilder*) mergeFrom:(TeachNodePb*) other;
- (TeachNodePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachNodePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (TeachNodePbBuilder*) setId:(SInt64) value;
- (TeachNodePbBuilder*) clearId;

- (BOOL) hasSchoolId;
- (SInt64) schoolId;
- (TeachNodePbBuilder*) setSchoolId:(SInt64) value;
- (TeachNodePbBuilder*) clearSchoolId;

- (BOOL) hasSubjectId;
- (SInt64) subjectId;
- (TeachNodePbBuilder*) setSubjectId:(SInt64) value;
- (TeachNodePbBuilder*) clearSubjectId;

- (BOOL) hasName;
- (NSString*) name;
- (TeachNodePbBuilder*) setName:(NSString*) value;
- (TeachNodePbBuilder*) clearName;

- (BOOL) hasStep;
- (SInt32) step;
- (TeachNodePbBuilder*) setStep:(SInt32) value;
- (TeachNodePbBuilder*) clearStep;

- (BOOL) hasType;
- (SInt32) type;
- (TeachNodePbBuilder*) setType:(SInt32) value;
- (TeachNodePbBuilder*) clearType;

- (BOOL) hasResId;
- (SInt64) resId;
- (TeachNodePbBuilder*) setResId:(SInt64) value;
- (TeachNodePbBuilder*) clearResId;

- (BOOL) hasNodeTime;
- (SInt64) nodeTime;
- (TeachNodePbBuilder*) setNodeTime:(SInt64) value;
- (TeachNodePbBuilder*) clearNodeTime;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (TeachNodePbBuilder*) setModifiedDate:(SInt64) value;
- (TeachNodePbBuilder*) clearModifiedDate;

- (BOOL) hasStudentId;
- (SInt64) studentId;
- (TeachNodePbBuilder*) setStudentId:(SInt64) value;
- (TeachNodePbBuilder*) clearStudentId;

- (BOOL) hasTeacherName;
- (NSString*) teacherName;
- (TeachNodePbBuilder*) setTeacherName:(NSString*) value;
- (TeachNodePbBuilder*) clearTeacherName;

- (BOOL) hasNodeStatus;
- (NSString*) nodeStatus;
- (TeachNodePbBuilder*) setNodeStatus:(NSString*) value;
- (TeachNodePbBuilder*) clearNodeStatus;

- (BOOL) hasScore;
- (SInt32) score;
- (TeachNodePbBuilder*) setScore:(SInt32) value;
- (TeachNodePbBuilder*) clearScore;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (TeachNodePbBuilder*) setDataStatus:(SInt32) value;
- (TeachNodePbBuilder*) clearDataStatus;

- (BOOL) hasImgText;
- (NSString*) imgText;
- (TeachNodePbBuilder*) setImgText:(NSString*) value;
- (TeachNodePbBuilder*) clearImgText;

- (BOOL) hasClassIds;
- (NSString*) classIds;
- (TeachNodePbBuilder*) setClassIds:(NSString*) value;
- (TeachNodePbBuilder*) clearClassIds;

- (BOOL) hasCorrectCount;
- (SInt64) correctCount;
- (TeachNodePbBuilder*) setCorrectCount:(SInt64) value;
- (TeachNodePbBuilder*) clearCorrectCount;

- (BOOL) hasSubmitCount;
- (SInt64) submitCount;
- (TeachNodePbBuilder*) setSubmitCount:(SInt64) value;
- (TeachNodePbBuilder*) clearSubmitCount;

- (BOOL) hasTotal;
- (SInt64) total;
- (TeachNodePbBuilder*) setTotal:(SInt64) value;
- (TeachNodePbBuilder*) clearTotal;

- (BOOL) hasIsRead;
- (SInt32) isRead;
- (TeachNodePbBuilder*) setIsRead:(SInt32) value;
- (TeachNodePbBuilder*) clearIsRead;

- (BOOL) hasIsFinish;
- (SInt32) isFinish;
- (TeachNodePbBuilder*) setIsFinish:(SInt32) value;
- (TeachNodePbBuilder*) clearIsFinish;

- (BOOL) hasPicture;
- (NSString*) picture;
- (TeachNodePbBuilder*) setPicture:(NSString*) value;
- (TeachNodePbBuilder*) clearPicture;

- (BOOL) hasVoice;
- (NSString*) voice;
- (TeachNodePbBuilder*) setVoice:(NSString*) value;
- (TeachNodePbBuilder*) clearVoice;

- (BOOL) hasFile;
- (NSData*) file;
- (TeachNodePbBuilder*) setFile:(NSData*) value;
- (TeachNodePbBuilder*) clearFile;
@end

#define TeachNodeDetailsPb_planNodeId @"planNodeId"
#define TeachNodeDetailsPb_classId @"classId"
#define TeachNodeDetailsPb_studentId @"studentId"
#define TeachNodeDetailsPb_studentName @"studentName"
#define TeachNodeDetailsPb_totalScore @"totalScore"
#define TeachNodeDetailsPb_isRead @"isRead"
#define TeachNodeDetailsPb_isSubmit @"isSubmit"
#define TeachNodeDetailsPb_isCorrect @"isCorrect"
#define TeachNodeDetailsPb_isFinish @"isFinish"
#define TeachNodeDetailsPb_modifiedDate @"modifiedDate"
@interface TeachNodeDetailsPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasPlanNodeId_:1;
  BOOL hasClassId_:1;
  BOOL hasStudentId_:1;
  BOOL hasTotalScore_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasIsRead_:1;
  BOOL hasIsSubmit_:1;
  BOOL hasIsCorrect_:1;
  BOOL hasIsFinish_:1;
  BOOL hasStudentName_:1;
  SInt64 planNodeId;
  SInt64 classId;
  SInt64 studentId;
  SInt64 totalScore;
  SInt64 modifiedDate;
  SInt32 isRead;
  SInt32 isSubmit;
  SInt32 isCorrect;
  SInt32 isFinish;
  NSString* studentName;
}
- (BOOL) hasPlanNodeId;
- (BOOL) hasClassId;
- (BOOL) hasStudentId;
- (BOOL) hasStudentName;
- (BOOL) hasTotalScore;
- (BOOL) hasIsRead;
- (BOOL) hasIsSubmit;
- (BOOL) hasIsCorrect;
- (BOOL) hasIsFinish;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 planNodeId;
@property (readonly) SInt64 classId;
@property (readonly) SInt64 studentId;
@property (readonly, strong) NSString* studentName;
@property (readonly) SInt64 totalScore;
@property (readonly) SInt32 isRead;
@property (readonly) SInt32 isSubmit;
@property (readonly) SInt32 isCorrect;
@property (readonly) SInt32 isFinish;
@property (readonly) SInt64 modifiedDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachNodeDetailsPbBuilder*) builder;
+ (TeachNodeDetailsPbBuilder*) builder;
+ (TeachNodeDetailsPbBuilder*) builderWithPrototype:(TeachNodeDetailsPb*) prototype;
- (TeachNodeDetailsPbBuilder*) toBuilder;

+ (TeachNodeDetailsPb*) parseFromData:(NSData*) data;
+ (TeachNodeDetailsPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeDetailsPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachNodeDetailsPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeDetailsPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachNodeDetailsPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachNodeDetailsPbBuilder : PBGeneratedMessageBuilder {
@private
  TeachNodeDetailsPb* resultTeachNodeDetailsPb;
}

- (TeachNodeDetailsPb*) defaultInstance;

- (TeachNodeDetailsPbBuilder*) clear;
- (TeachNodeDetailsPbBuilder*) clone;

- (TeachNodeDetailsPb*) build;
- (TeachNodeDetailsPb*) buildPartial;

- (TeachNodeDetailsPbBuilder*) mergeFrom:(TeachNodeDetailsPb*) other;
- (TeachNodeDetailsPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachNodeDetailsPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasPlanNodeId;
- (SInt64) planNodeId;
- (TeachNodeDetailsPbBuilder*) setPlanNodeId:(SInt64) value;
- (TeachNodeDetailsPbBuilder*) clearPlanNodeId;

- (BOOL) hasClassId;
- (SInt64) classId;
- (TeachNodeDetailsPbBuilder*) setClassId:(SInt64) value;
- (TeachNodeDetailsPbBuilder*) clearClassId;

- (BOOL) hasStudentId;
- (SInt64) studentId;
- (TeachNodeDetailsPbBuilder*) setStudentId:(SInt64) value;
- (TeachNodeDetailsPbBuilder*) clearStudentId;

- (BOOL) hasStudentName;
- (NSString*) studentName;
- (TeachNodeDetailsPbBuilder*) setStudentName:(NSString*) value;
- (TeachNodeDetailsPbBuilder*) clearStudentName;

- (BOOL) hasTotalScore;
- (SInt64) totalScore;
- (TeachNodeDetailsPbBuilder*) setTotalScore:(SInt64) value;
- (TeachNodeDetailsPbBuilder*) clearTotalScore;

- (BOOL) hasIsRead;
- (SInt32) isRead;
- (TeachNodeDetailsPbBuilder*) setIsRead:(SInt32) value;
- (TeachNodeDetailsPbBuilder*) clearIsRead;

- (BOOL) hasIsSubmit;
- (SInt32) isSubmit;
- (TeachNodeDetailsPbBuilder*) setIsSubmit:(SInt32) value;
- (TeachNodeDetailsPbBuilder*) clearIsSubmit;

- (BOOL) hasIsCorrect;
- (SInt32) isCorrect;
- (TeachNodeDetailsPbBuilder*) setIsCorrect:(SInt32) value;
- (TeachNodeDetailsPbBuilder*) clearIsCorrect;

- (BOOL) hasIsFinish;
- (SInt32) isFinish;
- (TeachNodeDetailsPbBuilder*) setIsFinish:(SInt32) value;
- (TeachNodeDetailsPbBuilder*) clearIsFinish;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (TeachNodeDetailsPbBuilder*) setModifiedDate:(SInt64) value;
- (TeachNodeDetailsPbBuilder*) clearModifiedDate;
@end

#define TeachNodeContentPb_id @"id"
#define TeachNodeContentPb_nodeId @"nodeId"
#define TeachNodeContentPb_content @"content"
#define TeachNodeContentPb_dataStatus @"dataStatus"
#define TeachNodeContentPb_modifiedDate @"modifiedDate"
@interface TeachNodeContentPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasNodeId_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasDataStatus_:1;
  BOOL hasContent_:1;
  SInt64 id;
  SInt64 nodeId;
  SInt64 modifiedDate;
  SInt32 dataStatus;
  NSString* content;
}
- (BOOL) hasId;
- (BOOL) hasNodeId;
- (BOOL) hasContent;
- (BOOL) hasDataStatus;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 id;
@property (readonly) SInt64 nodeId;
@property (readonly, strong) NSString* content;
@property (readonly) SInt32 dataStatus;
@property (readonly) SInt64 modifiedDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeachNodeContentPbBuilder*) builder;
+ (TeachNodeContentPbBuilder*) builder;
+ (TeachNodeContentPbBuilder*) builderWithPrototype:(TeachNodeContentPb*) prototype;
- (TeachNodeContentPbBuilder*) toBuilder;

+ (TeachNodeContentPb*) parseFromData:(NSData*) data;
+ (TeachNodeContentPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeContentPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeachNodeContentPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeachNodeContentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeachNodeContentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeachNodeContentPbBuilder : PBGeneratedMessageBuilder {
@private
  TeachNodeContentPb* resultTeachNodeContentPb;
}

- (TeachNodeContentPb*) defaultInstance;

- (TeachNodeContentPbBuilder*) clear;
- (TeachNodeContentPbBuilder*) clone;

- (TeachNodeContentPb*) build;
- (TeachNodeContentPb*) buildPartial;

- (TeachNodeContentPbBuilder*) mergeFrom:(TeachNodeContentPb*) other;
- (TeachNodeContentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeachNodeContentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (TeachNodeContentPbBuilder*) setId:(SInt64) value;
- (TeachNodeContentPbBuilder*) clearId;

- (BOOL) hasNodeId;
- (SInt64) nodeId;
- (TeachNodeContentPbBuilder*) setNodeId:(SInt64) value;
- (TeachNodeContentPbBuilder*) clearNodeId;

- (BOOL) hasContent;
- (NSString*) content;
- (TeachNodeContentPbBuilder*) setContent:(NSString*) value;
- (TeachNodeContentPbBuilder*) clearContent;

- (BOOL) hasDataStatus;
- (SInt32) dataStatus;
- (TeachNodeContentPbBuilder*) setDataStatus:(SInt32) value;
- (TeachNodeContentPbBuilder*) clearDataStatus;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (TeachNodeContentPbBuilder*) setModifiedDate:(SInt64) value;
- (TeachNodeContentPbBuilder*) clearModifiedDate;
@end


// @@protoc_insertion_point(global_scope)
