// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "FscSession.pb.h"
// @@protoc_insertion_point(imports)

@class FscSessionPb;
@class FscSessionPbBuilder;
@class GRecorderListPb;
@class GRecorderListPbBuilder;
@class GRecorderPb;
@class GRecorderPbBuilder;
@class GSessionPb;
@class GSessionPbBuilder;
@class GUserPb;
@class GUserPbBuilder;
@class URecorderListPb;
@class URecorderListPbBuilder;
@class URecorderPb;
@class URecorderPbBuilder;
@class USessionPb;
@class USessionPbBuilder;



@interface FscChatGroupRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define GRecorderListPb_recorderPb @"recorderPb"
@interface GRecorderListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * recorderPbArray;
}
@property (readonly, strong) NSArray * recorderPb;
- (GRecorderPb*)recorderPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GRecorderListPbBuilder*) builder;
+ (GRecorderListPbBuilder*) builder;
+ (GRecorderListPbBuilder*) builderWithPrototype:(GRecorderListPb*) prototype;
- (GRecorderListPbBuilder*) toBuilder;

+ (GRecorderListPb*) parseFromData:(NSData*) data;
+ (GRecorderListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GRecorderListPb*) parseFromInputStream:(NSInputStream*) input;
+ (GRecorderListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GRecorderListPbBuilder : PBGeneratedMessageBuilder {
@private
  GRecorderListPb* resultGrecorderListPb;
}

- (GRecorderListPb*) defaultInstance;

- (GRecorderListPbBuilder*) clear;
- (GRecorderListPbBuilder*) clone;

- (GRecorderListPb*) build;
- (GRecorderListPb*) buildPartial;

- (GRecorderListPbBuilder*) mergeFrom:(GRecorderListPb*) other;
- (GRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)recorderPb;
- (GRecorderPb*)recorderPbAtIndex:(NSUInteger)index;
- (GRecorderListPbBuilder *)addRecorderPb:(GRecorderPb*)value;
- (GRecorderListPbBuilder *)setRecorderPbArray:(NSArray *)array;
- (GRecorderListPbBuilder *)clearRecorderPb;
@end

#define GSessionPb_id @"id"
#define GSessionPb_uuid @"uuid"
#define GSessionPb_name @"name"
#define GSessionPb_nameStatus @"nameStatus"
#define GSessionPb_leaderId @"leaderId"
#define GSessionPb_portrait @"portrait"
#define GSessionPb_createdDate @"createdDate"
#define GSessionPb_timestamp @"timestamp"
#define GSessionPb_user @"user"
#define GSessionPb_fscSession @"fscSession"
#define GSessionPb_file @"file"
@interface GSessionPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasLeaderId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasNameStatus_:1;
  BOOL hasUuid_:1;
  BOOL hasName_:1;
  BOOL hasPortrait_:1;
  BOOL hasFscSession_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 leaderId;
  SInt64 createdDate;
  SInt64 timestamp;
  SInt32 nameStatus;
  NSString* uuid;
  NSString* name;
  NSString* portrait;
  FscSessionPb* fscSession;
  NSData* file;
  NSMutableArray * userArray;
}
- (BOOL) hasId;
- (BOOL) hasUuid;
- (BOOL) hasName;
- (BOOL) hasNameStatus;
- (BOOL) hasLeaderId;
- (BOOL) hasPortrait;
- (BOOL) hasCreatedDate;
- (BOOL) hasTimestamp;
- (BOOL) hasFscSession;
- (BOOL) hasFile;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 nameStatus;
@property (readonly) SInt64 leaderId;
@property (readonly, strong) NSString* portrait;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 timestamp;
@property (readonly, strong) NSArray * user;
@property (readonly, strong) FscSessionPb* fscSession;
@property (readonly, strong) NSData* file;
- (GUserPb*)userAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GSessionPbBuilder*) builder;
+ (GSessionPbBuilder*) builder;
+ (GSessionPbBuilder*) builderWithPrototype:(GSessionPb*) prototype;
- (GSessionPbBuilder*) toBuilder;

+ (GSessionPb*) parseFromData:(NSData*) data;
+ (GSessionPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GSessionPb*) parseFromInputStream:(NSInputStream*) input;
+ (GSessionPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GSessionPbBuilder : PBGeneratedMessageBuilder {
@private
  GSessionPb* resultGsessionPb;
}

- (GSessionPb*) defaultInstance;

- (GSessionPbBuilder*) clear;
- (GSessionPbBuilder*) clone;

- (GSessionPb*) build;
- (GSessionPb*) buildPartial;

- (GSessionPbBuilder*) mergeFrom:(GSessionPb*) other;
- (GSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (GSessionPbBuilder*) setId:(SInt64) value;
- (GSessionPbBuilder*) clearId;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (GSessionPbBuilder*) setUuid:(NSString*) value;
- (GSessionPbBuilder*) clearUuid;

- (BOOL) hasName;
- (NSString*) name;
- (GSessionPbBuilder*) setName:(NSString*) value;
- (GSessionPbBuilder*) clearName;

- (BOOL) hasNameStatus;
- (SInt32) nameStatus;
- (GSessionPbBuilder*) setNameStatus:(SInt32) value;
- (GSessionPbBuilder*) clearNameStatus;

- (BOOL) hasLeaderId;
- (SInt64) leaderId;
- (GSessionPbBuilder*) setLeaderId:(SInt64) value;
- (GSessionPbBuilder*) clearLeaderId;

- (BOOL) hasPortrait;
- (NSString*) portrait;
- (GSessionPbBuilder*) setPortrait:(NSString*) value;
- (GSessionPbBuilder*) clearPortrait;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (GSessionPbBuilder*) setCreatedDate:(SInt64) value;
- (GSessionPbBuilder*) clearCreatedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (GSessionPbBuilder*) setTimestamp:(SInt64) value;
- (GSessionPbBuilder*) clearTimestamp;

- (NSMutableArray *)user;
- (GUserPb*)userAtIndex:(NSUInteger)index;
- (GSessionPbBuilder *)addUser:(GUserPb*)value;
- (GSessionPbBuilder *)setUserArray:(NSArray *)array;
- (GSessionPbBuilder *)clearUser;

- (BOOL) hasFscSession;
- (FscSessionPb*) fscSession;
- (GSessionPbBuilder*) setFscSession:(FscSessionPb*) value;
- (GSessionPbBuilder*) setFscSessionBuilder:(FscSessionPbBuilder*) builderForValue;
- (GSessionPbBuilder*) mergeFscSession:(FscSessionPb*) value;
- (GSessionPbBuilder*) clearFscSession;

- (BOOL) hasFile;
- (NSData*) file;
- (GSessionPbBuilder*) setFile:(NSData*) value;
- (GSessionPbBuilder*) clearFile;
@end

#define GUserPb_sessionId @"sessionId"
#define GUserPb_userId @"userId"
#define GUserPb_inviterId @"inviterId"
#define GUserPb_status @"status"
#define GUserPb_createdDate @"createdDate"
#define GUserPb_modifiedDate @"modifiedDate"
#define GUserPb_timestamp @"timestamp"
@interface GUserPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSessionId_:1;
  BOOL hasUserId_:1;
  BOOL hasInviterId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasStatus_:1;
  SInt64 sessionId;
  SInt64 userId;
  SInt64 inviterId;
  SInt64 createdDate;
  SInt64 modifiedDate;
  SInt64 timestamp;
  SInt32 status;
}
- (BOOL) hasSessionId;
- (BOOL) hasUserId;
- (BOOL) hasInviterId;
- (BOOL) hasStatus;
- (BOOL) hasCreatedDate;
- (BOOL) hasModifiedDate;
- (BOOL) hasTimestamp;
@property (readonly) SInt64 sessionId;
@property (readonly) SInt64 userId;
@property (readonly) SInt64 inviterId;
@property (readonly) SInt32 status;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 modifiedDate;
@property (readonly) SInt64 timestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GUserPbBuilder*) builder;
+ (GUserPbBuilder*) builder;
+ (GUserPbBuilder*) builderWithPrototype:(GUserPb*) prototype;
- (GUserPbBuilder*) toBuilder;

+ (GUserPb*) parseFromData:(NSData*) data;
+ (GUserPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GUserPb*) parseFromInputStream:(NSInputStream*) input;
+ (GUserPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GUserPbBuilder : PBGeneratedMessageBuilder {
@private
  GUserPb* resultGuserPb;
}

- (GUserPb*) defaultInstance;

- (GUserPbBuilder*) clear;
- (GUserPbBuilder*) clone;

- (GUserPb*) build;
- (GUserPb*) buildPartial;

- (GUserPbBuilder*) mergeFrom:(GUserPb*) other;
- (GUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (SInt64) sessionId;
- (GUserPbBuilder*) setSessionId:(SInt64) value;
- (GUserPbBuilder*) clearSessionId;

- (BOOL) hasUserId;
- (SInt64) userId;
- (GUserPbBuilder*) setUserId:(SInt64) value;
- (GUserPbBuilder*) clearUserId;

- (BOOL) hasInviterId;
- (SInt64) inviterId;
- (GUserPbBuilder*) setInviterId:(SInt64) value;
- (GUserPbBuilder*) clearInviterId;

- (BOOL) hasStatus;
- (SInt32) status;
- (GUserPbBuilder*) setStatus:(SInt32) value;
- (GUserPbBuilder*) clearStatus;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (GUserPbBuilder*) setCreatedDate:(SInt64) value;
- (GUserPbBuilder*) clearCreatedDate;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (GUserPbBuilder*) setModifiedDate:(SInt64) value;
- (GUserPbBuilder*) clearModifiedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (GUserPbBuilder*) setTimestamp:(SInt64) value;
- (GUserPbBuilder*) clearTimestamp;
@end

#define GRecorderPb_id @"id"
#define GRecorderPb_sessionId @"sessionId"
#define GRecorderPb_type @"type"
#define GRecorderPb_message @"message"
#define GRecorderPb_voiceLength @"voiceLength"
#define GRecorderPb_createdBy @"createdBy"
#define GRecorderPb_createdDate @"createdDate"
#define GRecorderPb_timestamp @"timestamp"
#define GRecorderPb_file @"file"
#define GRecorderPb_uuid @"uuid"
@interface GRecorderPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSessionId_:1;
  BOOL hasCreatedBy_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasType_:1;
  BOOL hasVoiceLength_:1;
  BOOL hasMessage_:1;
  BOOL hasUuid_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 sessionId;
  SInt64 createdBy;
  SInt64 createdDate;
  SInt64 timestamp;
  SInt32 type;
  SInt32 voiceLength;
  NSString* message;
  NSString* uuid;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasSessionId;
- (BOOL) hasType;
- (BOOL) hasMessage;
- (BOOL) hasVoiceLength;
- (BOOL) hasCreatedBy;
- (BOOL) hasCreatedDate;
- (BOOL) hasTimestamp;
- (BOOL) hasFile;
- (BOOL) hasUuid;
@property (readonly) SInt64 id;
@property (readonly) SInt64 sessionId;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* message;
@property (readonly) SInt32 voiceLength;
@property (readonly) SInt64 createdBy;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 timestamp;
@property (readonly, strong) NSData* file;
@property (readonly, strong) NSString* uuid;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (GRecorderPbBuilder*) builder;
+ (GRecorderPbBuilder*) builder;
+ (GRecorderPbBuilder*) builderWithPrototype:(GRecorderPb*) prototype;
- (GRecorderPbBuilder*) toBuilder;

+ (GRecorderPb*) parseFromData:(NSData*) data;
+ (GRecorderPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GRecorderPb*) parseFromInputStream:(NSInputStream*) input;
+ (GRecorderPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (GRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (GRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface GRecorderPbBuilder : PBGeneratedMessageBuilder {
@private
  GRecorderPb* resultGrecorderPb;
}

- (GRecorderPb*) defaultInstance;

- (GRecorderPbBuilder*) clear;
- (GRecorderPbBuilder*) clone;

- (GRecorderPb*) build;
- (GRecorderPb*) buildPartial;

- (GRecorderPbBuilder*) mergeFrom:(GRecorderPb*) other;
- (GRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (GRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (GRecorderPbBuilder*) setId:(SInt64) value;
- (GRecorderPbBuilder*) clearId;

- (BOOL) hasSessionId;
- (SInt64) sessionId;
- (GRecorderPbBuilder*) setSessionId:(SInt64) value;
- (GRecorderPbBuilder*) clearSessionId;

- (BOOL) hasType;
- (SInt32) type;
- (GRecorderPbBuilder*) setType:(SInt32) value;
- (GRecorderPbBuilder*) clearType;

- (BOOL) hasMessage;
- (NSString*) message;
- (GRecorderPbBuilder*) setMessage:(NSString*) value;
- (GRecorderPbBuilder*) clearMessage;

- (BOOL) hasVoiceLength;
- (SInt32) voiceLength;
- (GRecorderPbBuilder*) setVoiceLength:(SInt32) value;
- (GRecorderPbBuilder*) clearVoiceLength;

- (BOOL) hasCreatedBy;
- (SInt64) createdBy;
- (GRecorderPbBuilder*) setCreatedBy:(SInt64) value;
- (GRecorderPbBuilder*) clearCreatedBy;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (GRecorderPbBuilder*) setCreatedDate:(SInt64) value;
- (GRecorderPbBuilder*) clearCreatedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (GRecorderPbBuilder*) setTimestamp:(SInt64) value;
- (GRecorderPbBuilder*) clearTimestamp;

- (BOOL) hasFile;
- (NSData*) file;
- (GRecorderPbBuilder*) setFile:(NSData*) value;
- (GRecorderPbBuilder*) clearFile;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (GRecorderPbBuilder*) setUuid:(NSString*) value;
- (GRecorderPbBuilder*) clearUuid;
@end


// @@protoc_insertion_point(global_scope)
