// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "FscSession.pb.h"
// @@protoc_insertion_point(imports)

@class CRecorderListPb;
@class CRecorderListPbBuilder;
@class CRecorderPb;
@class CRecorderPbBuilder;
@class CSessionPb;
@class CSessionPbBuilder;
@class CUserPb;
@class CUserPbBuilder;
@class FscSessionPb;
@class FscSessionPbBuilder;
@class URecorderListPb;
@class URecorderListPbBuilder;
@class URecorderPb;
@class URecorderPbBuilder;
@class USessionPb;
@class USessionPbBuilder;



@interface FscChatClassRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define CRecorderListPb_recorderPb @"recorderPb"
@interface CRecorderListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * recorderPbArray;
}
@property (readonly, strong) NSArray * recorderPb;
- (CRecorderPb*)recorderPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CRecorderListPbBuilder*) builder;
+ (CRecorderListPbBuilder*) builder;
+ (CRecorderListPbBuilder*) builderWithPrototype:(CRecorderListPb*) prototype;
- (CRecorderListPbBuilder*) toBuilder;

+ (CRecorderListPb*) parseFromData:(NSData*) data;
+ (CRecorderListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CRecorderListPb*) parseFromInputStream:(NSInputStream*) input;
+ (CRecorderListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CRecorderListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CRecorderListPbBuilder : PBGeneratedMessageBuilder {
@private
  CRecorderListPb* resultCrecorderListPb;
}

- (CRecorderListPb*) defaultInstance;

- (CRecorderListPbBuilder*) clear;
- (CRecorderListPbBuilder*) clone;

- (CRecorderListPb*) build;
- (CRecorderListPb*) buildPartial;

- (CRecorderListPbBuilder*) mergeFrom:(CRecorderListPb*) other;
- (CRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CRecorderListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)recorderPb;
- (CRecorderPb*)recorderPbAtIndex:(NSUInteger)index;
- (CRecorderListPbBuilder *)addRecorderPb:(CRecorderPb*)value;
- (CRecorderListPbBuilder *)setRecorderPbArray:(NSArray *)array;
- (CRecorderListPbBuilder *)clearRecorderPb;
@end

#define CSessionPb_id @"id"
#define CSessionPb_uuid @"uuid"
#define CSessionPb_name @"name"
#define CSessionPb_classId @"classId"
#define CSessionPb_createdDate @"createdDate"
#define CSessionPb_timestamp @"timestamp"
#define CSessionPb_user @"user"
#define CSessionPb_fscSession @"fscSession"
@interface CSessionPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasClassId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasUuid_:1;
  BOOL hasName_:1;
  BOOL hasFscSession_:1;
  SInt64 id;
  SInt64 classId;
  SInt64 createdDate;
  SInt64 timestamp;
  NSString* uuid;
  NSString* name;
  FscSessionPb* fscSession;
  NSMutableArray * userArray;
}
- (BOOL) hasId;
- (BOOL) hasUuid;
- (BOOL) hasName;
- (BOOL) hasClassId;
- (BOOL) hasCreatedDate;
- (BOOL) hasTimestamp;
- (BOOL) hasFscSession;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSString* name;
@property (readonly) SInt64 classId;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 timestamp;
@property (readonly, strong) NSArray * user;
@property (readonly, strong) FscSessionPb* fscSession;
- (CUserPb*)userAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CSessionPbBuilder*) builder;
+ (CSessionPbBuilder*) builder;
+ (CSessionPbBuilder*) builderWithPrototype:(CSessionPb*) prototype;
- (CSessionPbBuilder*) toBuilder;

+ (CSessionPb*) parseFromData:(NSData*) data;
+ (CSessionPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CSessionPb*) parseFromInputStream:(NSInputStream*) input;
+ (CSessionPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CSessionPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CSessionPbBuilder : PBGeneratedMessageBuilder {
@private
  CSessionPb* resultCsessionPb;
}

- (CSessionPb*) defaultInstance;

- (CSessionPbBuilder*) clear;
- (CSessionPbBuilder*) clone;

- (CSessionPb*) build;
- (CSessionPb*) buildPartial;

- (CSessionPbBuilder*) mergeFrom:(CSessionPb*) other;
- (CSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CSessionPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (CSessionPbBuilder*) setId:(SInt64) value;
- (CSessionPbBuilder*) clearId;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (CSessionPbBuilder*) setUuid:(NSString*) value;
- (CSessionPbBuilder*) clearUuid;

- (BOOL) hasName;
- (NSString*) name;
- (CSessionPbBuilder*) setName:(NSString*) value;
- (CSessionPbBuilder*) clearName;

- (BOOL) hasClassId;
- (SInt64) classId;
- (CSessionPbBuilder*) setClassId:(SInt64) value;
- (CSessionPbBuilder*) clearClassId;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (CSessionPbBuilder*) setCreatedDate:(SInt64) value;
- (CSessionPbBuilder*) clearCreatedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (CSessionPbBuilder*) setTimestamp:(SInt64) value;
- (CSessionPbBuilder*) clearTimestamp;

- (NSMutableArray *)user;
- (CUserPb*)userAtIndex:(NSUInteger)index;
- (CSessionPbBuilder *)addUser:(CUserPb*)value;
- (CSessionPbBuilder *)setUserArray:(NSArray *)array;
- (CSessionPbBuilder *)clearUser;

- (BOOL) hasFscSession;
- (FscSessionPb*) fscSession;
- (CSessionPbBuilder*) setFscSession:(FscSessionPb*) value;
- (CSessionPbBuilder*) setFscSessionBuilder:(FscSessionPbBuilder*) builderForValue;
- (CSessionPbBuilder*) mergeFscSession:(FscSessionPb*) value;
- (CSessionPbBuilder*) clearFscSession;
@end

#define CUserPb_sessionId @"sessionId"
#define CUserPb_userId @"userId"
#define CUserPb_inviterId @"inviterId"
#define CUserPb_status @"status"
#define CUserPb_createdDate @"createdDate"
#define CUserPb_modifiedDate @"modifiedDate"
#define CUserPb_timestamp @"timestamp"
@interface CUserPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSessionId_:1;
  BOOL hasUserId_:1;
  BOOL hasInviterId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasStatus_:1;
  SInt64 sessionId;
  SInt64 userId;
  SInt64 inviterId;
  SInt64 createdDate;
  SInt64 modifiedDate;
  SInt64 timestamp;
  SInt32 status;
}
- (BOOL) hasSessionId;
- (BOOL) hasUserId;
- (BOOL) hasInviterId;
- (BOOL) hasStatus;
- (BOOL) hasCreatedDate;
- (BOOL) hasModifiedDate;
- (BOOL) hasTimestamp;
@property (readonly) SInt64 sessionId;
@property (readonly) SInt64 userId;
@property (readonly) SInt64 inviterId;
@property (readonly) SInt32 status;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 modifiedDate;
@property (readonly) SInt64 timestamp;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CUserPbBuilder*) builder;
+ (CUserPbBuilder*) builder;
+ (CUserPbBuilder*) builderWithPrototype:(CUserPb*) prototype;
- (CUserPbBuilder*) toBuilder;

+ (CUserPb*) parseFromData:(NSData*) data;
+ (CUserPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CUserPb*) parseFromInputStream:(NSInputStream*) input;
+ (CUserPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CUserPbBuilder : PBGeneratedMessageBuilder {
@private
  CUserPb* resultCuserPb;
}

- (CUserPb*) defaultInstance;

- (CUserPbBuilder*) clear;
- (CUserPbBuilder*) clone;

- (CUserPb*) build;
- (CUserPb*) buildPartial;

- (CUserPbBuilder*) mergeFrom:(CUserPb*) other;
- (CUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSessionId;
- (SInt64) sessionId;
- (CUserPbBuilder*) setSessionId:(SInt64) value;
- (CUserPbBuilder*) clearSessionId;

- (BOOL) hasUserId;
- (SInt64) userId;
- (CUserPbBuilder*) setUserId:(SInt64) value;
- (CUserPbBuilder*) clearUserId;

- (BOOL) hasInviterId;
- (SInt64) inviterId;
- (CUserPbBuilder*) setInviterId:(SInt64) value;
- (CUserPbBuilder*) clearInviterId;

- (BOOL) hasStatus;
- (SInt32) status;
- (CUserPbBuilder*) setStatus:(SInt32) value;
- (CUserPbBuilder*) clearStatus;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (CUserPbBuilder*) setCreatedDate:(SInt64) value;
- (CUserPbBuilder*) clearCreatedDate;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (CUserPbBuilder*) setModifiedDate:(SInt64) value;
- (CUserPbBuilder*) clearModifiedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (CUserPbBuilder*) setTimestamp:(SInt64) value;
- (CUserPbBuilder*) clearTimestamp;
@end

#define CRecorderPb_id @"id"
#define CRecorderPb_sessionId @"sessionId"
#define CRecorderPb_type @"type"
#define CRecorderPb_message @"message"
#define CRecorderPb_voiceLength @"voiceLength"
#define CRecorderPb_createdBy @"createdBy"
#define CRecorderPb_createdDate @"createdDate"
#define CRecorderPb_timestamp @"timestamp"
#define CRecorderPb_file @"file"
#define CRecorderPb_uuid @"uuid"
#define CRecorderPb_extendId @"extendId"
@interface CRecorderPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSessionId_:1;
  BOOL hasCreatedBy_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasTimestamp_:1;
  BOOL hasExtendId_:1;
  BOOL hasType_:1;
  BOOL hasVoiceLength_:1;
  BOOL hasMessage_:1;
  BOOL hasUuid_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 sessionId;
  SInt64 createdBy;
  SInt64 createdDate;
  SInt64 timestamp;
  SInt64 extendId;
  SInt32 type;
  SInt32 voiceLength;
  NSString* message;
  NSString* uuid;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasSessionId;
- (BOOL) hasType;
- (BOOL) hasMessage;
- (BOOL) hasVoiceLength;
- (BOOL) hasCreatedBy;
- (BOOL) hasCreatedDate;
- (BOOL) hasTimestamp;
- (BOOL) hasFile;
- (BOOL) hasUuid;
- (BOOL) hasExtendId;
@property (readonly) SInt64 id;
@property (readonly) SInt64 sessionId;
@property (readonly) SInt32 type;
@property (readonly, strong) NSString* message;
@property (readonly) SInt32 voiceLength;
@property (readonly) SInt64 createdBy;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 timestamp;
@property (readonly, strong) NSData* file;
@property (readonly, strong) NSString* uuid;
@property (readonly) SInt64 extendId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (CRecorderPbBuilder*) builder;
+ (CRecorderPbBuilder*) builder;
+ (CRecorderPbBuilder*) builderWithPrototype:(CRecorderPb*) prototype;
- (CRecorderPbBuilder*) toBuilder;

+ (CRecorderPb*) parseFromData:(NSData*) data;
+ (CRecorderPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CRecorderPb*) parseFromInputStream:(NSInputStream*) input;
+ (CRecorderPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (CRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (CRecorderPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface CRecorderPbBuilder : PBGeneratedMessageBuilder {
@private
  CRecorderPb* resultCrecorderPb;
}

- (CRecorderPb*) defaultInstance;

- (CRecorderPbBuilder*) clear;
- (CRecorderPbBuilder*) clone;

- (CRecorderPb*) build;
- (CRecorderPb*) buildPartial;

- (CRecorderPbBuilder*) mergeFrom:(CRecorderPb*) other;
- (CRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (CRecorderPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (CRecorderPbBuilder*) setId:(SInt64) value;
- (CRecorderPbBuilder*) clearId;

- (BOOL) hasSessionId;
- (SInt64) sessionId;
- (CRecorderPbBuilder*) setSessionId:(SInt64) value;
- (CRecorderPbBuilder*) clearSessionId;

- (BOOL) hasType;
- (SInt32) type;
- (CRecorderPbBuilder*) setType:(SInt32) value;
- (CRecorderPbBuilder*) clearType;

- (BOOL) hasMessage;
- (NSString*) message;
- (CRecorderPbBuilder*) setMessage:(NSString*) value;
- (CRecorderPbBuilder*) clearMessage;

- (BOOL) hasVoiceLength;
- (SInt32) voiceLength;
- (CRecorderPbBuilder*) setVoiceLength:(SInt32) value;
- (CRecorderPbBuilder*) clearVoiceLength;

- (BOOL) hasCreatedBy;
- (SInt64) createdBy;
- (CRecorderPbBuilder*) setCreatedBy:(SInt64) value;
- (CRecorderPbBuilder*) clearCreatedBy;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (CRecorderPbBuilder*) setCreatedDate:(SInt64) value;
- (CRecorderPbBuilder*) clearCreatedDate;

- (BOOL) hasTimestamp;
- (SInt64) timestamp;
- (CRecorderPbBuilder*) setTimestamp:(SInt64) value;
- (CRecorderPbBuilder*) clearTimestamp;

- (BOOL) hasFile;
- (NSData*) file;
- (CRecorderPbBuilder*) setFile:(NSData*) value;
- (CRecorderPbBuilder*) clearFile;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (CRecorderPbBuilder*) setUuid:(NSString*) value;
- (CRecorderPbBuilder*) clearUuid;

- (BOOL) hasExtendId;
- (SInt64) extendId;
- (CRecorderPbBuilder*) setExtendId:(SInt64) value;
- (CRecorderPbBuilder*) clearExtendId;
@end


// @@protoc_insertion_point(global_scope)
