// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FscNoticeListPb;
@class FscNoticeListPbBuilder;
@class FscNoticePb;
@class FscNoticePbBuilder;



@interface FscNoticeRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FscNoticeListPb_noticePb @"noticePb"
@interface FscNoticeListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * noticePbArray;
}
@property (readonly, strong) NSArray * noticePb;
- (FscNoticePb*)noticePbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscNoticeListPbBuilder*) builder;
+ (FscNoticeListPbBuilder*) builder;
+ (FscNoticeListPbBuilder*) builderWithPrototype:(FscNoticeListPb*) prototype;
- (FscNoticeListPbBuilder*) toBuilder;

+ (FscNoticeListPb*) parseFromData:(NSData*) data;
+ (FscNoticeListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscNoticeListPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscNoticeListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscNoticeListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscNoticeListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscNoticeListPbBuilder : PBGeneratedMessageBuilder {
@private
  FscNoticeListPb* resultFscNoticeListPb;
}

- (FscNoticeListPb*) defaultInstance;

- (FscNoticeListPbBuilder*) clear;
- (FscNoticeListPbBuilder*) clone;

- (FscNoticeListPb*) build;
- (FscNoticeListPb*) buildPartial;

- (FscNoticeListPbBuilder*) mergeFrom:(FscNoticeListPb*) other;
- (FscNoticeListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscNoticeListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)noticePb;
- (FscNoticePb*)noticePbAtIndex:(NSUInteger)index;
- (FscNoticeListPbBuilder *)addNoticePb:(FscNoticePb*)value;
- (FscNoticeListPbBuilder *)setNoticePbArray:(NSArray *)array;
- (FscNoticeListPbBuilder *)clearNoticePb;
@end

#define FscNoticePb_id @"id"
#define FscNoticePb_noticeType @"noticeType"
#define FscNoticePb_title @"title"
#define FscNoticePb_coverImg @"coverImg"
#define FscNoticePb_summary @"summary"
#define FscNoticePb_createdDate @"createdDate"
#define FscNoticePb_modifiedDate @"modifiedDate"
@interface FscNoticePb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasCreatedDate_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasNoticeType_:1;
  BOOL hasTitle_:1;
  BOOL hasCoverImg_:1;
  BOOL hasSummary_:1;
  SInt64 id;
  SInt64 createdDate;
  SInt64 modifiedDate;
  NSString* noticeType;
  NSString* title;
  NSString* coverImg;
  NSString* summary;
}
- (BOOL) hasId;
- (BOOL) hasNoticeType;
- (BOOL) hasTitle;
- (BOOL) hasCoverImg;
- (BOOL) hasSummary;
- (BOOL) hasCreatedDate;
- (BOOL) hasModifiedDate;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* noticeType;
@property (readonly, strong) NSString* title;
@property (readonly, strong) NSString* coverImg;
@property (readonly, strong) NSString* summary;
@property (readonly) SInt64 createdDate;
@property (readonly) SInt64 modifiedDate;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscNoticePbBuilder*) builder;
+ (FscNoticePbBuilder*) builder;
+ (FscNoticePbBuilder*) builderWithPrototype:(FscNoticePb*) prototype;
- (FscNoticePbBuilder*) toBuilder;

+ (FscNoticePb*) parseFromData:(NSData*) data;
+ (FscNoticePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscNoticePb*) parseFromInputStream:(NSInputStream*) input;
+ (FscNoticePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscNoticePb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscNoticePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscNoticePbBuilder : PBGeneratedMessageBuilder {
@private
  FscNoticePb* resultFscNoticePb;
}

- (FscNoticePb*) defaultInstance;

- (FscNoticePbBuilder*) clear;
- (FscNoticePbBuilder*) clone;

- (FscNoticePb*) build;
- (FscNoticePb*) buildPartial;

- (FscNoticePbBuilder*) mergeFrom:(FscNoticePb*) other;
- (FscNoticePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscNoticePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscNoticePbBuilder*) setId:(SInt64) value;
- (FscNoticePbBuilder*) clearId;

- (BOOL) hasNoticeType;
- (NSString*) noticeType;
- (FscNoticePbBuilder*) setNoticeType:(NSString*) value;
- (FscNoticePbBuilder*) clearNoticeType;

- (BOOL) hasTitle;
- (NSString*) title;
- (FscNoticePbBuilder*) setTitle:(NSString*) value;
- (FscNoticePbBuilder*) clearTitle;

- (BOOL) hasCoverImg;
- (NSString*) coverImg;
- (FscNoticePbBuilder*) setCoverImg:(NSString*) value;
- (FscNoticePbBuilder*) clearCoverImg;

- (BOOL) hasSummary;
- (NSString*) summary;
- (FscNoticePbBuilder*) setSummary:(NSString*) value;
- (FscNoticePbBuilder*) clearSummary;

- (BOOL) hasCreatedDate;
- (SInt64) createdDate;
- (FscNoticePbBuilder*) setCreatedDate:(SInt64) value;
- (FscNoticePbBuilder*) clearCreatedDate;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (FscNoticePbBuilder*) setModifiedDate:(SInt64) value;
- (FscNoticePbBuilder*) clearModifiedDate;
@end


// @@protoc_insertion_point(global_scope)
