// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FscUserPb;
@class FscUserPbBuilder;
@class FscUserPbList;
@class FscUserPbListBuilder;



@interface FscUserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FscUserPbList_fscUserPb @"fscUserPb"
@interface FscUserPbList : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * fscUserPbArray;
}
@property (readonly, strong) NSArray * fscUserPb;
- (FscUserPb*)fscUserPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscUserPbListBuilder*) builder;
+ (FscUserPbListBuilder*) builder;
+ (FscUserPbListBuilder*) builderWithPrototype:(FscUserPbList*) prototype;
- (FscUserPbListBuilder*) toBuilder;

+ (FscUserPbList*) parseFromData:(NSData*) data;
+ (FscUserPbList*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscUserPbList*) parseFromInputStream:(NSInputStream*) input;
+ (FscUserPbList*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscUserPbList*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscUserPbList*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscUserPbListBuilder : PBGeneratedMessageBuilder {
@private
  FscUserPbList* resultFscUserPbList;
}

- (FscUserPbList*) defaultInstance;

- (FscUserPbListBuilder*) clear;
- (FscUserPbListBuilder*) clone;

- (FscUserPbList*) build;
- (FscUserPbList*) buildPartial;

- (FscUserPbListBuilder*) mergeFrom:(FscUserPbList*) other;
- (FscUserPbListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscUserPbListBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)fscUserPb;
- (FscUserPb*)fscUserPbAtIndex:(NSUInteger)index;
- (FscUserPbListBuilder *)addFscUserPb:(FscUserPb*)value;
- (FscUserPbListBuilder *)setFscUserPbArray:(NSArray *)array;
- (FscUserPbListBuilder *)clearFscUserPb;
@end

#define FscUserPb_id @"id"
#define FscUserPb_name @"name"
#define FscUserPb_gender @"gender"
#define FscUserPb_userType @"userType"
#define FscUserPb_portrait @"portrait"
#define FscUserPb_schoolName @"schoolName"
#define FscUserPb_keyword @"keyword"
#define FscUserPb_linkmanId @"linkmanId"
#define FscUserPb_addStatus @"addStatus"
#define FscUserPb_classId @"classId"
#define FscUserPb_file @"file"
@interface FscUserPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasLinkmanId_:1;
  BOOL hasClassId_:1;
  BOOL hasGender_:1;
  BOOL hasUserType_:1;
  BOOL hasAddStatus_:1;
  BOOL hasName_:1;
  BOOL hasPortrait_:1;
  BOOL hasSchoolName_:1;
  BOOL hasKeyword_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 linkmanId;
  SInt64 classId;
  SInt32 gender;
  SInt32 userType;
  SInt32 addStatus;
  NSString* name;
  NSString* portrait;
  NSString* schoolName;
  NSString* keyword;
  NSData* file;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasGender;
- (BOOL) hasUserType;
- (BOOL) hasPortrait;
- (BOOL) hasSchoolName;
- (BOOL) hasKeyword;
- (BOOL) hasLinkmanId;
- (BOOL) hasAddStatus;
- (BOOL) hasClassId;
- (BOOL) hasFile;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 gender;
@property (readonly) SInt32 userType;
@property (readonly, strong) NSString* portrait;
@property (readonly, strong) NSString* schoolName;
@property (readonly, strong) NSString* keyword;
@property (readonly) SInt64 linkmanId;
@property (readonly) SInt32 addStatus;
@property (readonly) SInt64 classId;
@property (readonly, strong) NSData* file;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscUserPbBuilder*) builder;
+ (FscUserPbBuilder*) builder;
+ (FscUserPbBuilder*) builderWithPrototype:(FscUserPb*) prototype;
- (FscUserPbBuilder*) toBuilder;

+ (FscUserPb*) parseFromData:(NSData*) data;
+ (FscUserPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscUserPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscUserPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscUserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscUserPbBuilder : PBGeneratedMessageBuilder {
@private
  FscUserPb* resultFscUserPb;
}

- (FscUserPb*) defaultInstance;

- (FscUserPbBuilder*) clear;
- (FscUserPbBuilder*) clone;

- (FscUserPb*) build;
- (FscUserPb*) buildPartial;

- (FscUserPbBuilder*) mergeFrom:(FscUserPb*) other;
- (FscUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscUserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscUserPbBuilder*) setId:(SInt64) value;
- (FscUserPbBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (FscUserPbBuilder*) setName:(NSString*) value;
- (FscUserPbBuilder*) clearName;

- (BOOL) hasGender;
- (SInt32) gender;
- (FscUserPbBuilder*) setGender:(SInt32) value;
- (FscUserPbBuilder*) clearGender;

- (BOOL) hasUserType;
- (SInt32) userType;
- (FscUserPbBuilder*) setUserType:(SInt32) value;
- (FscUserPbBuilder*) clearUserType;

- (BOOL) hasPortrait;
- (NSString*) portrait;
- (FscUserPbBuilder*) setPortrait:(NSString*) value;
- (FscUserPbBuilder*) clearPortrait;

- (BOOL) hasSchoolName;
- (NSString*) schoolName;
- (FscUserPbBuilder*) setSchoolName:(NSString*) value;
- (FscUserPbBuilder*) clearSchoolName;

- (BOOL) hasKeyword;
- (NSString*) keyword;
- (FscUserPbBuilder*) setKeyword:(NSString*) value;
- (FscUserPbBuilder*) clearKeyword;

- (BOOL) hasLinkmanId;
- (SInt64) linkmanId;
- (FscUserPbBuilder*) setLinkmanId:(SInt64) value;
- (FscUserPbBuilder*) clearLinkmanId;

- (BOOL) hasAddStatus;
- (SInt32) addStatus;
- (FscUserPbBuilder*) setAddStatus:(SInt32) value;
- (FscUserPbBuilder*) clearAddStatus;

- (BOOL) hasClassId;
- (SInt64) classId;
- (FscUserPbBuilder*) setClassId:(SInt64) value;
- (FscUserPbBuilder*) clearClassId;

- (BOOL) hasFile;
- (NSData*) file;
- (FscUserPbBuilder*) setFile:(NSData*) value;
- (FscUserPbBuilder*) clearFile;
@end


// @@protoc_insertion_point(global_scope)
