// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class FscVoteListPb;
@class FscVoteListPbBuilder;
@class FscVotePb;
@class FscVotePbBuilder;
@class FscVoteQuesItemPb;
@class FscVoteQuesItemPbBuilder;
@class FscVoteQuesPb;
@class FscVoteQuesPbBuilder;



@interface FscVoteRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define FscVoteListPb_votePb @"votePb"
@interface FscVoteListPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  NSMutableArray * votePbArray;
}
@property (readonly, strong) NSArray * votePb;
- (FscVotePb*)votePbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscVoteListPbBuilder*) builder;
+ (FscVoteListPbBuilder*) builder;
+ (FscVoteListPbBuilder*) builderWithPrototype:(FscVoteListPb*) prototype;
- (FscVoteListPbBuilder*) toBuilder;

+ (FscVoteListPb*) parseFromData:(NSData*) data;
+ (FscVoteListPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteListPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscVoteListPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscVoteListPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscVoteListPbBuilder : PBGeneratedMessageBuilder {
@private
  FscVoteListPb* resultFscVoteListPb;
}

- (FscVoteListPb*) defaultInstance;

- (FscVoteListPbBuilder*) clear;
- (FscVoteListPbBuilder*) clone;

- (FscVoteListPb*) build;
- (FscVoteListPb*) buildPartial;

- (FscVoteListPbBuilder*) mergeFrom:(FscVoteListPb*) other;
- (FscVoteListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscVoteListPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (NSMutableArray *)votePb;
- (FscVotePb*)votePbAtIndex:(NSUInteger)index;
- (FscVoteListPbBuilder *)addVotePb:(FscVotePb*)value;
- (FscVoteListPbBuilder *)setVotePbArray:(NSArray *)array;
- (FscVoteListPbBuilder *)clearVotePb;
@end

#define FscVotePb_id @"id"
#define FscVotePb_voteName @"voteName"
#define FscVotePb_voteNum @"voteNum"
#define FscVotePb_coverImg @"coverImg"
#define FscVotePb_deadline @"deadline"
#define FscVotePb_modifiedDate @"modifiedDate"
#define FscVotePb_quesList @"quesList"
#define FscVotePb_fscVoteQuesPb @"fscVoteQuesPb"
#define FscVotePb_applyStatus @"applyStatus"
@interface FscVotePb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasVoteNum_:1;
  BOOL hasDeadline_:1;
  BOOL hasModifiedDate_:1;
  BOOL hasApplyStatus_:1;
  BOOL hasVoteName_:1;
  BOOL hasCoverImg_:1;
  BOOL hasQuesList_:1;
  SInt64 id;
  SInt64 voteNum;
  SInt64 deadline;
  SInt64 modifiedDate;
  SInt32 applyStatus;
  NSString* voteName;
  NSString* coverImg;
  NSString* quesList;
  NSMutableArray * fscVoteQuesPbArray;
}
- (BOOL) hasId;
- (BOOL) hasVoteName;
- (BOOL) hasVoteNum;
- (BOOL) hasCoverImg;
- (BOOL) hasDeadline;
- (BOOL) hasModifiedDate;
- (BOOL) hasQuesList;
- (BOOL) hasApplyStatus;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* voteName;
@property (readonly) SInt64 voteNum;
@property (readonly, strong) NSString* coverImg;
@property (readonly) SInt64 deadline;
@property (readonly) SInt64 modifiedDate;
@property (readonly, strong) NSString* quesList;
@property (readonly, strong) NSArray * fscVoteQuesPb;
@property (readonly) SInt32 applyStatus;
- (FscVoteQuesPb*)fscVoteQuesPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscVotePbBuilder*) builder;
+ (FscVotePbBuilder*) builder;
+ (FscVotePbBuilder*) builderWithPrototype:(FscVotePb*) prototype;
- (FscVotePbBuilder*) toBuilder;

+ (FscVotePb*) parseFromData:(NSData*) data;
+ (FscVotePb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVotePb*) parseFromInputStream:(NSInputStream*) input;
+ (FscVotePb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVotePb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscVotePb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscVotePbBuilder : PBGeneratedMessageBuilder {
@private
  FscVotePb* resultFscVotePb;
}

- (FscVotePb*) defaultInstance;

- (FscVotePbBuilder*) clear;
- (FscVotePbBuilder*) clone;

- (FscVotePb*) build;
- (FscVotePb*) buildPartial;

- (FscVotePbBuilder*) mergeFrom:(FscVotePb*) other;
- (FscVotePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscVotePbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscVotePbBuilder*) setId:(SInt64) value;
- (FscVotePbBuilder*) clearId;

- (BOOL) hasVoteName;
- (NSString*) voteName;
- (FscVotePbBuilder*) setVoteName:(NSString*) value;
- (FscVotePbBuilder*) clearVoteName;

- (BOOL) hasVoteNum;
- (SInt64) voteNum;
- (FscVotePbBuilder*) setVoteNum:(SInt64) value;
- (FscVotePbBuilder*) clearVoteNum;

- (BOOL) hasCoverImg;
- (NSString*) coverImg;
- (FscVotePbBuilder*) setCoverImg:(NSString*) value;
- (FscVotePbBuilder*) clearCoverImg;

- (BOOL) hasDeadline;
- (SInt64) deadline;
- (FscVotePbBuilder*) setDeadline:(SInt64) value;
- (FscVotePbBuilder*) clearDeadline;

- (BOOL) hasModifiedDate;
- (SInt64) modifiedDate;
- (FscVotePbBuilder*) setModifiedDate:(SInt64) value;
- (FscVotePbBuilder*) clearModifiedDate;

- (BOOL) hasQuesList;
- (NSString*) quesList;
- (FscVotePbBuilder*) setQuesList:(NSString*) value;
- (FscVotePbBuilder*) clearQuesList;

- (NSMutableArray *)fscVoteQuesPb;
- (FscVoteQuesPb*)fscVoteQuesPbAtIndex:(NSUInteger)index;
- (FscVotePbBuilder *)addFscVoteQuesPb:(FscVoteQuesPb*)value;
- (FscVotePbBuilder *)setFscVoteQuesPbArray:(NSArray *)array;
- (FscVotePbBuilder *)clearFscVoteQuesPb;

- (BOOL) hasApplyStatus;
- (SInt32) applyStatus;
- (FscVotePbBuilder*) setApplyStatus:(SInt32) value;
- (FscVotePbBuilder*) clearApplyStatus;
@end

#define FscVoteQuesPb_id @"id"
#define FscVoteQuesPb_voteId @"voteId"
#define FscVoteQuesPb_title @"title"
#define FscVoteQuesPb_checkType @"checkType"
#define FscVoteQuesPb_fscVoteQuesItemPb @"fscVoteQuesItemPb"
@interface FscVoteQuesPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasVoteId_:1;
  BOOL hasCheckType_:1;
  BOOL hasTitle_:1;
  SInt64 id;
  SInt64 voteId;
  SInt32 checkType;
  NSString* title;
  NSMutableArray * fscVoteQuesItemPbArray;
}
- (BOOL) hasId;
- (BOOL) hasVoteId;
- (BOOL) hasTitle;
- (BOOL) hasCheckType;
@property (readonly) SInt64 id;
@property (readonly) SInt64 voteId;
@property (readonly, strong) NSString* title;
@property (readonly) SInt32 checkType;
@property (readonly, strong) NSArray * fscVoteQuesItemPb;
- (FscVoteQuesItemPb*)fscVoteQuesItemPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscVoteQuesPbBuilder*) builder;
+ (FscVoteQuesPbBuilder*) builder;
+ (FscVoteQuesPbBuilder*) builderWithPrototype:(FscVoteQuesPb*) prototype;
- (FscVoteQuesPbBuilder*) toBuilder;

+ (FscVoteQuesPb*) parseFromData:(NSData*) data;
+ (FscVoteQuesPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteQuesPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscVoteQuesPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteQuesPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscVoteQuesPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscVoteQuesPbBuilder : PBGeneratedMessageBuilder {
@private
  FscVoteQuesPb* resultFscVoteQuesPb;
}

- (FscVoteQuesPb*) defaultInstance;

- (FscVoteQuesPbBuilder*) clear;
- (FscVoteQuesPbBuilder*) clone;

- (FscVoteQuesPb*) build;
- (FscVoteQuesPb*) buildPartial;

- (FscVoteQuesPbBuilder*) mergeFrom:(FscVoteQuesPb*) other;
- (FscVoteQuesPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscVoteQuesPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscVoteQuesPbBuilder*) setId:(SInt64) value;
- (FscVoteQuesPbBuilder*) clearId;

- (BOOL) hasVoteId;
- (SInt64) voteId;
- (FscVoteQuesPbBuilder*) setVoteId:(SInt64) value;
- (FscVoteQuesPbBuilder*) clearVoteId;

- (BOOL) hasTitle;
- (NSString*) title;
- (FscVoteQuesPbBuilder*) setTitle:(NSString*) value;
- (FscVoteQuesPbBuilder*) clearTitle;

- (BOOL) hasCheckType;
- (SInt32) checkType;
- (FscVoteQuesPbBuilder*) setCheckType:(SInt32) value;
- (FscVoteQuesPbBuilder*) clearCheckType;

- (NSMutableArray *)fscVoteQuesItemPb;
- (FscVoteQuesItemPb*)fscVoteQuesItemPbAtIndex:(NSUInteger)index;
- (FscVoteQuesPbBuilder *)addFscVoteQuesItemPb:(FscVoteQuesItemPb*)value;
- (FscVoteQuesPbBuilder *)setFscVoteQuesItemPbArray:(NSArray *)array;
- (FscVoteQuesPbBuilder *)clearFscVoteQuesItemPb;
@end

#define FscVoteQuesItemPb_id @"id"
#define FscVoteQuesItemPb_voteQuesId @"voteQuesId"
#define FscVoteQuesItemPb_title @"title"
@interface FscVoteQuesItemPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasVoteQuesId_:1;
  BOOL hasTitle_:1;
  SInt64 id;
  SInt64 voteQuesId;
  NSString* title;
}
- (BOOL) hasId;
- (BOOL) hasVoteQuesId;
- (BOOL) hasTitle;
@property (readonly) SInt64 id;
@property (readonly) SInt64 voteQuesId;
@property (readonly, strong) NSString* title;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FscVoteQuesItemPbBuilder*) builder;
+ (FscVoteQuesItemPbBuilder*) builder;
+ (FscVoteQuesItemPbBuilder*) builderWithPrototype:(FscVoteQuesItemPb*) prototype;
- (FscVoteQuesItemPbBuilder*) toBuilder;

+ (FscVoteQuesItemPb*) parseFromData:(NSData*) data;
+ (FscVoteQuesItemPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteQuesItemPb*) parseFromInputStream:(NSInputStream*) input;
+ (FscVoteQuesItemPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FscVoteQuesItemPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FscVoteQuesItemPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FscVoteQuesItemPbBuilder : PBGeneratedMessageBuilder {
@private
  FscVoteQuesItemPb* resultFscVoteQuesItemPb;
}

- (FscVoteQuesItemPb*) defaultInstance;

- (FscVoteQuesItemPbBuilder*) clear;
- (FscVoteQuesItemPbBuilder*) clone;

- (FscVoteQuesItemPb*) build;
- (FscVoteQuesItemPb*) buildPartial;

- (FscVoteQuesItemPbBuilder*) mergeFrom:(FscVoteQuesItemPb*) other;
- (FscVoteQuesItemPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FscVoteQuesItemPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (FscVoteQuesItemPbBuilder*) setId:(SInt64) value;
- (FscVoteQuesItemPbBuilder*) clearId;

- (BOOL) hasVoteQuesId;
- (SInt64) voteQuesId;
- (FscVoteQuesItemPbBuilder*) setVoteQuesId:(SInt64) value;
- (FscVoteQuesItemPbBuilder*) clearVoteQuesId;

- (BOOL) hasTitle;
- (NSString*) title;
- (FscVoteQuesItemPbBuilder*) setTitle:(NSString*) value;
- (FscVoteQuesItemPbBuilder*) clearTitle;
@end


// @@protoc_insertion_point(global_scope)
