// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

// @@protoc_insertion_point(imports)

@class PhoneInfoPb;
@class PhoneInfoPbBuilder;



@interface PhoneInfoRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define PhoneInfoPb_deviceId @"deviceId"
#define PhoneInfoPb_subscriberId @"subscriberId"
#define PhoneInfoPb_model @"model"
#define PhoneInfoPb_brand @"brand"
#define PhoneInfoPb_number @"number"
#define PhoneInfoPb_appVersion @"appVersion"
#define PhoneInfoPb_osVersion @"osVersion"
@interface PhoneInfoPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasOsVersion_:1;
  BOOL hasDeviceId_:1;
  BOOL hasSubscriberId_:1;
  BOOL hasModel_:1;
  BOOL hasBrand_:1;
  BOOL hasNumber_:1;
  BOOL hasAppVersion_:1;
  SInt32 osVersion;
  NSString* deviceId;
  NSString* subscriberId;
  NSString* model;
  NSString* brand;
  NSString* number;
  NSString* appVersion;
}
- (BOOL) hasDeviceId;
- (BOOL) hasSubscriberId;
- (BOOL) hasModel;
- (BOOL) hasBrand;
- (BOOL) hasNumber;
- (BOOL) hasAppVersion;
- (BOOL) hasOsVersion;
@property (readonly, strong) NSString* deviceId;
@property (readonly, strong) NSString* subscriberId;
@property (readonly, strong) NSString* model;
@property (readonly, strong) NSString* brand;
@property (readonly, strong) NSString* number;
@property (readonly, strong) NSString* appVersion;
@property (readonly) SInt32 osVersion;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (PhoneInfoPbBuilder*) builder;
+ (PhoneInfoPbBuilder*) builder;
+ (PhoneInfoPbBuilder*) builderWithPrototype:(PhoneInfoPb*) prototype;
- (PhoneInfoPbBuilder*) toBuilder;

+ (PhoneInfoPb*) parseFromData:(NSData*) data;
+ (PhoneInfoPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PhoneInfoPb*) parseFromInputStream:(NSInputStream*) input;
+ (PhoneInfoPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (PhoneInfoPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (PhoneInfoPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface PhoneInfoPbBuilder : PBGeneratedMessageBuilder {
@private
  PhoneInfoPb* resultPhoneInfoPb;
}

- (PhoneInfoPb*) defaultInstance;

- (PhoneInfoPbBuilder*) clear;
- (PhoneInfoPbBuilder*) clone;

- (PhoneInfoPb*) build;
- (PhoneInfoPb*) buildPartial;

- (PhoneInfoPbBuilder*) mergeFrom:(PhoneInfoPb*) other;
- (PhoneInfoPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (PhoneInfoPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasDeviceId;
- (NSString*) deviceId;
- (PhoneInfoPbBuilder*) setDeviceId:(NSString*) value;
- (PhoneInfoPbBuilder*) clearDeviceId;

- (BOOL) hasSubscriberId;
- (NSString*) subscriberId;
- (PhoneInfoPbBuilder*) setSubscriberId:(NSString*) value;
- (PhoneInfoPbBuilder*) clearSubscriberId;

- (BOOL) hasModel;
- (NSString*) model;
- (PhoneInfoPbBuilder*) setModel:(NSString*) value;
- (PhoneInfoPbBuilder*) clearModel;

- (BOOL) hasBrand;
- (NSString*) brand;
- (PhoneInfoPbBuilder*) setBrand:(NSString*) value;
- (PhoneInfoPbBuilder*) clearBrand;

- (BOOL) hasNumber;
- (NSString*) number;
- (PhoneInfoPbBuilder*) setNumber:(NSString*) value;
- (PhoneInfoPbBuilder*) clearNumber;

- (BOOL) hasAppVersion;
- (NSString*) appVersion;
- (PhoneInfoPbBuilder*) setAppVersion:(NSString*) value;
- (PhoneInfoPbBuilder*) clearAppVersion;

- (BOOL) hasOsVersion;
- (SInt32) osVersion;
- (PhoneInfoPbBuilder*) setOsVersion:(SInt32) value;
- (PhoneInfoPbBuilder*) clearOsVersion;
@end


// @@protoc_insertion_point(global_scope)
