// Generated by the protocol buffer compiler.  DO NOT EDIT!

#import <ProtocolBuffers/ProtocolBuffers.h>

#import "FscClass.pb.h"
#import "FscTeachPlan.pb.h"
// @@protoc_insertion_point(imports)

@class FscClassPb;
@class FscClassPbBuilder;
@class FscClassPbList;
@class FscClassPbListBuilder;
@class FuncCtrlPb;
@class FuncCtrlPbBuilder;
@class ParentsPb;
@class ParentsPbBuilder;
@class SchoolPb;
@class SchoolPbBuilder;
@class StudentPb;
@class StudentPbBuilder;
@class TeachPlanImgPb;
@class TeachPlanImgPbBuilder;
@class TeachPlanNodePb;
@class TeachPlanNodePbBuilder;
@class TeachPlanPb;
@class TeachPlanPbBuilder;
@class TeacherPb;
@class TeacherPbBuilder;
@class UserPb;
@class UserPbBuilder;



@interface UserRoot : NSObject {
}
+ (PBExtensionRegistry*) extensionRegistry;
+ (void) registerAllExtensions:(PBMutableExtensionRegistry*) registry;
@end

#define UserPb_id @"id"
#define UserPb_schoolId @"schoolId"
#define UserPb_uuid @"uuid"
#define UserPb_username @"username"
#define UserPb_password @"password"
#define UserPb_name @"name"
#define UserPb_userType @"userType"
#define UserPb_phaseId @"phaseId"
#define UserPb_gender @"gender"
#define UserPb_address @"address"
#define UserPb_email @"email"
#define UserPb_token @"token"
#define UserPb_schoolName @"schoolName"
#define UserPb_portrait @"portrait"
#define UserPb_file @"file"
#define UserPb_parentsPb @"parentsPb"
#define UserPb_teacherPb @"teacherPb"
#define UserPb_schoolPb @"schoolPb"
#define UserPb_funcCtrlPb @"funcCtrlPb"
@interface UserPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasSchoolId_:1;
  BOOL hasPhaseId_:1;
  BOOL hasUserType_:1;
  BOOL hasGender_:1;
  BOOL hasUuid_:1;
  BOOL hasUsername_:1;
  BOOL hasPassword_:1;
  BOOL hasName_:1;
  BOOL hasAddress_:1;
  BOOL hasEmail_:1;
  BOOL hasToken_:1;
  BOOL hasSchoolName_:1;
  BOOL hasPortrait_:1;
  BOOL hasParentsPb_:1;
  BOOL hasTeacherPb_:1;
  BOOL hasSchoolPb_:1;
  BOOL hasFile_:1;
  SInt64 id;
  SInt64 schoolId;
  SInt64 phaseId;
  SInt32 userType;
  SInt32 gender;
  NSString* uuid;
  NSString* username;
  NSString* password;
  NSString* name;
  NSString* address;
  NSString* email;
  NSString* token;
  NSString* schoolName;
  NSString* portrait;
  ParentsPb* parentsPb;
  TeacherPb* teacherPb;
  SchoolPb* schoolPb;
  NSData* file;
  NSMutableArray * funcCtrlPbArray;
}
- (BOOL) hasId;
- (BOOL) hasSchoolId;
- (BOOL) hasUuid;
- (BOOL) hasUsername;
- (BOOL) hasPassword;
- (BOOL) hasName;
- (BOOL) hasUserType;
- (BOOL) hasPhaseId;
- (BOOL) hasGender;
- (BOOL) hasAddress;
- (BOOL) hasEmail;
- (BOOL) hasToken;
- (BOOL) hasSchoolName;
- (BOOL) hasPortrait;
- (BOOL) hasFile;
- (BOOL) hasParentsPb;
- (BOOL) hasTeacherPb;
- (BOOL) hasSchoolPb;
@property (readonly) SInt64 id;
@property (readonly) SInt64 schoolId;
@property (readonly, strong) NSString* uuid;
@property (readonly, strong) NSString* username;
@property (readonly, strong) NSString* password;
@property (readonly, strong) NSString* name;
@property (readonly) SInt32 userType;
@property (readonly) SInt64 phaseId;
@property (readonly) SInt32 gender;
@property (readonly, strong) NSString* address;
@property (readonly, strong) NSString* email;
@property (readonly, strong) NSString* token;
@property (readonly, strong) NSString* schoolName;
@property (readonly, strong) NSString* portrait;
@property (readonly, strong) NSData* file;
@property (readonly, strong) ParentsPb* parentsPb;
@property (readonly, strong) TeacherPb* teacherPb;
@property (readonly, strong) SchoolPb* schoolPb;
@property (readonly, strong) NSArray * funcCtrlPb;
- (FuncCtrlPb*)funcCtrlPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (UserPbBuilder*) builder;
+ (UserPbBuilder*) builder;
+ (UserPbBuilder*) builderWithPrototype:(UserPb*) prototype;
- (UserPbBuilder*) toBuilder;

+ (UserPb*) parseFromData:(NSData*) data;
+ (UserPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserPb*) parseFromInputStream:(NSInputStream*) input;
+ (UserPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (UserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (UserPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface UserPbBuilder : PBGeneratedMessageBuilder {
@private
  UserPb* resultUserPb;
}

- (UserPb*) defaultInstance;

- (UserPbBuilder*) clear;
- (UserPbBuilder*) clone;

- (UserPb*) build;
- (UserPb*) buildPartial;

- (UserPbBuilder*) mergeFrom:(UserPb*) other;
- (UserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (UserPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (UserPbBuilder*) setId:(SInt64) value;
- (UserPbBuilder*) clearId;

- (BOOL) hasSchoolId;
- (SInt64) schoolId;
- (UserPbBuilder*) setSchoolId:(SInt64) value;
- (UserPbBuilder*) clearSchoolId;

- (BOOL) hasUuid;
- (NSString*) uuid;
- (UserPbBuilder*) setUuid:(NSString*) value;
- (UserPbBuilder*) clearUuid;

- (BOOL) hasUsername;
- (NSString*) username;
- (UserPbBuilder*) setUsername:(NSString*) value;
- (UserPbBuilder*) clearUsername;

- (BOOL) hasPassword;
- (NSString*) password;
- (UserPbBuilder*) setPassword:(NSString*) value;
- (UserPbBuilder*) clearPassword;

- (BOOL) hasName;
- (NSString*) name;
- (UserPbBuilder*) setName:(NSString*) value;
- (UserPbBuilder*) clearName;

- (BOOL) hasUserType;
- (SInt32) userType;
- (UserPbBuilder*) setUserType:(SInt32) value;
- (UserPbBuilder*) clearUserType;

- (BOOL) hasPhaseId;
- (SInt64) phaseId;
- (UserPbBuilder*) setPhaseId:(SInt64) value;
- (UserPbBuilder*) clearPhaseId;

- (BOOL) hasGender;
- (SInt32) gender;
- (UserPbBuilder*) setGender:(SInt32) value;
- (UserPbBuilder*) clearGender;

- (BOOL) hasAddress;
- (NSString*) address;
- (UserPbBuilder*) setAddress:(NSString*) value;
- (UserPbBuilder*) clearAddress;

- (BOOL) hasEmail;
- (NSString*) email;
- (UserPbBuilder*) setEmail:(NSString*) value;
- (UserPbBuilder*) clearEmail;

- (BOOL) hasToken;
- (NSString*) token;
- (UserPbBuilder*) setToken:(NSString*) value;
- (UserPbBuilder*) clearToken;

- (BOOL) hasSchoolName;
- (NSString*) schoolName;
- (UserPbBuilder*) setSchoolName:(NSString*) value;
- (UserPbBuilder*) clearSchoolName;

- (BOOL) hasPortrait;
- (NSString*) portrait;
- (UserPbBuilder*) setPortrait:(NSString*) value;
- (UserPbBuilder*) clearPortrait;

- (BOOL) hasFile;
- (NSData*) file;
- (UserPbBuilder*) setFile:(NSData*) value;
- (UserPbBuilder*) clearFile;

- (BOOL) hasParentsPb;
- (ParentsPb*) parentsPb;
- (UserPbBuilder*) setParentsPb:(ParentsPb*) value;
- (UserPbBuilder*) setParentsPbBuilder:(ParentsPbBuilder*) builderForValue;
- (UserPbBuilder*) mergeParentsPb:(ParentsPb*) value;
- (UserPbBuilder*) clearParentsPb;

- (BOOL) hasTeacherPb;
- (TeacherPb*) teacherPb;
- (UserPbBuilder*) setTeacherPb:(TeacherPb*) value;
- (UserPbBuilder*) setTeacherPbBuilder:(TeacherPbBuilder*) builderForValue;
- (UserPbBuilder*) mergeTeacherPb:(TeacherPb*) value;
- (UserPbBuilder*) clearTeacherPb;

- (BOOL) hasSchoolPb;
- (SchoolPb*) schoolPb;
- (UserPbBuilder*) setSchoolPb:(SchoolPb*) value;
- (UserPbBuilder*) setSchoolPbBuilder:(SchoolPbBuilder*) builderForValue;
- (UserPbBuilder*) mergeSchoolPb:(SchoolPb*) value;
- (UserPbBuilder*) clearSchoolPb;

- (NSMutableArray *)funcCtrlPb;
- (FuncCtrlPb*)funcCtrlPbAtIndex:(NSUInteger)index;
- (UserPbBuilder *)addFuncCtrlPb:(FuncCtrlPb*)value;
- (UserPbBuilder *)setFuncCtrlPbArray:(NSArray *)array;
- (UserPbBuilder *)clearFuncCtrlPb;
@end

#define SchoolPb_id @"id"
#define SchoolPb_name @"name"
#define SchoolPb_year @"year"
#define SchoolPb_semester @"semester"
@interface SchoolPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasYear_:1;
  BOOL hasSemester_:1;
  BOOL hasName_:1;
  SInt64 id;
  SInt64 year;
  SInt32 semester;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasYear;
- (BOOL) hasSemester;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly) SInt64 year;
@property (readonly) SInt32 semester;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (SchoolPbBuilder*) builder;
+ (SchoolPbBuilder*) builder;
+ (SchoolPbBuilder*) builderWithPrototype:(SchoolPb*) prototype;
- (SchoolPbBuilder*) toBuilder;

+ (SchoolPb*) parseFromData:(NSData*) data;
+ (SchoolPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SchoolPb*) parseFromInputStream:(NSInputStream*) input;
+ (SchoolPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (SchoolPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (SchoolPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface SchoolPbBuilder : PBGeneratedMessageBuilder {
@private
  SchoolPb* resultSchoolPb;
}

- (SchoolPb*) defaultInstance;

- (SchoolPbBuilder*) clear;
- (SchoolPbBuilder*) clone;

- (SchoolPb*) build;
- (SchoolPb*) buildPartial;

- (SchoolPbBuilder*) mergeFrom:(SchoolPb*) other;
- (SchoolPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (SchoolPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (SchoolPbBuilder*) setId:(SInt64) value;
- (SchoolPbBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (SchoolPbBuilder*) setName:(NSString*) value;
- (SchoolPbBuilder*) clearName;

- (BOOL) hasYear;
- (SInt64) year;
- (SchoolPbBuilder*) setYear:(SInt64) value;
- (SchoolPbBuilder*) clearYear;

- (BOOL) hasSemester;
- (SInt32) semester;
- (SchoolPbBuilder*) setSemester:(SInt32) value;
- (SchoolPbBuilder*) clearSemester;
@end

#define FuncCtrlPb_schoolId @"schoolId"
#define FuncCtrlPb_funcCode @"funcCode"
#define FuncCtrlPb_status @"status"
@interface FuncCtrlPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSchoolId_:1;
  BOOL hasStatus_:1;
  BOOL hasFuncCode_:1;
  SInt64 schoolId;
  SInt32 status;
  NSString* funcCode;
}
- (BOOL) hasSchoolId;
- (BOOL) hasFuncCode;
- (BOOL) hasStatus;
@property (readonly) SInt64 schoolId;
@property (readonly, strong) NSString* funcCode;
@property (readonly) SInt32 status;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (FuncCtrlPbBuilder*) builder;
+ (FuncCtrlPbBuilder*) builder;
+ (FuncCtrlPbBuilder*) builderWithPrototype:(FuncCtrlPb*) prototype;
- (FuncCtrlPbBuilder*) toBuilder;

+ (FuncCtrlPb*) parseFromData:(NSData*) data;
+ (FuncCtrlPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FuncCtrlPb*) parseFromInputStream:(NSInputStream*) input;
+ (FuncCtrlPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (FuncCtrlPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (FuncCtrlPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface FuncCtrlPbBuilder : PBGeneratedMessageBuilder {
@private
  FuncCtrlPb* resultFuncCtrlPb;
}

- (FuncCtrlPb*) defaultInstance;

- (FuncCtrlPbBuilder*) clear;
- (FuncCtrlPbBuilder*) clone;

- (FuncCtrlPb*) build;
- (FuncCtrlPb*) buildPartial;

- (FuncCtrlPbBuilder*) mergeFrom:(FuncCtrlPb*) other;
- (FuncCtrlPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (FuncCtrlPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasSchoolId;
- (SInt64) schoolId;
- (FuncCtrlPbBuilder*) setSchoolId:(SInt64) value;
- (FuncCtrlPbBuilder*) clearSchoolId;

- (BOOL) hasFuncCode;
- (NSString*) funcCode;
- (FuncCtrlPbBuilder*) setFuncCode:(NSString*) value;
- (FuncCtrlPbBuilder*) clearFuncCode;

- (BOOL) hasStatus;
- (SInt32) status;
- (FuncCtrlPbBuilder*) setStatus:(SInt32) value;
- (FuncCtrlPbBuilder*) clearStatus;
@end

#define ParentsPb_mobile @"mobile"
#define ParentsPb_studentPb @"studentPb"
#define ParentsPb_classPb @"classPb"
@interface ParentsPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasMobile_:1;
  NSString* mobile;
  NSMutableArray * studentPbArray;
  NSMutableArray * classPbArray;
}
- (BOOL) hasMobile;
@property (readonly, strong) NSString* mobile;
@property (readonly, strong) NSArray * studentPb;
@property (readonly, strong) NSArray * classPb;
- (StudentPb*)studentPbAtIndex:(NSUInteger)index;
- (FscClassPb*)classPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (ParentsPbBuilder*) builder;
+ (ParentsPbBuilder*) builder;
+ (ParentsPbBuilder*) builderWithPrototype:(ParentsPb*) prototype;
- (ParentsPbBuilder*) toBuilder;

+ (ParentsPb*) parseFromData:(NSData*) data;
+ (ParentsPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ParentsPb*) parseFromInputStream:(NSInputStream*) input;
+ (ParentsPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (ParentsPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (ParentsPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface ParentsPbBuilder : PBGeneratedMessageBuilder {
@private
  ParentsPb* resultParentsPb;
}

- (ParentsPb*) defaultInstance;

- (ParentsPbBuilder*) clear;
- (ParentsPbBuilder*) clone;

- (ParentsPb*) build;
- (ParentsPb*) buildPartial;

- (ParentsPbBuilder*) mergeFrom:(ParentsPb*) other;
- (ParentsPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (ParentsPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobile;
- (NSString*) mobile;
- (ParentsPbBuilder*) setMobile:(NSString*) value;
- (ParentsPbBuilder*) clearMobile;

- (NSMutableArray *)studentPb;
- (StudentPb*)studentPbAtIndex:(NSUInteger)index;
- (ParentsPbBuilder *)addStudentPb:(StudentPb*)value;
- (ParentsPbBuilder *)setStudentPbArray:(NSArray *)array;
- (ParentsPbBuilder *)clearStudentPb;

- (NSMutableArray *)classPb;
- (FscClassPb*)classPbAtIndex:(NSUInteger)index;
- (ParentsPbBuilder *)addClassPb:(FscClassPb*)value;
- (ParentsPbBuilder *)setClassPbArray:(NSArray *)array;
- (ParentsPbBuilder *)clearClassPb;
@end

#define TeacherPb_mobile @"mobile"
#define TeacherPb_title @"title"
#define TeacherPb_subjectId @"subjectId"
#define TeacherPb_subjectName @"subjectName"
#define TeacherPb_classPb @"classPb"
#define TeacherPb_teachPlanPb @"teachPlanPb"
@interface TeacherPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasSubjectId_:1;
  BOOL hasMobile_:1;
  BOOL hasTitle_:1;
  BOOL hasSubjectName_:1;
  SInt64 subjectId;
  NSString* mobile;
  NSString* title;
  NSString* subjectName;
  NSMutableArray * classPbArray;
  NSMutableArray * teachPlanPbArray;
}
- (BOOL) hasMobile;
- (BOOL) hasTitle;
- (BOOL) hasSubjectId;
- (BOOL) hasSubjectName;
@property (readonly, strong) NSString* mobile;
@property (readonly, strong) NSString* title;
@property (readonly) SInt64 subjectId;
@property (readonly, strong) NSString* subjectName;
@property (readonly, strong) NSArray * classPb;
@property (readonly, strong) NSArray * teachPlanPb;
- (FscClassPb*)classPbAtIndex:(NSUInteger)index;
- (TeachPlanPb*)teachPlanPbAtIndex:(NSUInteger)index;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (TeacherPbBuilder*) builder;
+ (TeacherPbBuilder*) builder;
+ (TeacherPbBuilder*) builderWithPrototype:(TeacherPb*) prototype;
- (TeacherPbBuilder*) toBuilder;

+ (TeacherPb*) parseFromData:(NSData*) data;
+ (TeacherPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeacherPb*) parseFromInputStream:(NSInputStream*) input;
+ (TeacherPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (TeacherPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (TeacherPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface TeacherPbBuilder : PBGeneratedMessageBuilder {
@private
  TeacherPb* resultTeacherPb;
}

- (TeacherPb*) defaultInstance;

- (TeacherPbBuilder*) clear;
- (TeacherPbBuilder*) clone;

- (TeacherPb*) build;
- (TeacherPb*) buildPartial;

- (TeacherPbBuilder*) mergeFrom:(TeacherPb*) other;
- (TeacherPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (TeacherPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasMobile;
- (NSString*) mobile;
- (TeacherPbBuilder*) setMobile:(NSString*) value;
- (TeacherPbBuilder*) clearMobile;

- (BOOL) hasTitle;
- (NSString*) title;
- (TeacherPbBuilder*) setTitle:(NSString*) value;
- (TeacherPbBuilder*) clearTitle;

- (BOOL) hasSubjectId;
- (SInt64) subjectId;
- (TeacherPbBuilder*) setSubjectId:(SInt64) value;
- (TeacherPbBuilder*) clearSubjectId;

- (BOOL) hasSubjectName;
- (NSString*) subjectName;
- (TeacherPbBuilder*) setSubjectName:(NSString*) value;
- (TeacherPbBuilder*) clearSubjectName;

- (NSMutableArray *)classPb;
- (FscClassPb*)classPbAtIndex:(NSUInteger)index;
- (TeacherPbBuilder *)addClassPb:(FscClassPb*)value;
- (TeacherPbBuilder *)setClassPbArray:(NSArray *)array;
- (TeacherPbBuilder *)clearClassPb;

- (NSMutableArray *)teachPlanPb;
- (TeachPlanPb*)teachPlanPbAtIndex:(NSUInteger)index;
- (TeacherPbBuilder *)addTeachPlanPb:(TeachPlanPb*)value;
- (TeacherPbBuilder *)setTeachPlanPbArray:(NSArray *)array;
- (TeacherPbBuilder *)clearTeachPlanPb;
@end

#define StudentPb_id @"id"
#define StudentPb_name @"name"
#define StudentPb_classId @"classId"
#define StudentPb_gradeId @"gradeId"
@interface StudentPb : PBGeneratedMessage<GeneratedMessageProtocol> {
@private
  BOOL hasId_:1;
  BOOL hasClassId_:1;
  BOOL hasGradeId_:1;
  BOOL hasName_:1;
  SInt64 id;
  SInt64 classId;
  SInt64 gradeId;
  NSString* name;
}
- (BOOL) hasId;
- (BOOL) hasName;
- (BOOL) hasClassId;
- (BOOL) hasGradeId;
@property (readonly) SInt64 id;
@property (readonly, strong) NSString* name;
@property (readonly) SInt64 classId;
@property (readonly) SInt64 gradeId;

+ (instancetype) defaultInstance;
- (instancetype) defaultInstance;

- (BOOL) isInitialized;
- (void) writeToCodedOutputStream:(PBCodedOutputStream*) output;
- (StudentPbBuilder*) builder;
+ (StudentPbBuilder*) builder;
+ (StudentPbBuilder*) builderWithPrototype:(StudentPb*) prototype;
- (StudentPbBuilder*) toBuilder;

+ (StudentPb*) parseFromData:(NSData*) data;
+ (StudentPb*) parseFromData:(NSData*) data extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StudentPb*) parseFromInputStream:(NSInputStream*) input;
+ (StudentPb*) parseFromInputStream:(NSInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
+ (StudentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input;
+ (StudentPb*) parseFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;
@end

@interface StudentPbBuilder : PBGeneratedMessageBuilder {
@private
  StudentPb* resultStudentPb;
}

- (StudentPb*) defaultInstance;

- (StudentPbBuilder*) clear;
- (StudentPbBuilder*) clone;

- (StudentPb*) build;
- (StudentPb*) buildPartial;

- (StudentPbBuilder*) mergeFrom:(StudentPb*) other;
- (StudentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input;
- (StudentPbBuilder*) mergeFromCodedInputStream:(PBCodedInputStream*) input extensionRegistry:(PBExtensionRegistry*) extensionRegistry;

- (BOOL) hasId;
- (SInt64) id;
- (StudentPbBuilder*) setId:(SInt64) value;
- (StudentPbBuilder*) clearId;

- (BOOL) hasName;
- (NSString*) name;
- (StudentPbBuilder*) setName:(NSString*) value;
- (StudentPbBuilder*) clearName;

- (BOOL) hasClassId;
- (SInt64) classId;
- (StudentPbBuilder*) setClassId:(SInt64) value;
- (StudentPbBuilder*) clearClassId;

- (BOOL) hasGradeId;
- (SInt64) gradeId;
- (StudentPbBuilder*) setGradeId:(SInt64) value;
- (StudentPbBuilder*) clearGradeId;
@end


// @@protoc_insertion_point(global_scope)
